Add SSM > Maintenance Windows. Closes #83
turbot/steampipe-plugin-aws pull request #108
Opened 2021-03-05 06:16 UTC by visiit

vishalkumar@Vishals-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_ssm_maintenance_window
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_ssm_maintenance_window []

PRETEST: tests/aws_ssm_maintenance_window

TEST: tests/aws_ssm_maintenance_window
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_ssm_maintenance_window.named_test_resource: Creating...
aws_ssm_maintenance_window.named_test_resource: Creation complete after 5s [id=mw-00501ee9607ec2ceb]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_region = us-east-1
resource_aka = arn:aws:ssm:us-east-1:986325076436:maintenancewindow/mw-00501ee9607ec2ceb
resource_id = mw-00501ee9607ec2ceb
resource_name = turbottest50804

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "arn:aws:ssm:us-east-1:986325076436:maintenancewindow/mw-00501ee9607ec2ceb"
    ],
    "name": "turbottest50804",
    "tags": {
      "name": "turbottest50804"
    },
    "title": "turbottest50804"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "name": "turbottest50804",
    "partition": "aws",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest50804"
    },
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest50804"
      }
    ],
    "targets": [],
    "tasks": [],
    "window_id": "mw-00501ee9607ec2ceb"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "986325076436",
    "akas": [
      "arn:aws:ssm:us-east-1:986325076436:maintenancewindow/mw-00501ee9607ec2ceb"
    ],
    "region": "us-east-1",
    "tags": {
      "name": "turbottest50804"
    },
    "title": "turbottest50804"
  }
]
✔ PASSED

POSTTEST: tests/aws_ssm_maintenance_window

TEARDOWN: tests/aws_ssm_maintenance_window

SUMMARY:

1/1 passed.

2021-03-05 14:29 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +				Description: "The name of the  Maintenance Window.",
```suggestion
				Description: "The name of the Maintenance Window.",
```

2021-03-05 14:30 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +				Description: "Whether targets must be registered with the Maintenance Window before tasks can be defined for those targets.",
```suggestion
				Description: "Indicates whether targets must be registered with the Maintenance Window before tasks can be defined for those targets.",
```

2021-03-05 14:34 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_INT,
```

2021-03-05 14:34 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +				Type:        proto.ColumnType_STRING,
![image](https://user-images.githubusercontent.com/38218418/110129479-04bb3c00-7dee-11eb-82f2-a796b4cb4c20.png)

2021-03-05 14:38 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +}
Generally we follow the below order
1. LIST FUNCTION
2. HYDRATE FUNCTIONS
3. TRANSFORM FUNCTIONS

2021-03-05 14:41 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +
//// TRANSFORM FUNCTIONS

2021-03-05 14:45 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +
Return nil if no tag is set
```suggestion
  if tagList == nil {
    return nil, nil
  }
```

2021-03-05 14:45 UTC, Subhajit97 commented on docs/tables/aws_ssm_maintenance_window.md
> +
```suggestion
```

2021-03-05 14:46 UTC, Subhajit97 commented on docs/tables/aws_ssm_maintenance_window.md
> +### Whether the maintenance window is enable.
```suggestion

### Whether the maintenance window is enable.
```

2021-03-05 14:46 UTC, Subhajit97 commented on docs/tables/aws_ssm_maintenance_window.md
> +  enabled
```suggestion
  enabled;
```

2021-03-05 14:47 UTC, Subhajit97 commented on aws-test/tests/aws_ssm_maintenance_window/test-get-query.sql
> +where window_id = '{{ output.resource_id.value }}'
```suggestion
where window_id = '{{ output.resource_id.value }}';
```

2021-03-05 14:48 UTC, Subhajit97 commented on aws-test/tests/aws_ssm_maintenance_window/test-list-expected.json
> +]
```suggestion
[
  {
    "name": "{{ output.resource_name.value }}",
    "partition": "aws",
    "region": "{{ output.aws_region.value }}",
    "tags": {
      "name": "{{ output.resource_name.value }}"
    },
    "tags_src": [
      {
        "Key": "name",
        "Value": "{{ output.resource_name.value }}"
      }
    ],
    "targets": [],
    "tasks": [],
    "window_id": "{{ output.resource_id.value }}"
  }
]
```

2021-03-05 14:48 UTC, Subhajit97 commented on aws-test/tests/aws_ssm_maintenance_window/test-list-query.sql
> +where akas::text = '["{{output.resource_aka.value}}"]'
```suggestion
where akas::text = '["{{output.resource_aka.value}}"]';
```

2021-03-05 14:49 UTC, Subhajit97 commented on aws-test/tests/aws_ssm_maintenance_window/test-turbot-expected.json
> +]
```suggestion
[
  {
    "account_id": "{{ output.account_id.value }}",
    "akas": ["{{ output.resource_aka.value }}"],
    "region": "{{ output.aws_region.value }}",
    "tags": {
      "name": "{{ output.resource_name.value }}"
    },
    "title": "{{ output.resource_name.value }}"
  }
]
```

2021-03-05 14:49 UTC, Subhajit97 commented on aws-test/tests/aws_ssm_maintenance_window/test-turbot-query.sql
> +where window_id = '{{ output.resource_id.value }}'
```suggestion
where window_id = '{{ output.resource_id.value }}';
```

2021-03-05 14:49 UTC, Subhajit97 commented on aws/plugin.go
> +			"aws_ssm_maintenance_window":             tableAwsSSMMaintenanceWindow(ctx),
Sort the list

2021-03-05 14:52 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +
Can we add below columns?
```
created_date
end_date
schedule_timezone
start_date
```

2021-03-05 14:53 UTC, Subhajit97 commented on aws/table_aws_ssm_maintenance_window.go
> +
![image](https://user-images.githubusercontent.com/38218418/110131836-962bad80-7df0-11eb-8b7c-f4fb38bfae6b.png)

2021-03-05 14:58 UTC, Subhajit97 requested changes
Make suggested changes

2021-03-10 08:38 UTC, visiit commented on aws/table_aws_ssm_maintenance_window.go
> +				})
resolved

2021-03-11 00:41 UTC, cbruno10 approved these changes

2021-03-11 00:42 UTC, merged