Add Kinesis > Stream table. closes #111
turbot/steampipe-plugin-aws pull request #125
Opened 2021-03-08 14:56 UTC by sayan133

2021-03-15 07:13 UTC, Paulami30 commented on aws-test/tests/aws_kinesis_stream/test-get-query.sql
> +
remove space

2021-03-15 07:16 UTC, Paulami30 commented on aws/plugin.go
> +			"aws_kinesis_stream":                     tableAwsKinesisStream(ctx),
sort the list

2021-03-15 07:21 UTC, Paulami30 commented on aws/table_aws_kinesis_stream.go
> +			},
```suggestion
			},
			
```

2021-03-15 07:24 UTC, Paulami30 commented on docs/tables/aws_kinesis_stream.md
> +```
```
select
  stream_name,
  stream_arn,
  stream_status,
  consumer_count,
  stream_creation_timestamp,
  region
from
  aws_kinesis_stream;
```

2021-03-15 07:24 UTC, Paulami30 commented on docs/tables/aws_kinesis_stream.md
> +```
Fix indentation for all the queries

2021-03-15 07:26 UTC, Paulami30 commented on docs/tables/aws_kinesis_stream.md
> +	consumer_count = '0';
```suggestion
	consumer_count = 0;
```
consumer_count is integer

2021-03-15 07:29 UTC, Paulami30 commented on docs/tables/aws_kinesis_stream.md
> +	And key_id = 'alias/aws/kinesis';
```suggestion
	and key_id = 'alias/aws/kinesis';
```

2021-03-16 04:18 UTC, Paulami30 commented on aws/table_aws_kinesis_stream.go
> +				Transform:   transform.FromValue(),
can we get the aka from StreamDescription.StreamARN?

2021-03-16 12:01 UTC, Paulami30 submitted a review, later dismissed

2021-03-16 12:05 UTC, Subhajit97 commented on aws/table_aws_kinesis_stream.go
> +				Description: "A list of tags associated with StreamName.",
```suggestion
				Description: "A list of tags associated with the stream.",
```

2021-03-16 12:07 UTC, Subhajit97 commented on aws/table_aws_kinesis_stream.go
> +	streamName = *h.Item.(*kinesis.DescribeStreamOutput).StreamDescription.StreamName
```suggestion
	streamName := *h.Item.(*kinesis.DescribeStreamOutput).StreamDescription.StreamName
```

2021-03-16 12:09 UTC, Subhajit97 commented on aws/table_aws_kinesis_stream.go
> +
Return nil, if `tagList` is null
```suggestion

if tagList == nil {
  return nil, nil
}
```

2021-03-16 12:12 UTC, Subhajit97 commented on docs/tables/aws_kinesis_stream.md
> +### List all the encrypted streams which are not encrypted using customer managed key
```suggestion
### List of streams which are not encrypted using CMK
```

2021-03-16 12:14 UTC, Subhajit97 commented on aws-test/tests/aws_kinesis_stream/variables.json
> +}
```suggestion
```

2021-03-16 12:14 UTC, Subhajit97 commented on aws-test/tests/aws_kinesis_stream/test-turbot-expected.json
> +    "title": "{{ output.resource_name.value }}"
```suggestion
    "title": "{{ resourceName }}"
```

2021-03-16 12:15 UTC, Subhajit97 commented on aws-test/tests/aws_kinesis_stream/test-turbot-query.sql
> +where stream_name = '{{ output.resource_name.value }}';
```suggestion
where stream_name = '{{ resourceName }}';
```

2021-03-16 12:15 UTC, Subhajit97 commented on aws-test/tests/aws_kinesis_stream/test-list-expected.json
> +    "stream_name": "{{ output.resource_name.value }}",
```suggestion
    "stream_name": "{{ resourceName }}",
```

2021-03-16 12:17 UTC, Subhajit97 commented on aws-test/tests/aws_kinesis_stream/test-get-query.sql
> +select stream_name, stream_arn, stream_status, encryption_type, key_id, retention_period_hours
Also verify `account_id`, `partition` and `region`

2021-03-16 12:17 UTC, Subhajit97 requested changes
Make suggested changes, and also add tests logs

2021-03-17 12:26 UTC, Subhajit97 approved these changes
LGTM

2021-03-18 11:26 UTC, cbruno10 approved these changes

2021-03-18 11:26 UTC, merged