Add table `aws_appconfig_application` Closes #1238
turbot/steampipe-plugin-aws pull request #1253
Opened 2022-08-24 21:27 UTC by karanpopat

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Outputs:

description = "Example AppConfig Application"
id = "06ncx42"
resource_aka = "arn:aws:appconfig:us-east-1:111122223333:application/06ncx42"
resource_name = "turbottest69805"
tags_all = tomap({
  "Type" = "AppConfig Application"
})

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:appconfig:us-east-1:111122223333:application/06ncx42",
    "description": "Example AppConfig Application",
    "id": "06ncx42",
    "name": "turbottest69805",
    "tags": {
      "Type": "AppConfig Application"
    }
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:appconfig:us-east-1:111122223333:application/06ncx42",
    "description": "Example AppConfig Application",
    "id": "06ncx42",
    "name": "turbottest69805",
    "tags": {
      "Type": "AppConfig Application"
    }
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:appconfig:us-east-1:111122223333:application/06ncx42"
    ],
    "tags": {
      "Type": "AppConfig Application"
    },
    "title": "turbottest69805"
  }
]
✔ PASSED

POSTTEST: tests/aws_appconfig_application

TEARDOWN: tests/aws_appconfig_application

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```sql
> select
  arn,
  id,
  name,
  description,
  tags
from
  aws_appconfig_application;
+--------------------------------------------------------------+---------+-----------------+-------------------------------+----------------------------------+
| arn                                                          | id      | name            | description                   | tags                             |
+--------------------------------------------------------------+---------+-----------------+-------------------------------+----------------------------------+
| arn:aws:appconfig:us-east-1:111122223333:application/ikjegeg | ikjegeg | turbottest21720 | Example AppConfig Application | {"Type":"AppConfig Application"} |
+--------------------------------------------------------------+---------+-----------------+-------------------------------+----------------------------------+
```
</details>

2022-09-09 08:51 UTC, ParthaI commented on aws/service_v2.go
> +func AppConfigService(ctx context.Context, d *plugin.QueryData) (*appconfig.Client, error) {
```suggestion
func AppConfigClient(ctx context.Context, d *plugin.QueryData) (*appconfig.Client, error) {
```

2022-09-09 08:51 UTC, ParthaI commented on aws/table_aws_appconfig_application.go
> +	svc, err := AppConfigService(ctx, d)
```suggestion
	svc, err := AppConfigClient(ctx, d)
```

2022-09-09 08:52 UTC, ParthaI commented on aws/table_aws_appconfig_application.go
> +	svc, err := AppConfigService(ctx, d)
```suggestion
	svc, err := AppConfigClient(ctx, d)
```

2022-09-09 08:53 UTC, ParthaI commented on aws/table_aws_appconfig_application.go
> +	svc, err := AppConfigService(ctx, d)
```suggestion
	svc, err := AppConfigClient(ctx, d)
```

2022-09-13 08:11 UTC, khushboo9024 approved these changes

2022-09-14 20:33 UTC, cbruno10 requested changes
Please see review comments, thanks!

2022-09-14 20:33 UTC, cbruno10 commented on docs/tables/aws_appconfig_application.md
> +### Basic info
Based off of the lack of examples and useful columns, it's hard to tell why this table is required. @karanpopat @khushboo9024 Do you know why the request came up to create this table? Is it meant to join with another table's data? Do we need other AppConfig tables for this table to be useful?

2022-09-15 13:11 UTC, cbruno10 commented on docs/tables/aws_appconfig_application.md
> +### Basic info
While this table by itself is not very useful, later we will add tables like `aws_appconfig_environment`, which will use this table as a parent hydrate. So we'll add this table for now and then add additional AppConfig tables later on.

2022-09-15 13:11 UTC, cbruno10 approved these changes

2022-09-15 13:11 UTC, merged