Add table_aws_elasticache_cluster closes #112
turbot/steampipe-plugin-aws pull request #130
Opened 2021-03-09 10:18 UTC by Subhajit97

2021-03-10 06:29 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +				Description: "A list of clusters. ",
```suggestion
				Description: "A list of clusters.",
```

2021-03-10 06:33 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +				Description: "A list of tags associated with StreamName.",
```suggestion
				Description: "A list of tags associated with the cluster.",
```

2021-03-10 06:33 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +// LIST FUNCTION
```suggestion
//// LIST FUNCTION
```

2021-03-10 06:34 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +// HYDRATE FUNCTIONS
```suggestion
//// HYDRATE FUNCTIONS
```

2021-03-10 06:35 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +	CacheClusterID := quals["cache_cluster_id"].GetStringValue()
Use lowerCamelCase format when define any variable.

2021-03-10 06:35 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +		CacheClusterId: aws.String(CacheClusterID),
```suggestion
		CacheClusterId: aws.String(cacheClusterID),
```

2021-03-10 06:36 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +// TRANSFORM FUNCTIONS
```suggestion
//// TRANSFORM FUNCTIONS
```

2021-03-10 06:37 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +				Transform:   transform.From(elastiCacheClusterTurbotData),
```suggestion
				Transform:   transform.FromField("CacheClusterId"),
```

2021-03-10 06:38 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +}
Use `transform.FromField()` instead of adding a transform function for `title`.
```suggestion
```

2021-03-10 06:44 UTC, Subhajit97 commented on aws/plugin.go
> +			"aws_elasticache_cluster":                tableAwsElasticCacheCluster(ctx),
Sort the list

2021-03-10 06:44 UTC, Subhajit97 commented on aws-test/tests/aws_elasticache_cluster/variables.tf
> +  vpc_id            = "${aws_vpc.my_vpc.id}"
```suggestion
  vpc_id            = aws_vpc.my_vpc.id
```

2021-03-10 06:45 UTC, Subhajit97 commented on aws-test/tests/aws_elasticache_cluster/variables.tf
> +  subnet_ids = ["${aws_subnet.my_subnet.id}"]
```suggestion
  subnet_ids = [aws_subnet.my_subnet.id]
```

2021-03-10 06:47 UTC, Subhajit97 commented on aws-test/tests/aws_elasticache_cluster/test-list-query.sql
> +where cache_cluster_id = '{{ output.resource_id.value }}';
Use `arn` instead of using `cache_cluster_id` for list call, as `cache_cluster_id` is used for GET.

2021-03-10 06:49 UTC, Subhajit97 commented on docs/tables/aws_elastcache_cluster.md
> +	not at_rest_encryption_enabled;
```suggestion
select 
  cache_cluster_id, 
  cache_node_type, 
  at_rest_encryption_enabled 
from 
  aws_elasticache_cluster 
where 
  not at_rest_encryption_enabled;
```

2021-03-10 06:50 UTC, Subhajit97 commented on docs/tables/aws_elastcache_cluster.md
> +	preferred_availability_zone <> 'Multiple';
```suggestion
select
  cache_cluster_id,
  preferred_availability_zone
from
  aws_elasticache_cluster
where
  preferred_availability_zone <> 'Multiple';
```

2021-03-10 06:51 UTC, Subhajit97 commented on docs/tables/aws_elastcache_cluster.md
> +	not transit_encryption_enabled;
```suggestion
select
  cache_cluster_id,
  cache_node_type,
  transit_encryption_enabled
from
  aws_elasticache_cluster
where
  not transit_encryption_enabled;
```

2021-03-10 06:53 UTC, Subhajit97 commented on docs/tables/aws_elastcache_cluster.md
> +	notification_configuration ->> 'TopicStatus' = 'inactive';
```suggestion
select
  cache_cluster_id,
  cache_cluster_status,
  notification_configuration ->> 'TopicArn' as topic_arn,
  notification_configuration ->> 'TopicStatus' as topic_status
from
  aws_elastic_cache_cluster
where
  notification_configuration ->> 'TopicStatus' = 'inactive';
```

2021-03-10 06:53 UTC, Subhajit97 commented on docs/tables/aws_elastcache_cluster.md
> +	jsonb_array_elements(security_groups) as sg;
```suggestion
select
  cache_cluster_id,
  sg ->> 'SecurityGroupId' as security_group_id,
  sg ->> 'Status' as status
from
  aws_elasticache_cluster,
  jsonb_array_elements(security_groups) as sg;
```

2021-03-10 06:55 UTC, Subhajit97 reviewed
Make suggested changes, and add the tests log.

2021-03-10 08:16 UTC, Paulami30 commented
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_elasticache_cluster []

PRETEST: tests/aws_elasticache_cluster

TEST: tests/aws_elasticache_cluster
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_vpc.my_vpc: Creating...
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Still creating... [20s elapsed]
aws_vpc.my_vpc: Creation complete after 21s [id=vpc-02be7ba1132c657d4]
aws_subnet.my_subnet: Creating...
aws_subnet.my_subnet: Creation complete after 4s [id=subnet-0356f5bc6fe1a9052]
aws_elasticache_subnet_group.my_subnet_group: Creating...
aws_elasticache_subnet_group.my_subnet_group: Creation complete after 3s [id=turbottest45218]
aws_elasticache_cluster.named_test_resource: Creating...
aws_elasticache_cluster.named_test_resource: Still creating... [10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m0s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m0s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m0s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [4m0s elapsed]
aws_elasticache_cluster.named_test_resource: Creation complete after 4m10s [id=turbottest45218]
data.template_file.resource_aka: Refreshing state...

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

account_id = 352685002396
cache_cluster_id = turbottest45218
resource_aka = arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest45218
resource_id = turbottest45218
resource_name = turbottest45218

Running SQL query: test-get-query.sql
[
  {
    "cache_cluster_id": "turbottest45218",
    "cache_node_type": "cache.t2.micro",
    "engine": "memcached",
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest45218"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest45218"
    ],
    "cache_cluster_id": "turbottest45218",
    "tags": {
      "name": "turbottest45218"
    },
    "title": "turbottest45218"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest45218"
    ],
    "cache_cluster_id": "turbottest45218",
    "cache_node_type": "cache.t2.micro",
    "engine": "memcached",
    "title": "turbottest45218"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_elasticache_cluster

TEARDOWN: tests/aws_elasticache_cluster

SUMMARY:

1/1 passed.

2021-03-10 13:17 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +				Description: "An unique identifier for ElastiCache cluster. ",
```suggestion
				Description: "An unique identifier for ElastiCache cluster.",
```

2021-03-10 13:20 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +
Return `nil`, if `clusterTag.TagList` value is nil.
```suggestion

if clusterTag.TagList == nil {
  return nil, nil
}

```

2021-03-10 14:50 UTC, Subhajit97 commented
LGTM

2021-03-18 11:40 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +func tableAwsElasticCacheCluster(_ context.Context) *plugin.Table {
```suggestion
func tableAwsElasticacheCluster(_ context.Context) *plugin.Table {
```

2021-03-18 11:41 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +			Hydrate:           getElasticCacheCluster,
```suggestion
			Hydrate:           getElastiCacheCluster,
```

2021-03-18 11:41 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +			Hydrate: listElasticCacheClusters,
```suggestion
			Hydrate: listElastiCacheClusters,
```

2021-03-18 11:42 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +func listElasticCacheClusters(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listElastiCacheClusters(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-03-18 11:42 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +func getElasticCacheCluster(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getElastiCacheCluster(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-18 11:42 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +	plugin.Logger(ctx).Trace("getElasticCacheCluster")
```suggestion
	plugin.Logger(ctx).Trace("getElastiCacheCluster")
```

2021-03-18 11:42 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +func listTagsForElasticacheCluster(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func listTagsForElastiCacheCluster(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-18 11:44 UTC, cbruno10 commented on aws/service.go
> +func ElasticacheService(ctx context.Context, d *plugin.QueryData, region string) (*elasticache.ElastiCache, error) {
```suggestion
func ElastiCacheService(ctx context.Context, d *plugin.QueryData, region string) (*elasticache.ElastiCache, error) {
```

2021-03-18 11:44 UTC, cbruno10 commented on aws/service.go
> +// ElasticacheService returns the service connection for AWS Elasticache service
```suggestion
// ElastiCacheService returns the service connection for AWS ElastiCache service
```

2021-03-18 11:44 UTC, cbruno10 commented on aws/service.go
> +		return nil, fmt.Errorf("region must be passed Elasticache")
```suggestion
		return nil, fmt.Errorf("region must be passed ElastiCache")
```

2021-03-18 11:45 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +	svc, err := ElasticacheService(ctx, d, region)
```suggestion
	svc, err := ElastiCacheService(ctx, d, region)
```

2021-03-18 11:45 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +	svc, err := ElasticacheService(ctx, d, region)
```suggestion
	svc, err := ElastiCacheService(ctx, d, region)
```

2021-03-18 11:45 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +	logger.Trace("ListTagsForElasticacheCluster")
```suggestion
	logger.Trace("ListTagsForElastiCacheCluster")
```

2021-03-18 11:45 UTC, cbruno10 commented on aws/table_aws_elasticache_cluster.go
> +	svc, err := ElasticacheService(ctx, d, region)
```suggestion
	svc, err := ElastiCacheService(ctx, d, region)
```

2021-03-18 11:47 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +## Examples
Can you please add an example for `### Basic info`?

2021-03-18 11:47 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### List of unencrypted elasticache clusters
```suggestion
### List unencrypted clusters
```

2021-03-18 11:47 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### List of elasticache clusters whose availability zone count is less than 2
```suggestion
### List clusters whose availability zone count is less than 2
```

2021-03-18 11:48 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### List of unencrypted elasticache clusters
I expanded the description a bit since below we have an example for checking encryption in transit, so good to specify this is for encryption at rest

2021-03-18 11:49 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### List of elasticache cluster that DO NOT enforce encryption in transit
```suggestion
### List clusters that do not enforce encryption in transit
```

2021-03-18 11:50 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### Count of elasticache cluster provisioned with undesired(for example cache.m5.large and cache.m4.4xlarge is desired) node type(s).
```suggestion
### List clusters provisioned with undesired (for example, cache.m5.large and cache.m4.4xlarge are desired) node types.
```

2021-03-18 11:51 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### List of elasticache cluster which has inactive notification configuration topics
```suggestion
### List clusters with inactive notification configuration topics
```

2021-03-18 11:51 UTC, cbruno10 commented on docs/tables/aws_elastcache_cluster.md
> +### Security group details attached with the cache cluster
```suggestion
### Get security group details for each cluster
```

2021-03-18 11:51 UTC, cbruno10 requested changes
@Paulami30 Please see comments, thanks!

2021-03-18 12:56 UTC, Paulami30 commented
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_elasticache_cluster []

PRETEST: tests/aws_elasticache_cluster

TEST: tests/aws_elasticache_cluster
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_vpc.my_vpc: Creating...
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Still creating... [20s elapsed]
aws_vpc.my_vpc: Creation complete after 23s [id=vpc-0954730738dd5ff85]
aws_subnet.my_subnet: Creating...
aws_subnet.my_subnet: Creation complete after 9s [id=subnet-0705be96f66c148be]
aws_elasticache_subnet_group.my_subnet_group: Creating...
aws_elasticache_subnet_group.my_subnet_group: Creation complete after 2s [id=turbottest23563]
aws_elasticache_cluster.named_test_resource: Creating...
aws_elasticache_cluster.named_test_resource: Still creating... [10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m0s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [1m50s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m0s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m10s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m20s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m30s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m40s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [2m51s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m1s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m11s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m21s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m31s elapsed]
aws_elasticache_cluster.named_test_resource: Still creating... [3m41s elapsed]
aws_elasticache_cluster.named_test_resource: Creation complete after 3m42s [id=turbottest23563]
data.template_file.resource_aka: Refreshing state...

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

account_id = 352685002396
cache_cluster_id = turbottest23563
resource_aka = arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest23563
resource_id = turbottest23563
resource_name = turbottest23563

Running SQL query: test-get-query.sql
[
  {
    "cache_cluster_id": "turbottest23563",
    "cache_node_type": "cache.t2.micro",
    "engine": "memcached",
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest23563"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest23563"
    ],
    "cache_cluster_id": "turbottest23563",
    "tags": {
      "name": "turbottest23563"
    },
    "title": "turbottest23563"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:elasticache:us-east-1:352685002396:cluster:turbottest23563"
    ],
    "cache_cluster_id": "turbottest23563",
    "cache_node_type": "cache.t2.micro",
    "engine": "memcached",
    "title": "turbottest23563"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_elasticache_cluster

TEARDOWN: tests/aws_elasticache_cluster

SUMMARY:

1/1 passed.

2021-03-18 13:18 UTC, cbruno10 approved these changes

2021-03-18 13:18 UTC, merged