Add table_aws_eks_cluster. Closes #122
turbot/steampipe-plugin-aws pull request #131
Opened 2021-03-09 11:08 UTC by rajeshbal65

2021-03-10 11:30 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/test-get-query.sql
> +where arn = '{{ output.resource_aka.value }}'
Use `name` to check get query.

2021-03-10 11:32 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/test-get-query.sql
> +where arn = '{{ output.resource_aka.value }}'
```suggestion
where name = '{{ resourceName }}';
```

2021-03-10 11:32 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/test-list-query.sql
> +where arn = '{{ output.resource_aka.value }}'
```suggestion
where arn = '{{ output.resource_aka.value }}';
```

2021-03-10 11:32 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/test-not-found-query.sql
> +where name = 'dummy-{{ resourceName }}'
```suggestion
where name = 'dummy-{{ resourceName }}';
```

2021-03-10 11:32 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/test-turbot-query.sql
> +where name = 'dummy-{{ resourceName }}'
```suggestion
where name = 'dummy-{{ resourceName }}';
```

2021-03-10 11:40 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +	// TODO put me in helper function
```suggestion
```

2021-03-10 11:40 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +	// TODO put me in helper function
```suggestion
```

2021-03-10 11:42 UTC, khushboo9024 commented on docs/tables/aws_eks_cluster.md
> +```
Please add few more queries

2021-03-10 11:52 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +				Hydrate:     getEksCluster,
We should try to keep all the JSON fields at end of the table, please change accordingly

2021-03-10 11:53 UTC, khushboo9024 commented on docs/tables/aws_eks_cluster.md
> +  aws_eks_cluster;;
```suggestion
  aws_eks_cluster;
```

2021-03-10 12:02 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +				Transform:   transform.FromField("tags"),
we are getting the tags in TagsMap format the why we are adding `tags_src` column.

2021-03-10 12:03 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +
```suggestion
//// TABLE DEFINITION
```

2021-03-10 12:17 UTC, khushboo9024 commented on aws-test/tests/aws_eks_cluster/variables.tf
> +# Create AWS > EC2 > Transit Gateway
```suggestion
# Create AWS > EKS > Cluster
```

2021-03-10 12:23 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +				Description: "The Time when the cluster was created.",
```suggestion
				Description: "The Unix epoch timestamp in seconds for when the cluster was created.",
```

2021-03-10 12:29 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +			},
There are few more properties like `KubernetesNetworkConfig` and `EncryptionConfig` which are not added.

2021-03-10 12:29 UTC, khushboo9024 reviewed
Please add integration test logs also.

2021-03-15 06:57 UTC, khushboo9024 commented on aws/table_aws_eks_cluster.go
> +	return op.Cluster, nil
```suggestion
	if op.Cluster != nil {
		return op.Cluster, nil
	}
return nil, nil
```

2021-03-16 13:22 UTC, Subhajit97 commented on aws/table_aws_eks_cluster.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_TIMESTAMP,
```

2021-03-16 13:27 UTC, Subhajit97 commented on aws/table_aws_eks_cluster.go
> +				Name:        "tags",
Though the values are same, we need to define both `tags_src` and `tags`.

2021-03-16 13:27 UTC, Subhajit97 commented on aws/table_aws_eks_cluster.go
> +			},
Add `tags` column

2021-03-16 13:30 UTC, Subhajit97 commented on aws/table_aws_eks_cluster.go
> +	}
Handle pagination
https://github.com/aws/aws-sdk-go/blob/ae393afe895c4d711a69c7d4a4570a48b1c86179/service/eks/api.go#L2210

2021-03-16 13:31 UTC, Subhajit97 commented on aws/table_aws_eks_cluster.go
> +	}
Do we need this check?
Doesn't the API return any `Not Found` error?

2021-03-16 13:32 UTC, Subhajit97 commented on docs/tables/aws_eks_cluster.md
> +### List the Vpc configuration used by cluster
```suggestion
### List the VPC configuration used by cluster
```

2021-03-16 13:36 UTC, Subhajit97 commented on aws-test/tests/aws_eks_cluster/variables.tf
> +  availability_zone = "us-east-1b"
```suggestion
  availability_zone = "${var.aws_region}b"
```

2021-03-16 13:36 UTC, Subhajit97 commented on aws-test/tests/aws_eks_cluster/variables.tf
> +  availability_zone = "us-east-1d"
```suggestion
  availability_zone = "${var.aws_region}d"
```

2021-03-16 13:41 UTC, Subhajit97 commented on docs/tables/aws_eks_cluster.md
> +  i -> 'Types' as types
```suggestion
  i ->> 'Enabled' as enabled,
  i ->> 'Types' as types
```

2021-03-16 13:47 UTC, Subhajit97 requested changes
Make suggested changes, and also add the output of the queries added in docs

2021-03-18 13:45 UTC, cbruno10 approved these changes

2021-03-18 13:49 UTC, merged