Add table_aws_eventbridge_rule. Closes #113
turbot/steampipe-plugin-aws pull request #135
Opened 2021-03-09 11:31 UTC by anisadas

2021-03-09 11:34 UTC, anisadas commented
```
SETUP: tests/aws_eventbridge_rule []

PRETEST: tests/aws_eventbridge_rule

TEST: tests/aws_eventbridge_rule
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
aws_cloudwatch_event_rule.named_test_resource: Creating...
aws_cloudwatch_event_rule.named_test_resource: Creation complete after 5s [id=turbottest973]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:events:us-east-1:986325076436:rule/turbottest973
resource_name = turbottest973

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:events:us-east-1:986325076436:rule/turbottest973",
    "event_pattern": "{\"detail-type\":[\"AWS Console Sign In via CloudTrail\"]}",
    "name": "turbottest973",
    "tags": {
      "name": "turbottest973"
    }
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "arn": "arn:aws:events:us-east-1:986325076436:rule/turbottest973",
    "name": "turbottest973",
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest973"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:events:us-east-1:986325076436:rule/turbottest973",
    "event_bus_name": "default",
    "name": "turbottest973",
    "partition": "aws",
    "region": "us-east-1",
    "state": "ENABLED",
    "tags": {
      "name": "turbottest973"
    },
    "title": "turbottest973"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:events:us-east-1:986325076436:rule/turbottest973"
    ],
    "name": "turbottest973",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest973"
    },
    "title": "turbottest973"
  }
]
✔ PASSED

POSTTEST: tests/aws_eventbridge_rule

TEARDOWN: tests/aws_eventbridge_rule

SUMMARY:

1/1 passed.
```

2021-03-11 07:38 UTC, Paulami30 commented on aws-test/tests/aws_eventbridge_rule/variables.tf
> +
```suggestion
```

2021-03-11 07:38 UTC, Paulami30 commented on aws-test/tests/aws_eventbridge_rule/variables.tf
> +
```suggestion
```

2021-03-11 07:42 UTC, Paulami30 commented on aws/table_aws_eventbridge_rule.go
> +			},
Make `name` as the first column

2021-03-11 07:53 UTC, Paulami30 commented on aws/table_aws_eventbridge_rule.go
> +			/// Standard columns for all tables
```suggestion

			// Standard columns for all tables
```

2021-03-11 08:00 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +### List of rules which are not in enable state
```suggestion
### List of rules which are not enabled
```

2021-03-12 11:53 UTC, Paulami30 commented on aws/table_aws_eventbridge_rule.go
> +		//ResourceType: types.String("Parameter"),
```suggestion
	
```

2021-03-12 12:01 UTC, Paulami30 commented on aws/table_aws_eventbridge_rule.go
> +
```suggestion

//// HYDRATE FUNCTIONS

```

2021-03-12 12:21 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +
```
select
  name,
  arn,
  state,
  created_by,
  event_bus_name
from
  aws_eventbridge_rule;
```

2021-03-17 07:30 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +### List of targets info which are associated with rule
```suggestion
### List of targets info associated with the rule
```

2021-03-17 07:33 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +  cd ->> 'Id' as id
which id is this? change the alias as a meaningful name.

2021-03-17 07:36 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +### List of rules which have iam role
```suggestion
### List of rules which are not associated with any iam role
```

2021-03-17 07:43 UTC, Paulami30 commented on docs/tables/aws_eventbridge_rule.md
> +  cd ->> 'RoleArn' != 'null';
```suggestion
  cd ->> 'RoleArn' = null;
```

2021-03-17 09:44 UTC, Paulami30 submitted a review, later dismissed

2021-03-17 10:20 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +				Type:        proto.ColumnType_STRING,
Can we modify the `event_pattern` value from JSON string to JSON object?

2021-03-17 10:20 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +				Name:        "targets",
Add all the JSON type column at the end

2021-03-17 10:23 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +	arn := *h.Item.(*eventbridge.DescribeRuleOutput).Arn
```suggestion
	arn := h.Item.(*eventbridge.DescribeRuleOutput).Arn
```

2021-03-17 10:23 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +		ResourceARN: &arn,
```suggestion
		ResourceARN: arn,
```

2021-03-17 10:24 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +
```suggestion

if tagList == nil {
  return nil, nil
}

```

2021-03-17 10:27 UTC, Subhajit97 commented on aws/table_aws_eventbridge_rule.go
> +		Description: "AWS EventBridge Rule ",
```suggestion
		Description: "AWS EventBridge Rule",
```

2021-03-17 10:37 UTC, Subhajit97 requested changes
Hi @anisadas, I think we should update the `event_pattern` value from a JSON string to JSON object, which is easy to read.
Also there are some minor changes. Make the suggested changes and add the tests logs and the output of the queries added in docs.

2021-03-17 11:20 UTC, anisadas commented
<details><summary>Results</summary>
<p>

```
select
  name,
  arn,
  state,
  created_by,
  event_bus_name
from
  aws_eventbridge_rule;

+------------------------------------------------+-------------------------------------------------------------------------------------------+-
| name                                           | arn                                                                                       | 
+------------------------------------------------+-------------------------------------------------------------------------------------------+-
| turbot_aws_api_events_kms                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_kms                      | 
| Amazon_Inspector_Assessment_0-4TegljLN_IddROk4 | arn:aws:events:us-east-2:986325076436:rule/Amazon_Inspector_Assessment_0-4TegljLN_IddROk4 | 
| turbot_aws_api_events_eks                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_eks                      | 
| Amazon_Inspector_Assessment_0-yiEZ2sUv_IdX6pZb | arn:aws:events:us-east-2:986325076436:rule/Amazon_Inspector_Assessment_0-yiEZ2sUv_IdX6pZb | 
| turbot_aws_api_events_cloudtrail               | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_cloudtrail               | 
| AutoScalingManagedRule                         | arn:aws:events:us-east-2:986325076436:rule/AutoScalingManagedRule                         | 
| turbot_aws_api_events_codecommit               | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_codecommit               | 
| turbot_aws_api_events_lambda                   | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_lambda                   | 
| turbot_aws_api_events_iam                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_iam                      | 
| turbot_aws_api_events_s3                       | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_s3                       | 
| turbot_aws_api_events_athena                   | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_athena                   | 
| turbot_aws_api_events_rds                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_rds                      | 
| turbot_aws_api_events_cloudformation           | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_cloudformation           | 
| turbot_aws_api_events_lightsail                | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_lightsail                | 
| turbot_aws_api_events_config                   | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_config                   | 
| turbot_aws_api_events_vpc_core                 | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_vpc_core                 | 
| turbot_aws_api_events_sns                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_sns                      | 
| turbot_aws_api_events_ecs                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_ecs                      | 
| turbot_aws_api_events_ecr                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_ecr                      | 
| turbot_aws_api_events_vpc_security             | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_vpc_security             | 
| turbot_aws_api_events_ssm                      | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_ssm                      | 
| turbot_aws_api_events_billingconsole           | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_billingconsole           | 
| turbot_aws_api_events_codebuild                | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_codebuild                | 
| turbot_aws_api_events                          | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events                          | 
| turbot_aws_api_events_s3                       | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_s3                       | 
| turbot_aws_api_events_logs                     | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_logs                     | 
| rupzz                                          | arn:aws:events:us-east-2:986325076436:rule/rupzz                                          | 
| turbot_aws_api_events_sns                      | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_sns                      | 
| turbot_aws_api_events_codecommit               | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_codecommit               | 
| turbot_aws_api_events_logs                     | arn:aws:events:us-east-1:986325076436:rule/turbot_aws_api_events_logs                     | 
| turbot_aws_api_events_iam                      | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_iam                      | 
| bug-fix                                        | arn:aws:events:us-east-2:986325076436:rule/bug-fix                                        | 
| turbot_aws_api_events_vpc_core                 | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_vpc_core                 | 
| turbot_aws_api_events_cloudtrail               | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_cloudtrail               | 
| turbot_aws_api_events_ssm                      | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_ssm                      | 
| turbot_aws_api_events_kms                      | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_kms                      | 
| turbot_aws_api_events_billingconsole           | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_billingconsole           | 
| turbot_aws_api_events_ecr                      | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_ecr                      | 
| turbot_aws_api_events_lambda                   | arn:aws:events:us-east-2:986325076436:rule/turbot_aws_api_events_lambda                   | 

---------+--------------+----------------+
 state   | created_by   | event_bus_name |
---------+--------------+----------------+
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |
 ENABLED | 986325076436 | default        |


select [...]

2021-03-18 07:26 UTC, Subhajit97 approved these changes
LGTM

2021-03-18 14:28 UTC, cbruno10 commented on aws/plugin.go
> +			"aws_eventbridge_rule":                   tableAwsEventBridge(ctx),
```suggestion
			"aws_eventbridge_rule":                   tableAwsEventBridgeRule(ctx),
```

2021-03-18 14:29 UTC, cbruno10 commented on aws/table_aws_eventbridge_rule.go
> +func tableAwsEventBridge(_ context.Context) *plugin.Table {
```suggestion
func tableAwsEventBridgeRule(_ context.Context) *plugin.Table {
```

2021-03-18 14:31 UTC, cbruno10 commented on docs/tables/aws_eventbridge_rule.md
> +### EventBridge rule basic info
```suggestion
### Basic info
```

2021-03-18 14:31 UTC, cbruno10 commented on docs/tables/aws_eventbridge_rule.md
> +### List of rules which are not enabled
```suggestion
### List disabled rules
```

2021-03-18 14:32 UTC, cbruno10 commented on docs/tables/aws_eventbridge_rule.md
> +### List of targets and IAM roles associated with the rule
```suggestion
### Get the targets and IAM role associated with each rule
```

2021-03-18 14:32 UTC, cbruno10 commented on docs/tables/aws_eventbridge_rule.md
> +### List of rules which are not associated with any iam role
What's the impact of a rule not being associated with an IAM role? Does the rule not work then?

2021-03-18 15:07 UTC, cbruno10 approved these changes

2021-03-18 15:08 UTC, merged