Add table_aws_ecs_cluster. Closes #136
turbot/steampipe-plugin-aws pull request #140
Opened 2021-03-10 06:13 UTC by khushboo9024

2021-03-10 13:27 UTC, Subhajit97 commented on aws/table_aws_ecs_cluster.go
> +				Transform:   transform.FromField("ClusterName"),
```suggestion
```

2021-03-10 13:32 UTC, Subhajit97 commented on aws/table_aws_ecs_cluster.go
> +			{
Don't need to add `transform.FromField()` if the camelCase value of column name is same as SDK property.

2021-03-10 13:41 UTC, Subhajit97 commented on aws/table_aws_ecs_cluster.go
> +
Return `nil`, if the `ecsClusterTags.Tags` return nil
```suggestion

if ecsClusterTags.Tags == nil {
  return nil, nil
}

```

2021-03-10 13:58 UTC, Subhajit97 commented on docs/tables/aws_ecs_cluster.md
> +### List resources attached to ecs clusters
```suggestion
### List of resources attached with clusters
```

2021-03-10 14:01 UTC, Subhajit97 commented on docs/tables/aws_ecs_cluster.md
> +  aws_ecs_cluster;
Can we add some specific details for attachements (attachment_type, attachment_status, attachement_id)?

2021-03-10 14:01 UTC, Subhajit97 commented on docs/tables/aws_ecs_cluster.md
> +  aws_new.aws_ecs_cluster,
```suggestion
  aws_ecs_cluster,
```

2021-03-10 14:02 UTC, Subhajit97 commented on aws-test/tests/aws_ecs_cluster/variables.tf
> +# proper ordering of the setup of policies etc after the resource exists in Turbot.
```suggestion
```

2021-03-10 14:05 UTC, Subhajit97 requested changes
Make suggested changes, and add the tests logs

2021-03-10 14:12 UTC, Subhajit97 commented on aws/table_aws_ecs_cluster.go
> +			plugin.Logger(ctx).Trace("clusterArnclusterArnclusterArn", "clusterArn", results)
```suggestion
```

2021-03-18 14:14 UTC, Subhajit97 commented on aws/table_aws_ecs_cluster.go
> +				Transform:   transform.FromField("Statistics"),
```suggestion
```

2021-03-23 06:45 UTC, Subhajit97 submitted a review, later dismissed
LGTM

2021-03-24 20:56 UTC, cbruno10 approved these changes

2021-03-24 20:56 UTC, merged