fix: fix invalid pointer usage when your ecr image doesn't have any finding
turbot/steampipe-plugin-aws pull request #1429
Opened 2022-11-25 16:03 UTC by aminvielledebatAtBedrock

# Description

When you query a non existing aws image, or when there is still no finding, aws api returns an nil `output.ImageScanFindings.Findings` object.

This results in a `[HV000] ERROR: rpc error: code = Internal desc = hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference` error.

This PR fixes this issue.

2022-11-25 16:04 UTC, aminvielledebatAtBedrock commented
ping @cbruno10 if you have 5 minutes to review this one

2022-11-25 17:42 UTC, misraved commented
Hello @aminvielledebatAtBedrock, thanks for raising the PR 👍.

Could you please share the query that you were trying to run, for which you got the error?

I tried to run a simple query from the docs - 
```
select
  repository_name,
  image_tag,
  name,
  severity,
  description,
  attributes,
  uri,
  image_scan_status,
  image_scan_completed_at,
  vulnerability_source_updated_at
from
  aws_ecr_image_scan_finding
where
  repository_name = 'my-repo'
  and image_tag = 'my-image-tag'
```

Output:
```
+-----------------+-----------+------+----------+-------------+------------+-----+-------------------+-------------------------+---------------------------------+
| repository_name | image_tag | name | severity | description | attributes | uri | image_scan_status | image_scan_completed_at | vulnerability_source_updated_at |
+-----------------+-----------+------+----------+-------------+------------+-----+-------------------+-------------------------+---------------------------------+
+-----------------+-----------+------+----------+-------------+------------+-----+-------------------+-------------------------+---------------------------------+
```

Ideally, I should have gotten `[HV000] ERROR: rpc error: code = Internal desc = hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference error` error. 

Please let me know in case I missed something. Thanks 👍 .

2022-11-25 20:23 UTC, aminvielledebatAtBedrock commented
Hi @misraved !

Sure ! But my querie runs with my kubernetes cluster :cry: 
My goal is to list all my CVEs in running containers in my production clusters.

See bellow : 

``` sql 
drop table if exists aws_cache.aws_ecr_image_finding;
create table aws_cache.aws_ecr_image_finding as
select
  kube_container_image.image
 ,kube_container_image.repository_name
 ,kube_container_image.image_tag
 ,kube_container_image.context_name
 ,kube_container_image.project
 ,kube_container_image.team
 ,kube_container_image.customer
 ,kube_container_image.tenant
 ,findings.name as cve_name
 ,findings.severity as cve_severity
 ,findings.description as cve_description
from(
    select distinct
      image
      ,repository_name
      ,coalesce(image_tag, 'latest') as image_tag
      ,context_name
      ,lower(project) as project
      ,lower(team) as team
      ,lower(tenant) as tenant
      ,lower(customer) as customer
    from (
      select
        distinct
          jsonb_array_elements(p.init_containers)->>'image' as image
               ,(regexp_match(jsonb_array_elements(p.init_containers)->>'image','(?:[a-zA-Z0-9\-_\.]*\/)?([a-zA-Z0-9\/\-_\.]*)(?::?(.*))'))[1] as repository_name
               ,nullif((regexp_match(jsonb_array_elements(p.init_containers)->>'image','(?:[a-zA-Z0-9\-_\.]*\/)?([a-zA-Z0-9\/\-_\.]*)(?::?(.*))'))[2], '') as image_tag
               ,p.context_name
               ,coalesce(p.tags->>'project', p.tags->>'Project') as project
               ,coalesce(p.tags->>'team', p.tags->>'Team') as team
               ,coalesce(p.tags->>'tenant', p.tags->>'Tenant') as tenant
               ,coalesce(p.tags->>'customer', p.tags->>'Customer') as customer
      from kube_all.kubernetes_pod p
      where context_name ~* '.*prod.*'

      union

      select
        distinct
          jsonb_array_elements(p.containers)->>'image' as image
               ,(regexp_match(jsonb_array_elements(p.containers)->>'image','(?:[a-zA-Z0-9\-_\.]*\/)?([a-zA-Z0-9\/\-_\.]*)(?::?(.*))'))[1] as repository_name
               ,nullif((regexp_match(jsonb_array_elements(p.containers)->>'image','(?:[a-zA-Z0-9\-_\.]*\/)?([a-zA-Z0-9\/\-_\.]*)(?::?(.*))'))[2], '') as image_tag
               ,p.context_name
               ,coalesce(p.tags->>'project', p.tags->>'Project') as project
               ,coalesce(p.tags->>'team', p.tags->>'Team') as team
               ,coalesce(p.tags->>'tenant', p.tags->>'Tenant') as tenant
               ,coalesce(p.tags->>'customer', p.tags->>'Customer') as customer
      from kube_all.kubernetes_pod p
      where context_name ~* '.*prod.*'
    ) kube_container_image
) kube_container_image
left outer join services.aws_ecr_image_scan_finding findings
on kube_container_image.repository_name = findings.repository_name and kube_container_image.image_tag = findings.image_tag
;
```

2022-11-28 18:14 UTC, misraved commented
Thanks for the details @aminvielledebatAtBedrock 👍, very helpful indeed. The solution looks reasonable to me, however, we will try to replicate the error first, before merging it in 👍 .

2022-12-06 08:17 UTC, bigdatasourav commented
Hey @aminvielledebatAtBedrock, we were able to reproduce the error. When the scan is in progress, and if you try to query the findings then, the below error comes up -
```
> select * from aws_ecr_image_scan_finding where repository_name = 'test' and image_tag = '1.2'

Error: rpc error: code = Internal desc = hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
```

Could you please add a comment like below in your changes -
```
// If the scan is in progress, ImageScanFindings will be nil, and we will get an error -
// hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference
if output.ImageScanFindings == nil || output.ImageScanFindings.Findings == nil {
			return nil, nil
		}
```

2022-12-06 16:53 UTC, cbruno10 commented
@aminvielledebatAtBedrock @bigdatasourav Do we need a check if both `output.ImageScanFindings` and `output.ImageScanFindings.Findings` are `nil`? If so, in which cases do we get a `nil` for each?

From what it seems like in previous comments, does `output.ImageScanFindings` come back as `nil` when a scan is in progress, and `output.ImageScanFindings.Findings` comes back as `nil` when querying an AWS image that doesn't exist or when there are no findings?

2022-12-14 05:43 UTC, bigdatasourav commented
@cbruno10 we do not need to check both, `output.ImageScanFindings` will be enough, so the below will work fine.
```
// If the scan is in progress, ImageScanFindings will be nil, and we will get an error -
// hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference
if output.ImageScanFindings == nil {
			return nil, nil
		}
```

2022-12-20 05:13 UTC, cbruno10 requested changes
@aminvielledebatAtBedrock Please see suggested code and let me know your thoughts!

2022-12-20 05:13 UTC, cbruno10 commented on aws/table_aws_ecr_image_scan_finding.go
> +		}
```suggestion
		// If the scan is in progress and no findings are available yet, ImageScanFindings is nil
		if output.ImageScanFindings == nil {
			return nil, nil
		}
```
@bigdatasourav @aminvielledebatAtBedrock If we only need to check the first property, `ImageScanFindings`, maybe we can use the code and comment above

2023-05-10 01:50 UTC, merged