Add table aws_cloudtrail_event_data_store closes #1423
turbot/steampipe-plugin-aws pull request #1433
Opened 2022-11-28 11:18 UTC by ParthaI

# Integration test logs
<details>
  <summary>Logs</summary>

```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_cloudtrail_event_data_store []

PRETEST: tests/aws_cloudtrail_event_data_store

TEST: tests/aws_cloudtrail_event_data_store
Running terraform
data.aws_region.alternate: Reading...
data.aws_region.alternate: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Reading...
data.aws_partition.current: Reading...
data.aws_region.primary: Reading...
data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_region.primary: Read complete after 0s [id=us-east-1]
data.aws_caller_identity.current: Read complete after 2s [id=632902152528]
data.null_data_source.resource: Reading...
data.null_data_source.resource: Read complete after 0s [id=static]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_cloudtrail_event_data_store.named_test_resource will be created
  + resource "aws_cloudtrail_event_data_store" "named_test_resource" {
      + arn                            = (known after apply)
      + id                             = (known after apply)
      + multi_region_enabled           = true
      + name                           = "turbottest23807"
      + organization_enabled           = false
      + retention_period               = 2555
      + tags_all                       = (known after apply)
      + termination_protection_enabled = true

      + advanced_event_selector {
          + name = "Log all DynamoDB PutEvent actions for a specific DynamoDB table"

          + field_selector {
              + ends_with       = (known after apply)
              + equals          = [
                  + "AWS::DynamoDB::Table",
                ]
              + field           = "resources.type"
              + not_ends_with   = (known after apply)
              + not_equals      = (known after apply)
              + not_starts_with = (known after apply)
              + starts_with     = (known after apply)
            }
          + field_selector {
              + ends_with       = (known after apply)
              + equals          = [
                  + "Data",
                ]
              + field           = "eventCategory"
              + not_ends_with   = (known after apply)
              + not_equals      = (known after apply)
              + not_starts_with = (known after apply)
              + starts_with     = (known after apply)
            }
          + field_selector {
              + ends_with       = (known after apply)
              + equals          = [
                  + "PutItem",
                ]
              + field           = "eventName"
              + not_ends_with   = (known after apply)
              + not_equals      = (known after apply)
              + not_starts_with = (known after apply)
              + starts_with     = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + account_id    = "632902152528"
  + aws_partition = "aws"
  + region_name   = "us-east-1"
  + resource_aka  = (known after apply)
  + resource_name = "turbottest23807"
aws_cloudtrail_event_data_store.named_test_resource: Creating...
aws_cloudtrail_event_data_store.named_test_resource: Creation complete after 5s [id=arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/4b19aea8-fc7b-4f50-9863-bee5a24d0d88]

Warning: Deprecated

  with data.null_data_source.resource,
  on variables.tf line 44, in data "null_data_source" "resource":
  44: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values
to re-use elsewhere in configuration, the same can now be achieved using
locals

(and one more similar warning elsewhere)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = "632902152528"
aws_partition = "aws"
region_name = "us-east-1"
resource_aka = "arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/4b19aea8-fc7b-4f50-9863-bee5a24d0d88"
resource_name = "turbottest23807"

Running SQL query: test-hydrate-query.sql
[
  {
    "advanced_event_selectors": [
      {
        "FieldSelectors": [
          {
            "EndsWith": null,
            "Equals": [
              "Data"
            ],
            "Field": "eventCategory",
            "NotEndsWith": null,
            "NotEquals": null,
            "NotStartsWith": null,
            "StartsWith": null
          },
          {
            "EndsWith": null,
            "Equals": [
              "PutItem"
            ],
            "Field": "eventName",
            "NotEndsWith": null,
            "NotEquals": null,
            "NotStartsWith": null,
            "StartsWith": null
          },
          {
            "EndsWith": null,
            "Equals": [
              "AWS::DynamoDB::Table"
            ],
            "Field": "resources.type",
            "NotEndsWith": null,
            "NotEquals": null,
            "NotStartsWith": null,
            "StartsWith": null
          }
        ],
        "Name": "Log all DynamoDB PutEvent actions for a specific DynamoDB table"
      }
    ],
    "name": "turbottest23807"
  }
]
✔ PASSED

Running SQL query: test-list-call-query.sql
[
  {
    "event_data_store_arn": "arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/4b19aea8-fc7b-4f50-9863-bee5a24d0d88",
    "name": "turbottest23807"
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/4b19aea8-fc7b-4f50-9863-bee5a24d0d88"
    ],
    "title": "turbottest23807"
  }
]
✔ PASSED

POSTTEST: tests/aws_cloudtrail_event_data_store

TEARDOWN: tests/aws_cloudtrail_event_data_store

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select
  name,
  event_data_store_arn,
  status,
  created_timestamp,
  multi_region_enabled,
  organization_enabled,
  termination_protection_enabled
from
  aws_cloudtrail_event_data_store;
+-----------------------+-----------------------------------------------------------------------------------------------+---------+---------------------------+----------------------+----------------------+--------------------------------+
| name                  | event_data_store_arn                                                                          | status  | created_timestamp         | multi_region_enabled | organization_enabled | termination_protection_enabled |
+-----------------------+-----------------------------------------------------------------------------------------------+---------+---------------------------+----------------------+----------------------+--------------------------------+
| turbottest23807       | arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/4b19aea8-fc7b-4f50-9863-bee5a24d0d88 | ENABLED | 2022-11-28T16:38:35+05:30 | true                 | false                | true                           |
| turbottest51242       | arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/03543d1c-054c-4016-95ae-1f8faef24485 | ENABLED | 2022-11-28T16:27:47+05:30 | true                 | false                | true                           |
| turbottest37839       | arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/3cde6043-35f1-4487-8f12-7dd097322bc6 | ENABLED | 2022-11-28T16:34:09+05:30 | true                 | false                | true                           |
| test-event-data-store | arn:aws:cloudtrail:us-east-1:632902152528:eventdatastore/5c5ae735-06f1-40b3-84d5-d9838162b1d1 | ENABLED | 2022-11-24T17:34:55+05:30 | true                 | false                | true                           |
| tur [...]

2022-11-28 11:41 UTC, misraved reviewed
Please take a look at the review comments. Thanks!!!

2022-11-28 11:41 UTC, misraved commented on aws/plugin.go
> +			"aws_cloudtrail_event_data_store":                              tableAwsCloudtrailEventDataStore(ctx),
Could you please sort this list of tables?

2022-11-28 11:41 UTC, misraved commented on aws/table_aws_cloudtrail_trail_event_data_store.go
> +			Hydrate: getCloudTrailEventDataStore,
```suggestion
			KeyColumns: plugin.AnyColumn([]string{"event_data_store_arn"}),
			Hydrate:        getCloudTrailEventDataStore,
```

2022-11-28 11:41 UTC, misraved commented on aws/table_aws_cloudtrail_trail_event_data_store.go
> +				Description: "This field is being deprecated. The retention period, in days.",
If this field is being deprecated, does it make sense to keep it?

2022-12-02 04:32 UTC, cbruno10 requested changes
@ParthaI Please see review comments, thanks!

2022-12-02 04:32 UTC, cbruno10 commented on aws/table_aws_cloudtrail_trail_event_data_store.go
> +package aws
The filename looks incorrect, I think it should be `aws/table_aws_cloudtrail_event_data_store.go`

2022-12-02 04:32 UTC, cbruno10 commented on aws/table_aws_cloudtrail_trail_event_data_store.go
> +func tableAwsCloudtrailEventDataStore(_ context.Context) *plugin.Table {
```suggestion
func tableAwsCloudTrailEventDataStore(_ context.Context) *plugin.Table {
```

The service name is `CloudTrail`, so `Trail` should be capitalized in the function name.

2022-12-02 04:32 UTC, cbruno10 commented on docs/tables/aws_cloudtrail_event_data_store.md
> +AWS CloudTrail Event data store stores data for up to seven years, or 2557 days. By default, event data is retained for 2557 days, and termination protection is enabled for an event data store.
```suggestion
AWS CloudTrail event data stores retain data for up to seven years, or 2557 days. By default, event data is retained for 2557 days, and termination protection is enabled for an event data store.
```

2022-12-02 04:32 UTC, cbruno10 commented on docs/tables/aws_cloudtrail_event_data_store.md
> +### List cloudtrail event stores which are not enabled
```suggestion
### List event data stores which are not enabled
```

We don't need the service name (unless it's to disambiguate between resource names together), and we should include the full resource name

2022-12-02 04:32 UTC, cbruno10 commented on docs/tables/aws_cloudtrail_event_data_store.md
> +### List cloudtrail event stores with termination protection disabled
```suggestion
### List event data stores with termination protection disabled
```

2022-12-06 04:02 UTC, cbruno10 requested changes
@ParthaI Please see review comments, thanks!

2022-12-06 04:02 UTC, cbruno10 commented on aws/table_aws_cloudtrail_event_data_store.go
> +				Name:        "event_data_store_arn",
```suggestion
				Name:        "arn",
```

I think we usually normalize the `arn` columns to just be `arn` (so it's easy to find and so our mod controls work well with them).

2022-12-06 04:02 UTC, cbruno10 commented on aws/table_aws_cloudtrail_event_data_store.go
> +			if limit < 1 {
I think in the later Steampipe CLI versions if someone runs a query with `limit 0`, the hydrate functions aren't entered, so we may not need this check, so we could simplify to:
```
		if limit < maxLimit {
			maxLimit = limit
		}
```

Can you please test and confirm this?

2022-12-06 14:22 UTC, cbruno10 approved these changes

2022-12-06 14:23 UTC, merged