Add table aws_emr_cluster. Closes #141
turbot/steampipe-plugin-aws pull request #152
Opened 2021-03-11 13:30 UTC by khushboo9024

2021-03-15 11:03 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +			},
Use `name` as first column

2021-03-15 11:03 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +				Name:        "Normalized_instance_hours",
```suggestion
				Name:        "normalized_instance_hours",
```

2021-03-15 11:04 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +				Name:        "Normalized_instance_hours",
```suggestion
				Name:        "normalized_instance_hours",
```

2021-03-15 11:04 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +				Description: "The friendly name to identify the DB Cluster.",
Update the description

2021-03-15 11:05 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +				Description: "A list of tags associated with a cluster..",
```suggestion
				Description: "A list of tags associated with a cluster.",
```

2021-03-15 11:24 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +	// Mapping the resource tags inside turbotTags
```suggestion
	
	// Mapping the resource tags inside turbotTags
```

2021-03-15 11:26 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +				Description: "The size, in GiB, of the Amazon EBS root device volume of the Linux AMI that is used for each EC2 instance. Available in Amazon EMR version 4.x and later.",
```suggestion
				Description: "The size of the Amazon EBS root device volume of the Linux AMI that is used for each EC2 instance, in GiB. Available in Amazon EMR version 4.x and later.",
```

2021-03-15 11:30 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +
Please follow the below order defining the schema
```
1. Add 4-5 columns at first which are important (i.e. name, arn, state etc.)
2. Add rest of the columns in alphabetical order,
3. Add all the JSON type columns at the end
4. For the standard column, follow this order (title, tags, akas)
```

2021-03-15 11:31 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +	}
Is this check required?
Doesn't the API return any `Not Found` errors?

2021-03-15 11:32 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  name               = "test_iam_emr_service_role"
```suggestion
  name               = var.resource_name
```

2021-03-15 11:33 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  name = "test_iam_emr_service_policy"
```suggestion
  name = var.resource_name
```

2021-03-15 11:34 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +            "sqs:ReceiveMessage"
Try to create with 2-3 read-only permissions

2021-03-15 11:35 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  name = "test_iam_emr_profile_role"
```suggestion
  name = var.resource_name
```

2021-03-15 11:35 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  name  = "emr_profile_new008"
```suggestion
  name  = var.resource_name
```

2021-03-15 11:35 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  name = "iam_emr_profile_policy"
```suggestion
  name = var.resource_name
```

2021-03-15 11:35 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  role = "${aws_iam_role.iam_emr_profile_role.name}"
```suggestion
  role = aws_iam_role.iam_emr_profile_role.name
```

2021-03-15 11:36 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  role = "${aws_iam_role.iam_emr_profile_role.id}"
```suggestion
  role = "aws_iam_role.iam_emr_profile_role.id"
```

2021-03-15 11:36 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  vpc_id                 = "${aws_vpc.my_vpc.id}"
```suggestion
  vpc_id                 = aws_vpc.my_vpc.id
```

2021-03-15 11:37 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +}
```suggestion
resource "aws_subnet" "my_subnet" {
  vpc_id     = aws_vpc.my_vpc.id
  cidr_block = "168.31.0.0/20"
}
resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.my_vpc.id
}
resource "aws_route_table" "test_route_table" {
  vpc_id = aws_vpc.my_vpc.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.gw.id
  }
}
resource "aws_main_route_table_association" "test_association" {
  vpc_id         = aws_vpc.my_vpc.id
  route_table_id = aws_route_table.test_route_table.id
}
```

2021-03-15 11:37 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +    instance_profile                  = "${aws_iam_instance_profile.emr_profile.arn}"
```suggestion
    subnet_id                         = aws_subnet.my_subnet.id
    emr_managed_master_security_group = aws_security_group.emr_master.id
    emr_managed_slave_security_group  = aws_security_group.emr_master.id
    instance_profile                  = aws_iam_instance_profile.emr_profile.arn
```

2021-03-15 11:38 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +  service_role = "${aws_iam_role.iam_emr_service_role.arn}"
```suggestion
  service_role = aws_iam_role.iam_emr_service_role.arn
```

2021-03-15 11:42 UTC, Subhajit97 commented on aws-test/tests/aws_emr_cluster/variables.tf
> +    instance_type = "m4.xlarge"
Can we create resource of lower configuration?
```suggestion
    instance_type = "m1.small"
```

2021-03-15 11:50 UTC, Subhajit97 requested changes
Make suggested changes

2021-03-18 14:40 UTC, Subhajit97 commented on aws/table_aws_emr_cluster.go
> +	plugin.Logger(ctx).Trace("emrClusterTagToTurbotTags")
```suggestion
	plugin.Logger(ctx).Trace("getEmrClusterTurbotTags")
```

2021-03-18 14:42 UTC, Subhajit97 commented on docs/tables/aws_emr_cluster.md
> +  status ->>  'State' as state,
```suggestion
  status ->> 'State' as state,
```

2021-03-18 14:44 UTC, Subhajit97 commented on docs/tables/aws_emr_cluster.md
> +  status ->  'StateChangeReason' ->> 'Message'  as  state_change_reason
```suggestion
  status ->> 'State' as state,
  status ->> 'StateChangeReason' ->> 'Message'  as  state_change_reason
```

2021-03-18 14:44 UTC, Subhajit97 commented on docs/tables/aws_emr_cluster.md
> +  status ->>  'State' = 'TERMINATED_WITH_ERRORS';
```suggestion
  status ->> 'State' = 'TERMINATED_WITH_ERRORS';
```

2021-03-19 12:28 UTC, Subhajit97 approved these changes
LGTM

2021-03-23 05:55 UTC, Subhajit97 commented on aws/plugin.go
> +			"aws_emr_cluster":                        tableAwsEmrCluster(ctx),
Sort the list

2021-03-23 06:20 UTC, Subhajit97 submitted a review, later dismissed
LGTM

2021-03-25 09:37 UTC, Subhajit97 approved these changes
LGTM

2021-03-25 10:46 UTC, rajmohanty17 commented on docs/tables/aws_emr_cluster.md
> +```
Add one more example to check of EMR Cluster is Encrypted or not

2021-03-25 10:49 UTC, rajmohanty17 commented on docs/tables/aws_emr_cluster.md
> +```
@khushboo9024 pls check EMR Cluster Logging or not or by default.

2021-03-25 10:50 UTC, rajmohanty17 requested changes
Added comment to check encryption status.

2021-03-25 12:28 UTC, rajmohanty17 approved these changes
LGTM

2021-03-25 14:28 UTC, cbruno10 approved these changes

2021-03-25 14:29 UTC, merged