Add table aws_emr_cluster_block_public_access
turbot/steampipe-plugin-aws pull request #1602
Opened 2023-02-21 12:24 UTC by Priyanka-Chatterjee-2000

# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
Add example SQL query results here (please include the input queries as well)
```
</details>

2023-02-23 11:43 UTC, ParthaI reviewed
@Priyanka-Chatterjee-2000 please manage the table column ordering.
- We don't have any standard column for it?

2023-02-23 11:43 UTC, ParthaI commented on aws/table_aws_emr_block_public_access_configuration.go
> +		List: &plugin.ListConfig{
We don't have any get call for it?

2023-02-23 12:13 UTC, Priyanka-Chatterjee-2000 commented on aws/table_aws_emr_block_public_access_configuration.go
> +		List: &plugin.ListConfig{
No

2023-02-23 14:58 UTC, ParthaI approved these changes

2023-02-23 16:01 UTC, cbruno10 requested changes
@Priyanka-Chatterjee-2000 Please see review comments, thanks!

2023-02-24 07:33 UTC, Priyanka-Chatterjee-2000 commented on docs/tables/aws_emr_block_public_access_configuration.md
> +### List clusters with Block Public Access enabled
Right it is not set on clusters individually so changing the description to `List Block Public Access enabled settings for EMR` is this good?

2023-02-24 08:24 UTC, Priyanka-Chatterjee-2000 commented on docs/tables/aws_emr_block_public_access_configuration.md
> +### List Block Public Access with Permitted Public Security Group Rule Max and Min Ranges
In Permitted Public Security Group Rule json array  we get max and min port ranges. Port number can be set anything based  on the way the user wish to access the instance.Here port 22, is used for SSH access to the cluster EC2 instances. If the inbound traffic security rules are set with IPv4 0.0.0.0/0 from port 22 then these ports are publicly accessible and any body will be able to connect to cluster EC2 instances through ssh but here we only get the data of port numbers and nothing else. As there are less number of columns and I was asked to add more example queries I added this. Shall I remove this?

2023-02-24 08:58 UTC, Priyanka-Chatterjee-2000 commented on docs/tables/aws_emr_block_public_access_configuration.md
> +## Examples
Added an example query with `configuration details`

2023-03-03 16:15 UTC, misraved approved these changes

2023-03-03 16:16 UTC, merged