Add table aws_glacier_vault closes #149
turbot/steampipe-plugin-aws pull request #165
Opened 2021-03-12 13:10 UTC by Paulami30

No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_glacier_vault []

PRETEST: tests/aws_glacier_vault

TEST: tests/aws_glacier_vault
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_glacier_vault.named_test_resource: Creating...
aws_glacier_vault.named_test_resource: Still creating... [10s elapsed]
aws_glacier_vault.named_test_resource: Creation complete after 12s [id=turbottest96112]
data.template_file.resource_aka: Refreshing state...

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = arn:aws:glacier:us-east-1:352685002396:vaults/turbottest96112
resource_id = turbottest96112
resource_name = turbottest96112

Running SQL query: test-get-query.sql
[
  {
    "tags_src": {
      "name": "turbottest96112"
    },
    "title": "turbottest96112",
    "vault_name": "turbottest96112"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest96112"
    ],
    "policy": {
      "Statement": [
        {
          "Action": [
            "glacier:InitiateJob",
            "glacier:GetJobOutput"
          ],
          "Effect": "Allow",
          "Principal": "*",
          "Resource": "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest96112",
          "Sid": "__default_policy_ID"
        }
      ],
      "Version": "2012-10-17"
    },
    "tags": {
      "name": "turbottest96112"
    },
    "title": "turbottest96112",
    "vault_name": "turbottest96112"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest96112"
    ],
    "tags": {
      "name": "turbottest96112"
    },
    "title": "turbottest96112",
    "vault_name": "turbottest96112"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_glacier_vault

TEARDOWN: tests/aws_glacier_vault

SUMMARY:

1/1 passed.

2021-03-15 12:02 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +			ShouldIgnoreError: isNotFoundError([]string{"ResourceNotFoundException"}),
Handle below error
```
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DescribeVaultInput.VaultName.
```

2021-03-15 12:03 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +				Description: "A list of tags associated with the cluster.",
```suggestion
				Description: "A list of tags associated with the vault.",
```

2021-03-15 12:04 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +	accountID := commonColumnData.AccountId
Can't we use the `VaultARN` to get the accountID?

2021-03-15 12:05 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +	accountID := commonColumnData.AccountId
Can't we use the `VaultARN` to get the accountID?

2021-03-15 12:06 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +				Transform:   transform.FromField("Tags"),
```suggestion
```

2021-03-15 12:09 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +
```suggestion
```

2021-03-15 12:17 UTC, Subhajit97 requested changes
Make suggested changes

2021-03-15 15:22 UTC, Paulami30 commented
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_glacier_vault []

PRETEST: tests/aws_glacier_vault

TEST: tests/aws_glacier_vault
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_glacier_vault.named_test_resource: Creating...
aws_glacier_vault.named_test_resource: Still creating... [10s elapsed]
aws_glacier_vault.named_test_resource: Creation complete after 10s [id=turbottest99510]
data.template_file.resource_aka: Refreshing state...

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = arn:aws:glacier:us-east-1:352685002396:vaults/turbottest99510
resource_id = turbottest99510
resource_name = turbottest99510

Running SQL query: test-get-query.sql
[
  {
    "tags_src": {
      "name": "turbottest99510"
    },
    "title": "turbottest99510",
    "vault_name": "turbottest99510"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest99510"
    ],
    "policy": {
      "Statement": [
        {
          "Action": [
            "glacier:InitiateJob",
            "glacier:GetJobOutput"
          ],
          "Effect": "Allow",
          "Principal": "*",
          "Resource": "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest99510",
          "Sid": "__default_policy_ID"
        }
      ],
      "Version": "2012-10-17"
    },
    "tags": {
      "name": "turbottest99510"
    },
    "title": "turbottest99510",
    "vault_name": "turbottest99510"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:glacier:us-east-1:352685002396:vaults/turbottest99510"
    ],
    "tags": {
      "name": "turbottest99510"
    },
    "title": "turbottest99510",
    "vault_name": "turbottest99510"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_glacier_vault

TEARDOWN: tests/aws_glacier_vault

SUMMARY:

1/1 passed.

2021-03-16 12:25 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +	accountID := splitID[4]
```suggestion
	accountID := strings.Split(*vaultName.VaultARN, ":")[4]
```

2021-03-16 12:26 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +	vaultName := h.Item.(*glacier.DescribeVaultOutput)
```suggestion
	data := h.Item.(*glacier.DescribeVaultOutput)
```

2021-03-16 12:27 UTC, Subhajit97 commented on aws/table_aws_glacier_vault.go
> +	accountID := splitID[4]
```suggestion
	data := h.Item.(*glacier.DescribeVaultOutput)
	accountID := strings.Split(*data.VaultARN, ":")[4]
```

2021-03-17 10:42 UTC, Subhajit97 submitted a review, later dismissed

2021-03-29 09:01 UTC, Subhajit97 approved these changes
LGTM

2021-03-30 06:49 UTC, rajmohanty17 requested changes
All example looks good, but if we can add the archival days or archival policy of the vault will be good, this will help to list the buckets nearing the last date of deletion kind of.

2021-03-30 06:49 UTC, rajmohanty17 commented
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Glacier.html#describeVault-property

2021-03-31 08:51 UTC, rajmohanty17 approved these changes
LGTM

2021-04-01 14:33 UTC, cbruno10 approved these changes

2021-04-01 14:34 UTC, merged