Add table aws_ec2_client_vpn_endpoint closes #1717
turbot/steampipe-plugin-aws pull request #1722
Opened 2023-05-04 06:07 UTC by misraved

# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
Add example SQL query results here (please include the input queries as well)
```
</details>

2023-05-04 11:12 UTC, ParthaI requested changes
@misraved please take a look at the review comments. Thanks!

2023-05-04 11:12 UTC, ParthaI commented on aws/table_aws_ec2_client_vpn_endpoint.go
> +	return op.ClientVpnEndpoints, nil
```suggestion
	return op.ClientVpnEndpoints[0], nil
```

2023-05-15 11:46 UTC, misraved commented on aws/table_aws_ec2_client_vpn_endpoint.go
> +			}
@ParthaI the API docs mention that the minimum limit should be 5

2023-05-16 04:49 UTC, ParthaI reviewed
@misraved Please take a look at the review comments, Thanks!
Could you please re-order the columns?

- First 3-4 column would be the important column for the table like (name, id, arn, status...).
- Re-order the Non-JSON column alphabetically.
- Re-order the JSON column alphabetically.

2023-05-16 04:49 UTC, ParthaI commented on aws/table_aws_ec2_client_vpn_endpoint.go
> +				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"ValidationError", "InvalidQueryParameter", "InvalidParameterValue", "InvalidClientVpnEndpointId.NotFound"}),
Should we ignore `ValidationError`, `InvalidQueryParameter`, `InvalidParameterValue `?

2023-05-16 13:14 UTC, ParthaI approved these changes
LGTM

2023-05-16 14:12 UTC, merged