Add table aws_ecs_task_definition. Closes #171
turbot/steampipe-plugin-aws pull request #173
Opened 2021-03-15 12:17 UTC by khushboo9024

2021-03-17 13:11 UTC, Subhajit97 requested changes
Make suggested changes

2021-03-17 13:11 UTC, Subhajit97 commented on aws/table_aws_ecs_task_definition.go
> +				Description: "A list of tags associated with target group.",
```suggestion
				Description: "A list of tags associated with task.",
```

2021-03-17 13:11 UTC, Subhajit97 commented on aws/table_aws_ecs_task_definition.go
> +		result, err := svc.ListTaskDefinitions(params)
Can't we use `ListTaskDefinitionsPages` for pagination?
https://github.com/aws/aws-sdk-go/blob/67f532fc99ebc262a50fa05500b3462065b75569/service/ecs/api.go#L3317

2021-03-17 13:11 UTC, Subhajit97 commented on aws/table_aws_ecs_task_definition.go
> +	title := strings.Split(*arn, "/")[len(strings.Split(*arn, "/"))-1]
```suggestion
	splitArn := strings.Split(*arn, "/")
	title := splitArn[len(splitArn)-1]
```

2021-03-17 13:11 UTC, Subhajit97 commented on docs/tables/aws_ecs_task_definition.md
> +  jsonb_array_elements(container_definitions) as cd;
Do we need this?

2021-03-17 13:11 UTC, Subhajit97 commented on aws-test/tests/aws_ecs_task_definition/test-get-query.sql
> +select task_definition_arn, cpu, family, memory, status
Also validate `account_id`, `region` and `partition`.

2021-03-18 14:58 UTC, Subhajit97 approved these changes

2021-03-18 15:00 UTC, Subhajit97 commented on docs/tables/aws_ecs_task_definition.md
> +  where cd ->> 'Privileged' = 'true' ;
```suggestion
where 
  cd ->> 'Privileged' = 'true';
```

2021-03-18 15:02 UTC, Subhajit97 requested changes
@khushboo9024 There is a small change in docs. Please make the changes.

2021-03-23 06:12 UTC, Subhajit97 approved these changes

2021-03-25 11:20 UTC, Subhajit97 commented on aws/table_aws_ecs_task_definition.go
> +		// Get the resource tags
```suggestion
		if ecsTaskDefinition.Tags == nil {
		  return nil, nil
		}
		
		// Get the resource tags
```

2021-03-25 11:22 UTC, Subhajit97 requested changes
There is a minor change required. Please see the comment.

2021-03-25 11:40 UTC, Subhajit97 approved these changes
LGTM

2021-03-25 12:18 UTC, rajmohanty17 commented on docs/tables/aws_ecs_task_definition.md
> +### Basic info
Would recommend to add  network_mode to the query to check what's the  ECS task networking type.

2021-03-25 12:21 UTC, rajmohanty17 requested changes
Added to include meaningful col.

2021-03-25 14:17 UTC, rajmohanty17 approved these changes
LGTM

2021-03-29 17:31 UTC, merged