Add table aws_kinesis_video_stream. closes #175
turbot/steampipe-plugin-aws pull request #182
Opened 2021-03-16 11:20 UTC by sayan133

2021-03-19 12:15 UTC, Paulami30 commented on aws/service.go
> +		return nil, fmt.Errorf("region must be passed KinesisVideoService")
```suggestion
		return nil, fmt.Errorf("region must be passed Kinesis Video")
```

2021-03-19 12:18 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +			Hydrate:           describeStream,
```suggestion
			Hydrate:           getVideoStreams,
```

2021-03-19 12:18 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +			Hydrate: listVideoStreams,
```suggestion
			Hydrate: listKinesisVideoStreams,
```

2021-03-19 12:19 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +				Name:        "tags",
```suggestion
				Name:        "tags_src",
```

2021-03-19 12:21 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +				Hydrate:     getAwsKinesisVideoStreamTags,
```suggestion
				Hydrate:     listKinesisVideoStreamTags,
```

2021-03-19 12:25 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +func listVideoStreams(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listKinesisVideoStreams(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-03-19 12:32 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +func getAwsKinesisVideoStreamTags(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func listKinesisVideoStreamTags(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-19 12:33 UTC, Paulami30 commented on aws/table_aws_kinesis_video_stream.go
> +func describeStream(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getKinesisVideoStream(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-22 06:54 UTC, Subhajit97 commented on aws/table_aws_kinesis_video_stream.go
> +	logger.Trace("describeStream__", "params", params)
```suggestion
```

2021-03-22 06:54 UTC, Subhajit97 commented on aws/table_aws_kinesis_video_stream.go
> +
```suggestion
```

2021-03-22 06:56 UTC, Subhajit97 commented on aws/table_aws_kinesis_video_stream.go
> +	logger.Trace("listKinesisVideoStreamTags", "Tags", op)
```suggestion
```

2021-03-22 07:00 UTC, Subhajit97 commented on aws/table_aws_kinesis_video_stream.go
> +	streamName := *h.Item.(*kinesisvideo.StreamInfo).StreamName
```suggestion
	data := h.Item.(*kinesisvideo.StreamInfo)
```

2021-03-22 07:00 UTC, Subhajit97 commented on aws/table_aws_kinesis_video_stream.go
> +		StreamName: &streamName,
```suggestion
		StreamName: data.StreamName,
```

2021-03-22 07:07 UTC, Subhajit97 commented on docs/tables/aws_kinesis_video_stream.md
> +  split_part(kms_key_id, '/', 3) = 'kinesisvideo';
Can we add a new column to store kms_key_name? instead of split the ID here to check the key_name?
For example: `alias/aws/kinesisvideo` for default

2021-03-22 07:37 UTC, Subhajit97 requested changes
Make suggested changes, and also add the outputs of the queries added in docs.

2021-03-22 07:43 UTC, Subhajit97 commented on docs/tables/aws_kinesis_video_stream.md
> +  split_part(kms_key_id, '/', 3) = 'kinesisvideo';
```suggestion
  split_part(kms_key_id, ':', 6) = 'kinesisvideo';
```

2021-03-22 08:12 UTC, Subhajit97 submitted a review, later dismissed
LGTM

2021-03-25 05:56 UTC, Paulami30 submitted a review, later dismissed

2021-03-25 06:47 UTC, Subhajit97 approved these changes
LGTM

2021-03-25 07:49 UTC, rajmohanty17 commented on docs/tables/aws_kinesis_video_stream.md
> +### List video streams with data retention period < 7 days
### List video streams with data retention period < 7 days (Represented as hours in query).

2021-03-25 07:50 UTC, rajmohanty17 requested changes
Small change requested.

2021-03-25 11:10 UTC, rajmohanty17 approved these changes
LGTM

2021-03-25 14:18 UTC, cbruno10 approved these changes

2021-03-25 14:19 UTC, merged