#1872: Implementation of aws_lambda_function_event_source_mapping
turbot/steampipe-plugin-aws pull request #1874
Opened 2023-08-11 19:42 UTC by nickman

# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```sql
select
  event_source_arn,
  function_arn,
  function_name,
  last_processing_result,
  parallelization_factor,
  state,
  destination_config
from
  aws_lambda_function_event_source_mapping;
```
|event_source_arn|function_arn|function_name|last_processing_result|parallelization_factor|state|destination_config|
|----------------|------------|-------------|----------------------|----------------------|-----|------------------|
|arn:aws:kinesis:us-east-1:XXXXXXXXXXXXXX:stream/w8imy|arn:aws:lambda:us-east-1:XXXXXXXXXXXXXX:function:eventaudit|eventaudit|OK|9|Enabled|{"OnFailure": {"Destination": "arn:aws:sqs:us-east-1:XXXXXXXXXXXXXX:FailedAuditEvents"}, "OnSuccess": null}|
|arn:aws:kinesis:us-east-1:XXXXXXXXXXXXXX:stream/instruments|arn:aws:lambda:us-east-1:XXXXXXXXXXXXXX:function:eventaudit|eventaudit|OK|10|Enabled|{"OnFailure": {"Destination": null}, "OnSuccess": null}|
|arn:aws:kinesis:us-east-1:XXXXXXXXXXXXXX:stream/partnerProfiles|arn:aws:lambda:us-east-1:XXXXXXXXXXXXXX:function:eventaudit|eventaudit|OK|10|Enabled|{"OnFailure": {"Destination": null}, "OnSuccess": null}|

</details>

2023-08-15 17:08 UTC, cbruno10 requested changes
@nickman Thanks for opening this PR!

I've left some review comments and questions, can you please have a look and let us know if you have any questions?

2023-08-15 17:08 UTC, cbruno10 commented on aws/table_aws_lambda_function_event_source_mapping.go
> +// Commented these, and the using columns because the implementation is brittle or non-useful in some cases.
If we don't use these functions, can we remove them and add examples to extract the info, e.g., using the Postgres `split_part()` function?

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +### List of lambda functions which disabled
Is this showing functions that are disabled or disabled event source mappings?

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +### Count of lambda function event source mappings by runtime engines of the function
This example seems more relevant to the `aws_lambda_function` table, are there any other examples we can add specific to event source mappings? For instance, showing the data in `source_access_configurations`? Or showing  event sources with a particular filter criteria (from `filter_criteria`)?

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +  runtime;
```suggestion
select
  runtime,
  count(*)
from
  aws_lambda_function_event_source_mapping, 
  aws_lambda_function
where
  arn = function_arn
group by
  runtime;
```

Please format examples according to https://steampipe.io/docs/develop/table-docs-standards#example-query-guidelines

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +### List Kafka Bootstrap Servers from a self-managed Kafka cluster feeding events to a Lambda function
What does the output of this query look like?

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +AWS Lambda is a compute service that lets you run code without provisioning or managing servers.
```suggestion
```

I think it's ok if we just describe event source mappings in this table doc (else we'd be describing each service in each table doc)

2023-08-15 17:08 UTC, cbruno10 commented on docs/tables/aws_lambda_function_event_source_mapping.md
> +## Examples
Are there any other examples we can add that highlight which fields are relevant to specific resource types? For instance, looking at https://docs.aws.amazon.com/lambda/latest/dg/API_GetEventSourceMapping.html#API_GetEventSourceMapping_ResponseElements, a lot are only relevant to DynamoDB streams, so if there was an example only listing event source mappings using DDB streams and had DDB relevant columns in its `select` statement, that would be easy for users to run and know which columns are relevant.

2023-08-17 17:04 UTC, nickman commented on aws/plugin.go
> +			EV_SOURCE_MAPPING_TABLE_NAME:                                   tableAwsLambdaFunctionEventSourceMapping(ctx),
Hi @cbruno10
Thanks for the review.
Just to clarify... 
Should the base name be _just_ `aws_lambda_event_source_mapping`
or should I ditch the `lambda` part too... making it `aws_event_source_mapping` ?

2023-08-17 18:04 UTC, cbruno10 commented on aws/plugin.go
> +			EV_SOURCE_MAPPING_TABLE_NAME:                                   tableAwsLambdaFunctionEventSourceMapping(ctx),
@nickman `aws_lambda_event_source_mapping` would be good. We generally use the naming scheme `aws_<service>_<resource>` for table names (this is to help users find resources quickly and eliminate the possibility of conflicts, e.g., if two services have resources with the same name).

2023-10-25 10:59 UTC, merged