Add table_aws_cloudwatch_alarm. Closes #128
turbot/steampipe-plugin-aws pull request #197
Opened 2021-03-17 18:55 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```

SETUP: tests/aws_clouwatch_alarm []

PRETEST: tests/aws_clouwatch_alarm

TEST: tests/aws_clouwatch_alarm
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_cloudwatch_metric_alarm.named_test_resource: Creating...
aws_cloudwatch_metric_alarm.named_test_resource: Creation complete after 4s [id=turbottest74468]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = 013122550996
aws_partition = aws
region_name = us-east-1
resource_aka = arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468
resource_name = turbottest74468

Running SQL query: test-get-query.sql
[
  {
    "alarm_arn": "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468",
    "alarm_description": "turbottest74468",
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "metric_name": "CPUUtilization",
    "name": "turbottest74468"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468"
    ],
    "alarm_arn": "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468",
    "alarm_description": "turbottest74468",
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "metric_name": "CPUUtilization",
    "name": "turbottest74468",
    "tags": {
      "name": "turbottest74468"
    },
    "threshold": 80
  }
]
✔ PASSED

Running SQL query: test-list-call-query.sql
[
  {
    "alarm_arn": "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468",
    "alarm_description": "turbottest74468",
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "metric_name": "CPUUtilization",
    "name": "turbottest74468"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "013122550996",
    "akas": [
      "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468"
    ],
    "alarm_arn": "arn:aws:cloudwatch:us-east-1:013122550996:alarm:turbottest74468",
    "name": "turbottest74468",
    "partition": "aws",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest74468"
    },
    "title": "turbottest74468"
  }
]
✔ PASSED

POSTTEST: tests/aws_clouwatch_alarm

TEARDOWN: tests/aws_clouwatch_alarm

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```

## Examples

### Basic info

```sql
select
  name,
  state_value,
  metric_name,
  actions_enabled
from
  aws_cloudwatch_alarm;
```

+------------------------------------------------------------------------------------------+-------------------+-------------------------------+-----------------+
| name                                                                                     | state_value       | metric_name                   | actions_enabled |
+------------------------------------------------------------------------------------------+-------------------+-------------------------------+-----------------+
| Default_Test_Alarm3                                                                      | INSUFFICIENT_DATA | Default_Test                  | true            |
| Default_Test_Alarm4                                                                      | INSUFFICIENT_DATA | <null>                        | true            |
| testing1                                                                                 | INSUFFICIENT_DATA | MissingBlocks                 | true            |
| alarm-cis0306                                                                            | INSUFFICIENT_DATA | cis0306                       | true            |
| Billing alarm                                                                            | OK                | EstimatedCharges              | true            |
| Default_Test_Alarm5                                                                      | INSUFFICIENT_DATA | <null>                        | true            |
| alarm-cis0310                                                                            | INSUFFICIENT_DATA | cis0310                       | true            |
| TargetTracking-table/table1-AlarmHigh-a3b9103f-7bd0-4d88-9733-6ef3cd160ddb               | OK                | ConsumedReadCapacityUnits     | true            |
| alarm-cis0307                                                                            | INSUFFICIENT_DATA | cis0307                       | true            |
| TargetTracking-table/table1-AlarmHigh-b293885f-b438-494e-8817-87154da80a30               | OK                | ConsumedWriteCapacityUnits    | true            |
| alarm-cis0308                                                                            | INSUFFICIENT_DATA | cis0308                       | true            |
| alarm-cis0314                                                                            | INSUFFICIENT_DATA | cis0314                       | true            |
| alarm-cis0309                                                                            | INSUFFICIENT_DATA | cis0309                       | true            |
| TargetTracking-table/table1-AlarmLow-2464c435-817a-4d0f-ad8a-5fcd2def54d8                | ALARM             | ConsumedReadCapacityUnits     | true            |
| awsebs-vol-0fab0196974f8007d-Idle-Time                                                   | INSUFFICIENT_DATA | VolumeIdleTime                | true            |
| TargetTracking-table/table1-AlarmLow-4932b9b9-c9be-4a0f-a538-f6b128eb7134                | ALARM             | ConsumedWriteCapacityUnits    | true            |

### List of cloudwatch alarms whose state is in alarm

```sql
select
  name,
  alarm_arn,
  state_value,
  state_reason
from
  aws_cloudwatch_alarm
where
 state_value = 'ALARM';

+---------------------------------------------------------------------------------------------------------------------------+-------------+---------------------------------------------------------------------------------------------------
| alarm_arn                                                                                                                 | state_value | state_reason                                                                                      
+---------------------------------------------------------------------------------------------------------------------------+-------------+---------------------------------------------------------------------------------------------------
| arn:aws:cloudwatch:us-east-1:013122550996:alarm:TargetTracking-table/table1-AlarmLow-4932b9b9-c9be-4a0f-a538-f6b128eb7134 | ALARM       | Threshold Crossed: 15 datapoints were less than the threshold (150.0). The most recent datapoints 
| arn:aws:cloudwatch:us-east-1:013122550996:alarm:TargetTracking-table/table1-AlarmLow-2464c435-817a-4d0f-ad8a-5fcd2def54d8 | ALARM       | Threshold Crossed: 15 datapoints were less than the threshold (150.0). The most recent datapoints

### List of cloudwatch alarms whose action enabled is on

```sql
select
  alarm_arn,
  actions_enabled
from
  aws_cloudwatch_alarm
where
 actions_enabled;
```

+------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| alarm_arn                                                                                                                                | actions_enabled |
+--------------------------------------------------------------------------- [...]

2021-03-24 06:23 UTC, Subhajit97 commented on aws/table_aws_cloudwatch_alarm.go
> +			{
Move all the JSON type columns at the end.

2021-03-24 06:26 UTC, Subhajit97 commented on aws-test/tests/aws_cloudwatch_alarm/variables.tf
> +}
```suggestion
}

```

2021-03-24 06:27 UTC, Subhajit97 requested changes
Resolve conflicts and make suggested changes

2021-03-26 09:45 UTC, Subhajit97 approved these changes
LGTM

2021-03-26 10:25 UTC, rajmohanty17 approved these changes
LGTM

2021-03-29 17:37 UTC, cbruno10 approved these changes

2021-03-29 17:37 UTC, merged