Add table aws_kinesis_firehose_delivery_stream. closes #195
turbot/steampipe-plugin-aws pull request #206
Opened 2021-03-18 10:29 UTC by sayan133

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-03-30 07:34 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +				Name:        "delivery_stream_arn",
```suggestion
				Name:        "arn",
```

2021-03-30 07:39 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +func listStreams(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listFirehoseDeliveryStreams(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-03-30 07:39 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +func describeStream(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func describeFirehoseDeliveryStreams(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-30 07:46 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +func getAwsKinesisFirehoseDeliveryStreamTags(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func listFirehoseDeliveryStreamTags(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-30 07:48 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +The AWS Kinesis Firehose Delivery Stream resource delivers real-time streaming data to an Amazon Simple Storage Service (Amazon S3), Amazon Redshift, or Amazon Elasticsearch Service (Amazon ES) desti
```suggestion
The AWS Kinesis Firehose Delivery Stream resource delivers real-time streaming data to an Amazon Simple Storage Service (Amazon S3), Amazon Redshift or Amazon Elasticsearch Service (Amazon ES) destination.
```

2021-03-30 07:49 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +### List firehose delivery streams which are not in ACTIVE state
```suggestion
### List firehose delivery streams which are not active
```

2021-03-30 07:50 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +  delivery_stream_arn,
```suggestion
  arn,
```

2021-03-30 07:51 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +### List firehose delivery streams which updated in last 7 days
```suggestion
### List firehose delivery streams which are not updated in last 7 days
```

2021-03-30 07:55 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +```
Make the above query as your 3rd query and bring the current 3rd query here

2021-03-30 08:01 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +			},
leaving the first 5 columns, can you please arrange the remaining columns in alphabetical order

2021-03-30 08:04 UTC, Paulami30 reviewed
please check the comments and resolve the merge conflicts

2021-03-30 10:44 UTC, Paulami30 commented on aws/service.go
> +// Firehose returns the service connection for AWS Kinesis Firehose service
```suggestion
// FirehoseService returns the service connection for AWS Kinesis Firehose service
```

2021-03-30 10:45 UTC, Paulami30 commented on aws/table_aws_kinesis_firehose_delivery_stream.go
> +func describeFirehoseDeliveryStreams(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func describeFirehoseDeliveryStream(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-03-30 10:46 UTC, Paulami30 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +### List firehose delivery streams which are not in active
```suggestion
### List firehose delivery streams which are not active
```

2021-03-30 11:09 UTC, Paulami30 commented
LGTM

2021-03-30 11:11 UTC, Paulami30 approved these changes

2021-03-30 11:21 UTC, rajmohanty17 commented on docs/tables/aws_kinesis_firehose_delivery_stream.md
> +  delivery_stream_encryption_configuration ->> 'Status' = 'ENABLED';
where
  delivery_stream_encryption_configuration ->> 'Status' = 'ENABLED'; 
OR != 'ENABLED' ?

2021-03-30 11:24 UTC, rajmohanty17 requested changes
Check the List firehose delivery streams which are not encrypted where clause.

2021-03-30 11:51 UTC, rajmohanty17 approved these changes
LGTM

2021-04-02 15:03 UTC, cbruno10 approved these changes

2021-04-02 15:05 UTC, merged