Add table_aws_transfer_user
turbot/steampipe-plugin-aws pull request #2089
Opened 2024-02-27 10:10 UTC by jramosf

# Integration test logs
<details>
  <summary>Logs</summary>

```
  N/A, Terraform tests will run in turbot/steampipe-plugin-aws.git pipeline
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```sql+postgres
> select server_id, user_name, arn from aws_transfer_user where server_id in (select server_id from aws_transfer_server) and user_name = 'foobar';
+---------------------+-----------+-------------------------------------------------------------------------+
| server_id           | user_name | arn                                                                     |
+---------------------+-----------+-------------------------------------------------------------------------+
| s-xxxxxxxxxxxxxxxxx | foobar    | arn:aws:transfer:us-west-2:123456789901:user/s-xxxxxxxxxxxxxxxxx/foobar |
| s-xxxxxxxxxxxxxxxxx | foobar    | arn:aws:transfer:us-west-2:123456789901:user/s-xxxxxxxxxxxxxxxxx/foobar |
| s-xxxxxxxxxxxxxxxxx | foobar    | arn:aws:transfer:us-west-2:123456789901:user/s-xxxxxxxxxxxxxxxxx/foobar |
+---------------------+-----------+-------------------------------------------------------------------------+
```

```sql+postgres
> select server_id, user_name, home_directory_mappings->0->>'Entry' as entry_home_directory, home_directory_mappings->0->>'Target' as target_home_directory from aws_transfer_user where server_id = 's-xxxxxxxxxxxxxxxxx' limit 2;
+---------------------+-----------+----------------------+------------------------------------------------------------------------+
| server_id           | user_name | entry_home_directory | target_home_directory                                                  |
+---------------------+-----------+----------------------+------------------------------------------------------------------------+
| s-xxxxxxxxxxxxxxxxx | foobarabc | /                    | /transf-bucket2/companies/3edea173-fa04-4177-bdb5-e0951ae6e110/exports |
| s-xxxxxxxxxxxxxxxxx | foobarxyz | /                    | /transf-bucket2/companies/d5f68077-6207-4ef9-baaf-bcbc1e1665c6/exports |
+---------------------+-----------+----------------------+------------------------------------------------------------------------+
```

</details>

Tested OK with live data against AWS APIs. More examples in `README.md`.

2024-03-13 12:11 UTC, misraved requested changes
Thanks @jramosf for the new table 👍.

Please take a look at the review comments and let us know if you have questions 👍.

2024-03-13 12:11 UTC, misraved commented on docs/tables/aws_transfer_user.md
@jramosf could you please add the corresponding SQLite example queries?

2024-03-13 19:24 UTC, jramosf commented on aws/table_aws_transfer_user.go
> +			KeyColumns:    plugin.SingleColumn("server_id"),
Addressed

2024-03-13 19:24 UTC, jramosf commented on aws/table_aws_transfer_user.go
> +		ServerId:   aws.String(d.EqualsQuals["server_id"].GetStringValue()),
Addressed

2024-03-13 19:24 UTC, jramosf commented on docs/tables/aws_transfer_user.md
Done

2024-03-13 19:25 UTC, jramosf commented
Hi @misraved , thanks for the review. I've addressed all changes and made the whole thing more efficient (we only use the expensive `DescribeUser` API call when user polls those columns. Resending for review (I've force-pushed my changes).

2024-03-15 06:17 UTC, bigdatasourav commented on aws/table_aws_transfer_user.go
> +		userName = d.EqualsQuals["user_name"].GetStringValue()
```suggestion
		userName = d.EqualsQualString("user_name")
```

2024-03-15 06:17 UTC, bigdatasourav commented on aws/table_aws_transfer_user.go
> +		serverID = d.EqualsQuals["server_id"].GetStringValue()
```suggestion
		serverID = d. EqualsQualString("server_id")
```

2024-03-15 06:18 UTC, bigdatasourav commented
@jramosf, could you please make the minor changes as suggested above?

2024-03-15 07:46 UTC, jramosf commented
> @jramosf, could you please make the minor changes as suggested above?

Done

2024-03-15 07:47 UTC, bigdatasourav commented on aws/table_aws_transfer_user.go
> +		serverID = d. EqualsQualString("server_id")
```suggestion
		serverID = d.EqualsQualString("server_id")
```

2024-03-15 07:48 UTC, bigdatasourav commented on aws/table_aws_transfer_user.go
> +		serverID = d. EqualsQualString("server_id")
@jramosf, could you please fix this?

2024-03-15 08:03 UTC, bigdatasourav approved these changes

2024-03-15 08:08 UTC, misraved approved these changes

2024-03-15 08:09 UTC, merged