Add table aws_redshift_parameter_group. Closes #190
turbot/steampipe-plugin-aws pull request #217
Opened 2021-03-19 07:15 UTC by anisadas

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/aws_redshift_parameter_group []

PRETEST: tests/aws_redshift_parameter_group

TEST: tests/aws_redshift_parameter_group
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_redshift_parameter_group.named_test_resource: Creating...
aws_redshift_parameter_group.named_test_resource: Creation complete after 4s [id=turbottest47859]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:redshift:us-east-1:986325076436:parametergroup:turbottest47859
resource_name = turbottest47859

Running SQL query: test-get-query.sql
[
  {
    "family": "redshift-1.0",
    "name": "turbottest47859",
    "tags": {
      "name": "turbottest47859"
    }
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "name": "turbottest47859",
    "tags": {
      "name": "turbottest47859"
    },
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest47859"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "name": "turbottest47859",
    "partition": "aws",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest47859"
    },
    "title": "turbottest47859"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:redshift:us-east-1:986325076436:parametergroup:turbottest47859"
    ],
    "name": "turbottest47859",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest47859"
    },
    "title": "turbottest47859"
  }
]
✔ PASSED

POSTTEST: tests/aws_redshift_parameter_group

TEARDOWN: tests/aws_redshift_parameter_group

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-03-19 14:39 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +### Details of several parameters which are associated with each parameter group
```suggestion
### Details of the parameters associated with each parameter group
```

2021-03-19 14:40 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +A parameter group contains a WLM configuration and a set of cluster parameters. It optimizes query performance.
```suggestion
A parameter group is a group of parameters that apply to all of the databases that you create in the cluster. 

```

2021-03-19 14:41 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +  jsonb_pretty(parameters)
expand the json object

2021-03-25 06:01 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +A parameter group is a group of parameters that apply to all of the databases that you create in the cluster.
```suggestion
A parameter group is a group of parameters that apply to all of the databases that you create in the cluster. 

```
```suggestion
A parameter group is a group of parameters that apply to all of the databases that you create in the cluster. 
```

2021-03-25 06:02 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +A parameter group is a group of parameters that apply to all of the databases that you create in the cluster.
```suggestion
A parameter group is a group of parameters that apply to all of the databases that you create in the cluster. 

```

2021-03-30 09:34 UTC, Paulami30 commented on aws-test/tests/aws_redshift_parameter_group/test-get-query.sql
> +select family, name , tags
```suggestion
select family, name, tags
```

2021-03-30 09:34 UTC, Paulami30 commented on aws-test/tests/aws_redshift_parameter_group/test-hydrate-query.sql
> +select name , tags , tags_src
```suggestion
select name, tags, tags_src
```

2021-03-30 09:35 UTC, Paulami30 commented on aws-test/tests/aws_redshift_parameter_group/test-list-query.sql
> +select name , partition , region  , tags , title
```suggestion
select name, partition, region , tags, title
```

2021-03-30 09:35 UTC, Paulami30 commented on aws-test/tests/aws_redshift_parameter_group/test-list-query.sql
> +select name , partition , region  , tags , title
Fix spaces in the sql files

2021-03-31 06:52 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +### Details of the parameters associated with each parameter group
```suggestion
### Get the details of the parameters associated with each parameter group
```

2021-03-31 06:53 UTC, Paulami30 commented on aws/table_aws_redshift_parameter_group.go
> +	// TODO put me in helper function
```suggestion

	// TODO put me in helper function
```

2021-03-31 09:00 UTC, Paulami30 commented on aws/table_aws_redshift_parameter_group.go
> +				Name:        "name",
```suggestion
				Name:        "parameter_group_name",
```

2021-03-31 09:09 UTC, Paulami30 commented on aws/plugin.go
> +			"aws_redshift_parameter_group":           tableAwsRedshiftParameterGroup(ctx),
sort the list

2021-03-31 09:18 UTC, Paulami30 commented on docs/tables/aws_redshift_parameter_group.md
> +```
Rearrange this and add the other fields like AllowedValues, IsModifiable, MinimumEngineVersion
```
select
  name,
  p ->> 'ParameterName' as parameter_name,
  p ->> 'ParameterValue' as parameter_value,
  p ->> 'Description' as description,
  p ->> 'Source' as source,
  p ->> 'DataType' as data_type,
  p ->> 'ApplyType' as apply_type
from
  aws_redshift_parameter_group,
  jsonb_array_elements(parameters) as p;
```

2021-03-31 10:54 UTC, Paulami30 approved these changes

2021-03-31 11:39 UTC, rajmohanty17 requested changes
Pls check the comment.

2021-04-06 07:40 UTC, rajmohanty17 approved these changes
LGTM

2021-04-06 08:38 UTC, rajmohanty17 commented
Thanks for changing the doc.

2021-04-06 20:29 UTC, cbruno10 approved these changes

2021-04-06 20:29 UTC, merged