Add table aws_redshift_subnet_group closes #198
turbot/steampipe-plugin-aws pull request #220
Opened 2021-03-19 11:39 UTC by Paulami30

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_redshift_subnet_group []

PRETEST: tests/aws_redshift_subnet_group

TEST: tests/aws_redshift_subnet_group
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_vpc.my_vpc: Creating...
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Still creating... [20s elapsed]
aws_vpc.my_vpc: Creation complete after 29s [id=vpc-0ccd35fe4efc95678]
aws_subnet.my_subnet: Creating...
aws_subnet.my_subnet: Still creating... [10s elapsed]
aws_subnet.my_subnet: Creation complete after 15s [id=subnet-087088805169b03a0]
aws_redshift_subnet_group.named_test_resource: Creating...
aws_redshift_subnet_group.named_test_resource: Still creating... [10s elapsed]
aws_redshift_subnet_group.named_test_resource: Creation complete after 15s [id=turbottest57717]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = arn:aws:redshift:us-east-1:352685002396:subnetgroup:turbottest57717
resource_id = turbottest57717
resource_name = turbottest57717
vpc_id = vpc-0ccd35fe4efc95678

Running SQL query: test-get-query.sql
[
  {
    "cluster_subnet_group_name": "turbottest57717",
    "description": "A test subnet group",
    "subnet_group_status": "Complete",
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest57717"
      }
    ],
    "vpc_id": "vpc-0ccd35fe4efc95678"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:redshift:us-east-1:352685002396:subnetgroup:turbottest57717"
    ],
    "cluster_subnet_group_name": "turbottest57717",
    "description": "A test subnet group",
    "tags": {
      "name": "turbottest57717"
    },
    "title": "turbottest57717"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:redshift:us-east-1:352685002396:subnetgroup:turbottest57717"
    ],
    "cluster_subnet_group_name": "turbottest57717",
    "description": "A test subnet group",
    "subnet_group_status": "Complete",
    "tags": {
      "name": "turbottest57717"
    },
    "title": "turbottest57717"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

POSTTEST: tests/aws_redshift_subnet_group

TEARDOWN: tests/aws_redshift_subnet_group

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-03-23 13:30 UTC, Subhajit97 commented on aws/table_aws_redshift_subnet_group.go
> +			},
Add `subnet_group_status` column before `description`.

2021-03-23 13:32 UTC, Subhajit97 commented on aws/table_aws_redshift_subnet_group.go
> +			},
Move `tags` column after `title`.
Generally we add the standard column in this order(i.e. `title`, `tags` and `akas`)

2021-03-23 13:33 UTC, Subhajit97 commented on aws/table_aws_redshift_subnet_group.go
> +}
Move this code block after `getRedshiftSubnetGroupAkas`, as we add the tarnsform functions at the end

2021-03-23 13:34 UTC, Subhajit97 commented on aws-test/tests/aws_redshift_subnet_group/variables.tf
> +  ]
```suggestion
  subnet_ids = [aws_subnet.my_subnet.id]
```

2021-03-23 13:35 UTC, Subhajit97 requested changes
Make suggested changes

2021-03-25 06:33 UTC, Subhajit97 commented on aws/table_aws_redshift_subnet_group.go
> +func getRedshiftSubnetGroupTurbotTags(_ context.Context, d *transform.TransformData) (interface{}, error) {
```suggestion
func redshiftSubnetGroupTurbotTags(_ context.Context, d *transform.TransformData) (interface{}, error) {
```

2021-03-25 06:33 UTC, Subhajit97 commented on aws/table_aws_redshift_subnet_group.go
> +	// Get the resource tags
```suggestion

	// Get the resource tags
```

2021-03-25 06:36 UTC, Subhajit97 commented on docs/tables/aws_redshift_subnet_group.md
> +  cross join jsonb_array_elements(subnets) as subnet;
avoid using `cross join` when you don't need it in the examples
```suggestion
  aws_redshift_subnet_group,
  jsonb_array_elements(subnets) as subnet;
```

2021-03-25 06:40 UTC, Subhajit97 requested changes
@Paulami30 There are few more changes required, otherwise it looks good.

2021-03-26 10:50 UTC, Subhajit97 approved these changes
LGTM

2021-03-26 11:06 UTC, rajmohanty17 approved these changes
LGTM

2021-03-29 18:04 UTC, cbruno10 approved these changes

2021-03-29 18:04 UTC, merged