Issue 188
turbot/steampipe-plugin-aws pull request #223
Opened 2021-03-19 17:08 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
PRETEST: tests/aws_wellarchiected_workload
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "aws wellarchitected create-workload --workload-name turbottest33004 --description 'testinh-cli'  --environment 'PREPRODUCTION' --review-owner 'khushboo' --lenses 'wellarchitected' --aws-regions 'us-east-1' > /private/var/folders/60/6lk71pss3fn9r6whrktxd7fm0000gp/T/tests/aws_wellarchiected_workload/terraform/pretest/kinesis_stream.json"]
null_resource.named_test_resource: Creation complete after 2s [id=8751328409019315052]
data.local_file.input: Refreshing state...
data.template_file.resource_aka: Refreshing state...

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = 013122550996
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:wellarchitected:us-east-1:013122550996:workload/d80b4226263c0c5ab0110b0bf29d473d
resource_id = d80b4226263c0c5ab0110b0bf29d473d
resource_name = turbottest33004

TEST: tests/aws_wellarchiected_workload
Running terraform

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Running SQL query: test-get-query.sql
[
  {
    "account_id": "013122550996",
    "akas": [
      "arn:aws:wellarchitected:us-east-1:013122550996:workload/d80b4226263c0c5ab0110b0bf29d473d"
    ],
    "title": "turbottest33004",
    "workload_id": "d80b4226263c0c5ab0110b0bf29d473d",
    "workload_name": "turbottest33004"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:wellarchitected:us-east-1:013122550996:workload/d80b4226263c0c5ab0110b0bf29d473d"
    ],
    "title": "turbottest33004",
    "workload_id": "d80b4226263c0c5ab0110b0bf29d473d",
    "workload_name": "turbottest33004"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "013122550996",
    "akas": [
      "arn:aws:wellarchitected:us-east-1:013122550996:workload/d80b4226263c0c5ab0110b0bf29d473d"
    ],
    "partition": "aws",
    "region": "us-east-1",
    "title": "turbottest33004",
    "workload_id": "d80b4226263c0c5ab0110b0bf29d473d",
    "workload_name": "turbottest33004"
  }
]
✔ PASSED

POSTTEST: tests/aws_wellarchiected_workload
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "    aws wellarchitected delete-workload --workload-id  d80b4226263c0c5ab0110b0bf29d473d;\n"]
null_resource.named_test_resource: Creation complete after 2s [id=4854661456047373823]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

TEARDOWN: tests/aws_wellarchiected_workload

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
 ```
 ## Basic info
 select
  workload_name,
  workload_id,
  environment,
  industry,
  owner
from
  aws_wellarchitected_workload
+---------------+----------------------------------+---------------+----------+--------------+
| workload_name | workload_id                      | environment   | industry | owner        |
+---------------+----------------------------------+---------------+----------+--------------+
| test12        | 3bea73a2e4eb0bfb84c09627b5723599 | PREPRODUCTION | Defense  | 013122550996 |

```

```
## List of workload with production environment

select
  workload_name,
  workload_id,
  environment
from
  aws_wellarchitected_workload
where
  environment = 'PREPRODUCTION';

+---------------+----------------------------------+---------------+
| workload_name | workload_id                      | environment   |
+---------------+----------------------------------+---------------+
| test12        | 3bea73a2e4eb0bfb84c09627b5723599 | PREPRODUCTION |
+---------------+----------------------------------+---------------+

```

```
## List of aws regions associated with the workload,

select
  workload_name,
  workload_id,
  environment,
  aws_regions
from
  aws_wellarchitected_workload;

+---------------+----------------------------------+---------------+---------------------------+
| workload_name | workload_id                      | environment   | aws_regions               |
+---------------+----------------------------------+---------------+---------------------------+
| test12        | 3bea73a2e4eb0bfb84c09627b5723599 | PREPRODUCTION | ["us-east-1","us-east-2"] |
+---------------+----------------------------------+---------------+---------------------------+
```

```
## Industry type of the workloads

select
  workload_name,
  workload_id,
  industry_type
from
  aws_wellarchitected_workload;

+---------------+----------------------------------+---------------+
| workload_name | workload_id                      | industry_type |
+---------------+----------------------------------+---------------+
| test12        | 3bea73a2e4eb0bfb84c09627b5723599 | Defense       |
+---------------+----------------------------------+---------------+
```

```
## List of workloads with IsReviewOwnerUpdateAcknowledged no enabled

select
  workload_name,
  workload_id,
  is_review_owner_update_acknowledged
from
  aws_wellarchitected_workload
where
  not is_review_owner_update_acknowledged;

+---------------+-------------+-------------------------------------+
| workload_name | workload_id | is_review_owner_update_acknowledged |
+---------------+-------------+-------------------------------------+
+---------------+-------------+-------------------------------------+
```
```
</details>

2021-03-29 09:05 UTC, Subhajit97 commented on aws/plugin.go
> +			"aws_wellarchitected_workload":           tableAwsWellArchitectedWorload(ctx),
```suggestion
			"aws_wellarchitected_workload":           tableAwsWellArchitectedWorkload(ctx),
```

2021-03-29 09:05 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +func tableAwsWellArchitectedWorload(_ context.Context) *plugin.Table {
```suggestion
func tableAwsWellArchitectedWorkload(_ context.Context) *plugin.Table {
```

2021-03-29 09:05 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +			Hydrate:           getWellArchitectedWorload,
Update the function names

2021-03-29 09:06 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +		Description: "AWS Well Architected Workload",
```suggestion
		Description: "AWS Well-Architected Workload",
```

2021-03-29 09:07 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +			// Standard columns
Add a blank line before comment
```suggestion

			// Standard columns
```

2021-03-29 09:08 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +	plugin.Logger(ctx).Trace("listWellArchitectedWorloads", "AWS_REGION", region)
```suggestion
	plugin.Logger(ctx).Trace("listWellArchitectedWorkloads", "AWS_REGION", region)
```

2021-03-29 09:09 UTC, Subhajit97 commented on aws/table_aws_wellarchitected_workload.go
> +	logger.Trace("getWellArchitectedWorload")
```suggestion
	logger.Trace("getWellArchitectedWorkload")
```

2021-03-29 09:10 UTC, Subhajit97 commented on aws-test/tests/aws_wellarchitected_workload/posttest-variables.tf
> +
```suggestion
```

2021-03-29 09:10 UTC, Subhajit97 commented on aws-test/tests/aws_wellarchitected_workload/posttest-variables.tf
> +
```suggestion
```

2021-03-29 09:11 UTC, Subhajit97 commented on aws-test/tests/aws_wellarchitected_workload/posttest-variables.tf
> +    aws wellarchitected delete-workload --workload-id  {{ output.resource_id.value }};
```suggestion
    aws wellarchitected delete-workload --workload-id {{ output.resource_id.value }};
```

2021-03-29 09:15 UTC, Subhajit97 requested changes
@khushboo9024 There are some changes required. Please see comments.

2021-03-30 11:32 UTC, Subhajit97 commented on aws/service.go
> +		return nil, fmt.Errorf("region must be passed SsmService")
```suggestion
		return nil, fmt.Errorf("region must be passed WellArchitectedService")
```

2021-03-30 11:32 UTC, Subhajit97 commented on aws/service.go
> +// WellArchitectedService returns the service connection for AWS Well Architected service
```suggestion
// WellArchitectedService returns the service connection for AWS Well-Architected service
```

2021-03-31 05:26 UTC, Subhajit97 approved these changes
LGTM

2021-03-31 10:05 UTC, rajmohanty17 approved these changes
LGTM

2021-04-02 15:11 UTC, cbruno10 approved these changes

2021-04-02 15:17 UTC, cbruno10 commented
@johnsmyth AWS Well-Architected Tool doesn't have Terraform support yet, should the table be called `aws_wellarchitected_workload`, `aws_wellarchitectedtool_workload` or variants with underscores (`aws_well_architected_workload`, `aws_well_architected_tool_workload`)?

2021-04-02 18:13 UTC, johnsmyth commented
@cbruno10 I think `aws_wellarchitected_workload` is best.  I dont the think `tool` (`aws_wellarchitectedtool_workload`) adds anything , its just more to type in an already long name, and I *generally* prefer not splitting the "service" portion of the table name with an underscore.  The golang sdk uses `wellarchitected` as the service name, which is also a reasonable rationale.

2021-04-05 13:50 UTC, merged