Add table aws_inspector_assessment_target. closes #226
turbot/steampipe-plugin-aws pull request #234
Opened 2021-03-22 13:50 UTC by sayan133

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_inspector_assessment_target []

PRETEST: tests/aws_inspector_assessment_target

TEST: tests/aws_inspector_assessment_target
Running terraform
aws_inspector_resource_group.inspector_rg: Creating...
aws_inspector_resource_group.inspector_rg: Creation complete after 3s [id=arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-lMf2q9bo]
aws_inspector_assessment_target.named_test_resource: Creating...
aws_inspector_assessment_target.named_test_resource: Creation complete after 2s [id=arn:aws:inspector:us-east-1:388460667113:target/0-1A0YZ4h8]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

account_id = "388460667113"
aws_partition = "aws"
aws_region = "us-east-1"
resource_aka = "arn:aws:inspector:us-east-1:388460667113:target/0-1A0YZ4h8"
resource_group_aka = "arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-lMf2q9bo"
resource_name = "turbottest9791"

Running SQL query: test-get-query.sql
[
  {
    "account_id": "388460667113",
    "arn": "arn:aws:inspector:us-east-1:388460667113:target/0-1A0YZ4h8",
    "name": "turbottest9791",
    "partition": "aws",
    "region": "us-east-1",
    "resource_group_arn": "arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-lMf2q9bo"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:inspector:us-east-1:388460667113:target/0-1A0YZ4h8",
    "name": "turbottest9791",
    "resource_group_arn": "arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-lMf2q9bo"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:inspector:us-east-1:388460667113:target/0-1A0YZ4h8"
    ],
    "title": "turbottest9791"
  }
]
✔ PASSED

POSTTEST: tests/aws_inspector_assessment_target

TEARDOWN: tests/aws_inspector_assessment_target

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  name,
  arn,
  resource_group_arn,
  created_at,
  updated_at,
  region
from
  aws_inspector_assessment_target;
```

```
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+
| name      | arn                                                        | resource_group_arn                                                | created_at          | updated_at          | region    |
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+
| test-stem | arn:aws:inspector:us-east-1:388460667113:target/0-O7bVKxDE | arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-DjVxQgCg | 2021-03-22 08:11:08 | 2021-03-22 08:11:08 | us-east-1 |
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+

```

### List Assessment Targets that are created within last 7 days

```sql
select
  name,
  arn,
  resource_group_arn,
  created_at,
  updated_at,
  region
from
  aws_inspector_assessment_target
where
  created_at > (current_date - interval '7' day);
```

```
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+
| name      | arn                                                        | resource_group_arn                                                | created_at          | updated_at          | region    |
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+
| test-stem | arn:aws:inspector:us-east-1:388460667113:target/0-O7bVKxDE | arn:aws:inspector:us-east-1:388460667113:resourcegroup/0-DjVxQgCg | 2021-03-22 08:11:08 | 2021-03-22 08:11:08 | us-east-1 |
+-----------+------------------------------------------------------------+-------------------------------------------------------------------+---------------------+---------------------+-----------+

```

### List Assessment Targets that are updated after creation

```sql
select
  name,
  arn,
  resource_group_arn,
  created_at,
  updated_at,
  region
from
  aws_inspector_assessment_target
where
  created_at != updated_at;
```

```
+------+-----+--------------------+------------+------------+--------+
| name | arn | resource_group_arn | created_at | updated_at | region |
+------+-----+--------------------+------------+------------+--------+
+------+-----+--------------------+------------+------------+--------+

```
```
</details>

2021-03-25 10:38 UTC, khushboo9024 commented on aws-test/tests/aws_inspector_assessment_target/variables.tf
> +  default     = "integration-tests"
```suggestion
  default     = "default"
```

2021-03-25 10:50 UTC, khushboo9024 commented on aws/table_aws_inspector_assessment_target.go
> +			ShouldIgnoreError: isNotFoundError([]string{}),
If there is no not found error then please remove this.

2021-03-25 10:53 UTC, khushboo9024 commented on aws/table_aws_inspector_assessment_target.go
> +	// TODO put me in helper function
```suggestion
```

2021-03-25 10:53 UTC, khushboo9024 commented on aws/table_aws_inspector_assessment_target.go
> +	// TODO put me in helper function
```suggestion
```

2021-03-25 10:55 UTC, khushboo9024 commented on aws/table_aws_inspector_assessment_target.go
> +func describeAssessmentTarget(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
function name should be `getInspectorAssessmentTarget`

2021-03-25 10:56 UTC, khushboo9024 commented on aws/table_aws_inspector_assessment_target.go
> +func listAssessmentTargets(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
function name should be `listInspectorAssessmentTargets`

2021-03-25 11:02 UTC, khushboo9024 reviewed
Please make the suggested changes.

2021-03-26 06:20 UTC, khushboo9024 approved these changes
LGTM

2021-03-26 07:01 UTC, Subhajit97 commented on aws/table_aws_inspector_assessment_target.go
> +	if len(data.AssessmentTargets) > 0 {
```suggestion
	if data.AssessmentTargets != nil && len(data.AssessmentTargets) > 0 {
```

2021-03-26 07:04 UTC, Subhajit97 requested changes
@sayan133 There is a small change, otherwise looks good.

2021-03-26 09:53 UTC, Subhajit97 approved these changes
LGTM

2021-03-26 10:36 UTC, rajmohanty17 approved these changes
LGTM

2021-04-08 18:07 UTC, cbruno10 approved these changes

2021-04-08 18:07 UTC, merged