Add table aws_guardduty_detector. Closes #203
turbot/steampipe-plugin-aws pull request #251
Opened 2021-03-24 15:37 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-03-29 09:26 UTC, Subhajit97 commented on aws/service.go
> +// GuardDutyService returns the service connection for AWS ELB GuardDuty service
```suggestion
// GuardDutyService returns the service connection for AWS GuardDuty service
```

2021-03-29 09:28 UTC, Subhajit97 commented on aws/table_aws_guardduty_detector.go
> +			// Standard columns
```suggestion

			// Standard columns
```

2021-03-29 09:30 UTC, Subhajit97 commented on aws/table_aws_guardduty_detector.go
> +	id := h.Item.(detectorInfo)
```suggestion
	data := h.Item.(detectorInfo)
```

2021-03-29 09:31 UTC, Subhajit97 commented on aws/table_aws_guardduty_detector.go
> +	aka := "arn:" + commonColumnData.Partition + ":guardduty:" + commonColumnData.Region + ":" + commonColumnData.AccountId + ":detector" + "/" + id.DetectorID
```suggestion
	aka := "arn:" + commonColumnData.Partition + ":guardduty:" + commonColumnData.Region + ":" + commonColumnData.AccountId + ":detector/" + data.DetectorID
```

2021-03-29 09:32 UTC, Subhajit97 commented on aws/table_aws_guardduty_detector.go
> +func getAwsGuardDutyDetectorAkas(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
Don't use `get` keyword when defining any transform function

2021-03-29 09:33 UTC, Subhajit97 commented on docs/tables/aws_guardduty_detector.md
> +  data_sources -> 'FlowLogs' -> 'Status' as flow_logs_status
```suggestion
  data_sources -> 'CloudTrail' ->> 'Status' as cloud_trail_status,
  data_sources -> 'DNSLogs' ->> 'Status' as dns_logs_status,
  data_sources -> 'FlowLogs' ->> 'Status' as flow_logs_status
```

2021-03-29 09:35 UTC, Subhajit97 requested changes
@khushboo9024 There are few changes required. Please see comments.

2021-03-30 11:36 UTC, Subhajit97 approved these changes
LGTM

2021-03-30 12:19 UTC, rajmohanty17 approved these changes
LGTM

2021-04-14 17:57 UTC, cbruno10 approved these changes

2021-04-14 17:59 UTC, merged