Add table aws_wafv2_rule_group. closes #278
turbot/steampipe-plugin-aws pull request #281
Opened 2021-04-02 10:16 UTC by sayan133

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-05-16 16:34 UTC, khushboo9024 commented on aws/table_aws_wafv2_rule_group.go
> +				Name:        "capacity",
`capacity` column should be above `description` column.

2021-05-17 08:48 UTC, khushboo9024 commented on aws/table_aws_wafv2_rule_group.go
> +func regexPatternSetLocation(_ context.Context, d *transform.TransformData) (interface{}, error) {
```suggestion
func ruleGroupLocation(_ context.Context, d *transform.TransformData) (interface{}, error) {
```

2021-05-17 08:49 UTC, khushboo9024 commented on aws/table_aws_wafv2_rule_group.go
> +				Description: "Specifies the scope of the Regex Pattern Set. Possible values are: 'REGIONAL' and 'CLOUDFRONT'.",
Description is wrong.

2021-05-17 08:51 UTC, khushboo9024 requested changes
Minor changes required.

2021-05-18 05:19 UTC, khushboo9024 approved these changes
LGTM

2021-05-20 12:18 UTC, rajmohanty17 requested changes
Made quick remark to change.

2021-05-21 06:42 UTC, rajmohanty17 approved these changes
LGTM

2021-05-21 18:15 UTC, cbruno10 approved these changes

2021-05-21 18:15 UTC, merged