Add table aws_securityhub_standards_subscription. Closes #277
turbot/steampipe-plugin-aws pull request #286
Opened 2021-04-05 09:04 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_securityhub_standards_subscription []

PRETEST: tests/aws_securityhub_standards_subscription

TEST: tests/aws_securityhub_standards_subscription
Running terraform
aws_securityhub_account.named_test_resource: Creating...
aws_securityhub_account.named_test_resource: Creation complete after 4s [id=352685002396]
aws_securityhub_standards_subscription.cis: Creating...
aws_securityhub_standards_subscription.pci_321: Creating...
aws_securityhub_standards_subscription.pci_321: Creation complete after 3s [id=arn:aws:securityhub:us-east-1:352685002396:subscription/pci-dss/v/3.2.1]
aws_securityhub_standards_subscription.cis: Creation complete after 7s [id=arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

account_id = "352685002396"
aws_partition = "aws"
aws_region = "us-east-1"
cis_arn = "arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0"
pci_321_arn = "arn:aws:securityhub:us-east-1:352685002396:subscription/pci-dss/v/3.2.1"

Running SQL query: test-get-query.sql
[
  {
    "enabled_by_default": true,
    "name": "CIS AWS Foundations Benchmark v1.2.0",
    "standards_arn": "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0",
    "standards_subscription_arn": "arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "standards_input": {},
    "standards_status": "INCOMPLETE",
    "standards_subscription_arn": "arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "enabled_by_default": true,
    "name": "CIS AWS Foundations Benchmark v1.2.0",
    "standards_arn": "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0",
    "standards_status": "INCOMPLETE",
    "standards_subscription_arn": "arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:securityhub:us-east-1::standards/pci-dss/v/3.2.1"
    ],
    "name": "PCI DSS v3.2.1",
    "region": "us-east-1",
    "title": "PCI DSS v3.2.1"
  }
]
✔ PASSED

POSTTEST: tests/aws_securityhub_standards_subscription

TEARDOWN: tests/aws_securityhub_standards_subscription

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  name,
  standards_arn description,
  region
from
  aws_securityhub_standards_subscription;

+-------------------------------------------------+-------------------------------------------------------------------------------------------+-----------+
| name                                            | description                                                                               | region    |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+-----------+
| PCI DSS v3.2.1                                  | arn:aws:securityhub:us-east-1::standards/pci-dss/v/3.2.1                                  | us-east-1 |
| CIS AWS Foundations Benchmark v1.2.0            | arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0                       | us-east-1 |
| AWS Foundational Security Best Practices v1.0.0 | arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0 | us-east-1 |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+-----------+
```

### List enabled standards in security hub

```sql
select
  name,
  standards_arn,
  enabled_by_default
from
  aws_securityhub_standards_subscription
where
  enabled_by_default;

+-------------------------------------------------+-------------------------------------------------------------------------------------------+--------------------+
| name                                            | standards_arn                                                                             | enabled_by_default |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+--------------------+
| CIS AWS Foundations Benchmark v1.2.0            | arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0                       | true               |
| AWS Foundational Security Best Practices v1.0.0 | arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0 | true               |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+--------------------+
```

### List standards where standard status is not ready

```sql
select
  name,
  standards_arn,
  standards_subscription_arn,
  standards_status
from
  aws_securityhub_standards_subscription
where
  standards_status <> 'READY';

+-------------------------------------------------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+------------------+
| name                                            | standards_arn                                                                             | standards_subscription_arn                                                                               | standards_status |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+------------------+
| AWS Foundational Security Best Practices v1.0.0 | arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0 | arn:aws:securityhub:us-east-1:352685002396:subscription/aws-foundational-security-best-practices/v/1.0.0 | INCOMPLETE       |
| CIS AWS Foundations Benchmark v1.2.0            | arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0                       | arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0            | INCOMPLETE       |
+-------------------------------------------------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+------------------+
```
```
</details>

2021-04-05 10:20 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +
//// TABLE DEFINITION

2021-04-05 10:29 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +		Description: "AWS Securityhub standards",
```suggestion
		Description: "AWS Security Hub Standards Subscription",
```

2021-04-05 10:31 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +func listSecurityHubStandardSubcriptions(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listSecurityHubStandardsSubcriptions(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-05 10:31 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +	// TODO put me in helper function
```suggestion
```

2021-04-05 10:33 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +	// TODO put me in helper function
```suggestion
```

2021-04-05 10:33 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +func getSecurityHubStandardSubcription(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func getSecurityHubStandardsSubcription(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```
change wherever required.

2021-04-05 10:35 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +	resp, err := svc.DescribeStandards(&securityhub.DescribeStandardsInput{})
Can we use `DescribeStandardsPages` api for list call ?

2021-04-05 10:40 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +		if *item.Name == name {
This is not a get call , here we are just filtering list call.
Do we need this function in this case?

2021-04-05 10:40 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +	// TODO put me in helper function
```suggestion
```

2021-04-05 10:43 UTC, khushboo9024 commented on docs/tables/aws_securityhub_standards_subscription.md
> +  standards_arn description,
syntax is wrong

2021-04-05 10:44 UTC, khushboo9024 commented on docs/tables/aws_securityhub_standards_subscription.md
> +### List enabled standards in security hub
```suggestion
### List enabled security hub standards
```

2021-04-05 11:07 UTC, khushboo9024 requested changes
Please make the suggested changes and resolve conflict.

2021-04-05 11:08 UTC, khushboo9024 commented on aws-test/tests/aws_securityhub_standards_subscription/test-hydrate-expected.json
> +    "standards_subscription_arn": "arn:aws:securityhub:us-east-1:352685002396:subscription/cis-aws-foundations-benchmark/v/1.2.0"
why we are hardcoding account id, region and partition ?

2021-04-05 11:09 UTC, khushboo9024 commented on aws-test/tests/aws_securityhub_standards_subscription/test-turbot-expected.json
> +    "region": "us-east-1",
why we are hardcoding region ?

2021-04-08 05:54 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +func tableAwsSecurityHubStandardSubscription(_ context.Context) *plugin.Table {
```suggestion
func tableAwsSecurityHubStandardsSubscription(_ context.Context) *plugin.Table {
```

2021-04-08 05:55 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +		Description: "Security Hub Standards Subscription",
```suggestion
		Description: "AWS Security Hub Standards Subscription",
```

2021-04-08 05:58 UTC, khushboo9024 commented on docs/tables/aws_securityhub_standards_subscription.md
> +  description region
Syntax is wrong.

2021-04-08 14:03 UTC, khushboo9024 commented on aws/table_aws_securityhub_standards_subscription.go
> +func tableAwsSecurityHubStandardSubscription(_ context.Context) *plugin.Table {
Please change this function name.

2021-04-08 14:07 UTC, khushboo9024 requested changes
Please change the function name from `tableAwsSecurityHubStandardSubscription` to `tableAwsSecurityHubStandardsSubscription`

2021-04-12 12:26 UTC, khushboo9024 approved these changes
LGTM

2021-04-12 12:47 UTC, rajmohanty17 approved these changes
LGTM

2021-04-14 18:42 UTC, cbruno10 commented
@rajeshbal65 Is this table combining security hub standard info, and standard subscription info? How are standards and standard subscriptions related to one another? Can standards exist by themselves, and if so, do they have valuable info in them? Also, how does standards controls relate to standards?

2021-04-15 10:32 UTC, rajeshbal65 commented
@cbruno10 Yes this table is combination security hub standard, and standard subscriptions. Standards gives the available  standards information and Standard subscription gives the whether security hub is subscribed to the standards and its status. 

Standards can exist by themselves but don’t have any valuable information in them.

2021-07-13 06:12 UTC, rajlearner17 commented
@cbruno10 can you pls check this to close

2021-08-16 08:31 UTC, rajlearner17 approved these changes
LGTM

2021-08-17 07:40 UTC, merged