Add table aws_codebuild_project closes #297
turbot/steampipe-plugin-aws pull request #319
Opened 2021-04-15 14:45 UTC by Paulami30

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_codebuild_project []

PRETEST: tests/aws_codebuild_project

TEST: tests/aws_codebuild_project
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_vpc.my_vpc: Creating...
aws_iam_role.test_role: Creating...
aws_s3_bucket.test_bucket: Creating...
aws_s3_bucket.test_bucket: Still creating... [10s elapsed]
aws_iam_role.test_role: Still creating... [10s elapsed]
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Still creating... [20s elapsed]
aws_s3_bucket.test_bucket: Still creating... [20s elapsed]
aws_iam_role.test_role: Still creating... [20s elapsed]
aws_iam_role.test_role: Creation complete after 26s [id=turbottest48279]
aws_s3_bucket.test_bucket: Still creating... [30s elapsed]
aws_vpc.my_vpc: Still creating... [30s elapsed]
aws_s3_bucket.test_bucket: Still creating... [40s elapsed]
aws_vpc.my_vpc: Still creating... [40s elapsed]
aws_vpc.my_vpc: Still creating... [50s elapsed]
aws_s3_bucket.test_bucket: Still creating... [50s elapsed]
aws_s3_bucket.test_bucket: Still creating... [1m0s elapsed]
aws_vpc.my_vpc: Still creating... [1m0s elapsed]
aws_vpc.my_vpc: Still creating... [1m10s elapsed]
aws_s3_bucket.test_bucket: Still creating... [1m10s elapsed]
aws_vpc.my_vpc: Creation complete after 1m11s [id=vpc-007a66fa8dfd15e49]
aws_subnet.my_subnet2: Creating...
aws_subnet.my_subnet1: Creating...
aws_s3_bucket.test_bucket: Still creating... [1m20s elapsed]
aws_subnet.my_subnet1: Still creating... [10s elapsed]
aws_subnet.my_subnet2: Still creating... [10s elapsed]
aws_s3_bucket.test_bucket: Still creating... [1m30s elapsed]
aws_subnet.my_subnet1: Still creating... [20s elapsed]
aws_subnet.my_subnet2: Still creating... [20s elapsed]
aws_subnet.my_subnet1: Creation complete after 20s [id=subnet-02f2fdf011ab7815e]
aws_subnet.my_subnet2: Creation complete after 20s [id=subnet-0f05f70f5231dce27]
aws_s3_bucket.test_bucket: Creation complete after 1m38s [id=turbottest48279]
aws_iam_role_policy.test_role_policy: Creating...
aws_codebuild_project.named_test_resource: Creating...
aws_iam_role_policy.test_role_policy: Still creating... [10s elapsed]
aws_codebuild_project.named_test_resource: Still creating... [10s elapsed]
aws_iam_role_policy.test_role_policy: Creation complete after 13s [id=turbottest48279:terraform-20210415110038971200000001]
aws_codebuild_project.named_test_resource: Creation complete after 14s [id=arn:aws:codebuild:us-east-1:352685002396:project/turbottest48279]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Warning: Interpolation-only expressions are deprecated

  on variables.tf line 155, in resource "aws_codebuild_project" "named_test_resource":
 155:     location = "${aws_s3_bucket.test_bucket.bucket}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = arn:aws:codebuild:us-east-1:352685002396:project/turbottest48279
resource_id = arn:aws:codebuild:us-east-1:352685002396:project/turbottest48279
resource_name = turbottest48279

Running SQL query: test-get-query.sql
[
  {
    "artifacts": {
      "ArtifactIdentifier": null,
      "EncryptionDisabled": null,
      "Location": null,
      "Name": null,
      "NamespaceType": null,
      "OverrideArtifactName": false,
      "Packaging": null,
      "Path": null,
      "Type": "NO_ARTIFACTS"
    },
    "cache": {
      "Location": "turbottest48279",
      "Modes": null,
      "Type": "S3"
    },
    "description": "Resource for testing",
    "name": "turbottest48279",
    "source": {
      "Auth": null,
      "BuildStatusConfig": null,
      "Buildspec": "",
      "GitCloneDepth": 0,
      "GitSubmodulesConfig": null,
      "InsecureSsl": false,
      "Location": "https://github.com/mitchellh/packer.git",
      "ReportBuildStatus": false,
      "SourceIdentifier": null,
      "Type": "GITHUB"
    },
    "title": "turbottest48279"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:codebuild:us-east-1:352685002396:project/turbottest48279"
    ],
    "description": "Resource for testing",
    "name": "turbottest48279",
    "tags": {
      "foo": "bar"
    },
    "title": "turbottest48279"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "artifacts": {
      "ArtifactIdentifier": null,
      "EncryptionDisabled": null,
      "Location": null,
      "Name": null,
      "NamespaceType": null,
      "OverrideArtifactName": false,
      "Packaging": null,
      "Path": null,
      "Type": "NO_ARTIFACTS"
    },
    "description": "Resource for testing",
    "name": "turbottest48279",
    "tags": {
      "foo": "bar"
    },
    "title": "turbottest48279"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

POSTTEST: tests/aws_codebuild_project

TEARDOWN: tests/aws_codebuild_project

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

> select
  name,
  description,
  encryption_key,
  concurrent_build_limit,
  source_version,
  service_role,
  created,
  last_modified,
  region
from
  aws_codebuild_project;
+----------+-------------+-------------------------------------------------+------------------------+----------------+----------------------------------------
| name     | description | encryption_key                                  | concurrent_build_limit | source_version | service_role                           
+----------+-------------+-------------------------------------------------+------------------------+----------------+----------------------------------------
| test-001 | testing     | arn:aws:kms:us-east-1:352685002396:alias/aws/s3 | 2                      | 2              | arn:aws:iam::352685002396:role/service-
+----------+-------------+-------------------------------------------------+------------------------+----------------+----------------------------------------

### Get the build input details of the projects

> select
  name,
  source_version,
  source ->> 'Auth' as auth,
  source ->> 'BuildStatusConfig' as build_status_config,
  source ->> 'Buildspec' as build_spec,
  source ->> 'GitCloneDepth' as git_clone_depth,
  source ->> 'GitSubmodulesConfig' as git_submodules_config,
  source ->> 'InsecureSsl' as insecure_ssl,
  source ->> 'Location' as location,
  source ->> 'ReportBuildStatus' as report_build_status,
  source ->> 'SourceIdentifier' as source_identifier,
  source ->> 'Type' as type
from
  aws_codebuild_project;
+----------+----------------+--------+---------------------+------------+-----------------+-----------------------+--------------+--------------------+-------
| name     | source_version | auth   | build_status_config | build_spec | git_clone_depth | git_submodules_config | insecure_ssl | location           | report
+----------+----------------+--------+------- [...]

2021-04-16 05:29 UTC, Subhajit97 commented on aws/service.go
> +		return nil, fmt.Errorf("region must be passed BackupService")
```suggestion
		return nil, fmt.Errorf("region must be passed CodeBuildService")
```

2021-04-16 05:29 UTC, Subhajit97 commented on aws/service.go
> +	serviceCacheKey := fmt.Sprintf("backup-%s", region)
```suggestion
	serviceCacheKey := fmt.Sprintf("codebuild-%s", region)
```

2021-04-16 05:32 UTC, Subhajit97 commented on aws/table_aws_codebuild_project.go
> +func getCodeBuildProjectTurbotTags(ctx context.Context, d *transform.TransformData) (interface{},
```suggestion
func codeBuildProjectTurbotTags(ctx context.Context, d *transform.TransformData) (interface{},
```

2021-04-16 05:33 UTC, Subhajit97 commented on docs/tables/aws_codebuild_project.md
> +### List of projects which are not created within a VPC
```suggestion
### List projects which are not created within a VPC
```

2021-04-16 05:34 UTC, Subhajit97 commented on docs/tables/aws_codebuild_project.md
> +### List of projects in which logging is not enabled
```suggestion
### List projects with logging disabled
```

2021-04-16 05:36 UTC, Subhajit97 commented on aws-test/tests/aws_codebuild_project/variables.tf
> +    location = "${aws_s3_bucket.test_bucket.bucket}"
```suggestion
    location = aws_s3_bucket.test_bucket.bucket
```

2021-04-16 05:37 UTC, Subhajit97 commented on aws-test/tests/aws_codebuild_project/variables.tf
> +resource "aws_subnet" "my_subnet1" {
Add an extra line between plans

2021-04-16 05:40 UTC, Subhajit97 requested changes
@Paulami30 There are few changes required. Please see comments, thanks!

2021-04-16 14:04 UTC, Subhajit97 approved these changes
LGTM

2021-04-16 15:00 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 20:28 UTC, cbruno10 approved these changes

2021-04-22 20:28 UTC, merged