Add table aws_sagemaker_notebook_instance. closes #200
turbot/steampipe-plugin-aws pull request #324
Opened 2021-04-16 11:27 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/aws_sagemaker_notebook_instance []

PRETEST: tests/aws_sagemaker_notebook_instance

TEST: tests/aws_sagemaker_notebook_instance
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_iam_role.my_role: Creating...
aws_iam_role.my_role: Creation complete after 5s [id=turbottest15146]
aws_sagemaker_notebook_instance.named_test_resource: Creating...
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [10s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [20s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [30s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [40s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [50s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m0s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m10s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m20s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m30s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m40s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [1m50s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m0s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m10s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m20s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m30s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m40s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [2m50s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [3m0s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [3m10s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [3m20s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Still creating... [3m30s elapsed]
aws_sagemaker_notebook_instance.named_test_resource: Creation complete after 3m38s [id=turbottest15146]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbottest15146
resource_id = turbottest15146
resource_name = turbottest15146

Running SQL query: test-get-query.sql
[
  {
    "account_id": "986325076436",
    "arn": "arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbottest15146",
    "name": "turbottest15146",
    "partition": "aws",
    "region": "us-east-1",
    "tags": [
      {
        "Key": "name",
        "Value": "turbottest15146"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbottest15146"
    ],
    "name": "turbottest15146",
    "tags": [
      {
        "Key": "name",
        "Value": "turbottest15146"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbottest15146",
    "name": "turbottest15146",
    "partition": "aws",
    "region": "us-east-1"
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "986325076436",
    "akas": [
      "arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbottest15146"
    ],
    "region": "us-east-1",
    "tags": [
      {
        "Key": "name",
        "Value": "turbottest15146"
      }
    ],
    "title": "turbottest15146"
  }
]
✔ PASSED

POSTTEST: tests/aws_sagemaker_notebook_instance

TEARDOWN: tests/aws_sagemaker_notebook_instance

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  name,
  arn,
  creation_time,
  instance_type,
  notebook_instance_status
from
  aws_sagemaker_notebook_instance;

```
```
+------------------------------------+-----------------------------------------------------------------------------------------------+---------------------+--
| name                               | arn                                                                                           | creation_time       | i
+------------------------------------+-----------------------------------------------------------------------------------------------+---------------------+--
| steampipe12                        | arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/steampipe12                        | 2021-04-16 08:17:51 | m
| test-rupzz                         | arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/test-rupzz                         | 2021-04-08 09:22:53 | m
| turbot-test-20200125-create-update | arn:aws:sagemaker:us-east-1:986325076436:notebook-instance/turbot-test-20200125-create-update | 2021-04-16 09:32:26 | m
+------------------------------------+-----------------------------------------------------------------------------------------------+---------------------+--

```
### List notebook instances with unecrypted data on the ML storage volume

```sql
select
  name,
  kms_key_id
from
  aws_sagemaker_notebook_instance
where
  kms_key_id is null;
```
```
+------------------------------------+------------+
| name                               | kms_key_id |
+------------------------------------+------------+
| turbot-test-20200125-create-update | <null>     |
| test-rupzz                         | <null>     |
+------------------------------------+------------+
```

### List notebook instances that are not publicly available

```sql
select
  name,
  direct_internet_access
from
  aws_sagemaker_notebook_instance
where
  direct_internet_access = 'Disabled';
```
```
+------+------------------------+
| name | direct_internet_access |
+------+------------------------+
+------+------------------------+
```

### List notebook instances whose root access for users disabled

```sql
select
  name,
  root_access
from
  aws_sagemaker_notebook_instance
where
  root_access = 'Disabled';
```
```
+------+-------------+
| name | root_access |
+------+-------------+
+------+-------------+
```

2021-04-16 14:59 UTC, Paulami30 commented on aws-test/tests/aws_sagemaker_notebook_instance/test-get-expected.json
> +]
fix indentation

2021-04-16 15:05 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +				Description: "The date and time that the cluster was created.",
is the description correct?

2021-04-16 15:10 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +				Description: "Describes a group of DeferredMaintenanceWindow objects.",
check the description again

2021-04-16 15:11 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +			},
```suggestion
			},
			
```

2021-04-16 15:12 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +			},
arrange the columns as title, tags, akas

2021-04-16 15:17 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +
you are already getting the arn of the notebook instance.  why is this function required?

2021-04-16 15:27 UTC, Paulami30 commented on docs/tables/aws_sagemaker_notebook_instance.md
> +### List notebook instances that are not publicly available
```suggestion
### List notebook instances that are publicly available
```

2021-04-16 15:28 UTC, Paulami30 commented on docs/tables/aws_sagemaker_notebook_instance.md
> +### List notebook instances whose root access for users disabled
```suggestion
### List notebook instances which provides root access to the users
```

2021-04-16 15:29 UTC, Paulami30 commented on docs/tables/aws_sagemaker_notebook_instance.md
> +### List notebook instances whose root access for users disabled
Also make changes in the query accordingly

2021-04-16 15:35 UTC, Paulami30 requested changes
Please check for the comments

2021-04-19 08:01 UTC, Paulami30 commented on aws-test/tests/aws_sagemaker_notebook_instance/test-get-expected.json
> +]
can you check the indentation for this again?

2021-04-19 08:01 UTC, Paulami30 commented on aws-test/tests/aws_sagemaker_notebook_instance/test-turbot-expected.json
> +]
fix indentation

2021-04-19 08:11 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +				Transform:   transform.FromField("NotebookInstanceArn"),
use `arnToAkas` function here

2021-04-19 08:13 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +
remove the commented part

2021-04-19 08:15 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +			},
this is tags in the original format. why did not you convert it to turbot tags?

2021-04-19 08:15 UTC, Paulami30 commented on docs/tables/aws_sagemaker_notebook_instance.md
> +
```suggestion


```

2021-04-19 08:18 UTC, Paulami30 requested changes
Check the comments, run the integration test and update the latest log

2021-04-19 13:35 UTC, Paulami30 commented on aws-test/tests/aws_sagemaker_notebook_instance/test-turbot-expected.json
> +      "name": "{{ resourceName }}"
wrong indentation

2021-04-19 13:40 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +	instanceTags := d.HydrateItem.(*sagemaker.ListTagsOutput)
```suggestion
	data := d.HydrateItem.(*sagemaker.ListTagsOutput)
```

2021-04-19 13:40 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +	if instanceTags.Tags == nil {
```suggestion
	if data.Tags == nil {
```

2021-04-19 13:41 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +//// TRANSFORM FUNCTIONS
```suggestion
//// TRANSFORM FUNCTION
```

2021-04-19 13:41 UTC, Paulami30 commented on aws/table_aws_sagemaker_notebook_instance.go
> +
move the above function after the transform function

2021-04-20 06:35 UTC, Paulami30 approved these changes

2021-04-20 06:35 UTC, Paulami30 commented
LGTM

2021-04-20 06:57 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 20:31 UTC, cbruno10 approved these changes

2021-04-22 20:31 UTC, merged