aws_ecr_repository table not storing Public repositories. Closes #334
turbot/steampipe-plugin-aws pull request #336
Opened 2021-04-22 12:30 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/aws_ecrpublic_repository []

PRETEST: tests/aws_ecrpublic_repository

TEST: tests/aws_ecrpublic_repository
Running terraform
aws_ecrpublic_repository.named_test_resource: Creating...
aws_ecrpublic_repository.named_test_resource: Creation complete after 9s [id=turbottest67853]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = "013122550996"
aws_partition = "aws"
aws_region = "us-east-1"
registry_id = "013122550996"
resource_aka = "arn:aws:ecr-public::013122550996:repository/turbottest67853"
resource_id = "turbottest67853"
resource_name = "turbottest67853"

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "arn:aws:ecr-public::013122550996:repository/turbottest67853"
    ],
    "partition": "aws",
    "region": "us-east-1",
    "repository_name": "turbottest67853"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:ecr-public::013122550996:repository/turbottest67853"
    ],
    "repository_name": "turbottest67853",
    "title": "turbottest67853"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:ecr-public::013122550996:repository/turbottest67853",
    "partition": "aws",
    "region": "us-east-1",
    "repository_name": "turbottest67853"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "013122550996",
    "akas": [
      "arn:aws:ecr-public::013122550996:repository/turbottest67853"
    ],
    "region": "us-east-1",
    "title": "turbottest67853"
  }
]
✔ PASSED

POSTTEST: tests/aws_ecrpublic_repository

TEARDOWN: tests/aws_ecrpublic_repository

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  repository_name,
  registry_id,
  arn,
  repository_uri,
  created_at,
  region,
  account_id
from
  aws_ecrpublic_repository;
+-----------------+--------------+--------------------------------------------------+------------------------------+---------------------+-----------+--------------+
| repository_name | registry_id  | arn                                              | repository_uri               | created_at          | region    | account_id   |
+-----------------+--------------+--------------------------------------------------+------------------------------+---------------------+-----------+--------------+
| test            | 013122550996 | arn:aws:ecr-public::013122550996:repository/test | public.ecr.aws/i1f4e0n4/test | 2021-04-22 07:44:35 | us-east-1 | 013122550996 |
+-----------------+--------------+--------------------------------------------------+------------------------------+---------------------+-----------+--------------+

select
  title,
  p as principal,
  a as action,
  s ->> 'Effect' as effect,
  s -> 'Condition' as conditions
from
  aws_ecrpublic_repository,
  jsonb_array_elements(policy -> 'Statement') as s,
  jsonb_array_elements_text(s -> 'Principal' -> 'AWS') as p,
  jsonb_array_elements_text(s -> 'Action') as a
where
  s ->> 'Effect' = 'Allow'
  and a in ('*', 'ecr-public:*');
+-------+---------------------------------------------+--------------+--------+------------+
| title | principal                                   | action       | effect | conditions |
+-------+---------------------------------------------+--------------+--------+------------+
| test  | arn:aws:iam::013122550996:role/turbot/admin | ecr-public:* | Allow  | <null>     |
| test  | arn:aws:iam::013122550996:user/sourav       | ecr-public:* | Allow  | <null>     |
| test  | arn:aws:iam::013122550996:role/turbot/admin | *            | Allow  | <null>     |
| test  | arn:aws:iam::013122550996:user/sourav       | *            | Allow  | <null>     |
+-------+---------------------------------------------+--------------+--------+------------+
```
</details>

2021-04-26 08:36 UTC, Subhajit97 commented on aws/service.go
> +func EcrpublicService(ctx context.Context, d *plugin.QueryData, region string) (*ecrpublic.ECRPublic, error) {
```suggestion
func EcrPublicService(ctx context.Context, d *plugin.QueryData, region string) (*ecrpublic.ECRPublic, error) {
```

2021-04-26 08:37 UTC, Subhajit97 commented on aws/service.go
> +// EcrpublicService returns the service connection for AWS ECRPublic service
```suggestion
// EcrpublicService returns the service connection for AWS ECR Public service
```

2021-04-26 08:38 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +		Description: "AWS ECRPublic Repository",
https://docs.aws.amazon.com/AmazonECR/latest/public/public-repositories.html
```suggestion
		Description: "AWS ECR Public Repository",
```

2021-04-26 08:38 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +				Description: "The AWS account ID associated with the public registry that contains the repository",
```suggestion
				Description: "The AWS account ID associated with the public registry that contains the repository.",
```

2021-04-26 08:42 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +				Description: "A list of tags assigned to the Repository.",
```suggestion
				Description: "A list of tags assigned to the repository.",
```

2021-04-26 08:42 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +			// Standard columns for all tables
```suggestion
			// Steampipe standard columns
```

2021-04-26 08:43 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +			},
Order should be `title`, `tags` and `akas`.

2021-04-26 08:44 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +func getAwsEcrpublicRepositories(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getAwsEcrpublicRepository(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-04-26 08:46 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +	var name string
```suggestion

	var name string
```

2021-04-26 08:48 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +	return data.Repositories[0], nil
can you please add a if block to check the length of the response?

2021-04-26 08:50 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +
```suggestion

if tags == nil {
  return nil, nil
}

```

2021-04-26 08:51 UTC, Subhajit97 commented on aws-test/tests/aws_ecrpublic_repository/test-turbot-query.sql
> +where repository_name = '{{ output.resource_name.value }}';
```suggestion
where repository_name = '{{ resourceName }}';
```

2021-04-26 08:51 UTC, Subhajit97 commented on aws-test/tests/aws_ecrpublic_repository/test-notfound-query.sql
> +where repository_name = '{{ output.resourceName }}.1';
```suggestion
where repository_name = '{{ resourceName }}.1';
```

2021-04-26 08:52 UTC, Subhajit97 commented on aws-test/tests/aws_ecrpublic_repository/test-list-expected.json
> +    "repository_name": "{{ output.resource_name.value }}"
```suggestion
    "repository_name": "{{ resourceName }}"
```

2021-04-26 08:52 UTC, Subhajit97 requested changes
@bigdatasourav There are few changes required. Please see comments, thanks!

2021-04-26 16:26 UTC, khushboo9024 commented on aws-test/tests/aws_ecrpublic_repository/test-notfound-query.sql
> +from aws.aws_ecr_repository
```suggestion
from aws. aws_ecrpublic_repository
```

2021-04-27 05:26 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +		logger.Debug("getAwsEcrpublicRepositories", "ERROR", err)
```suggestion
		logger.Debug("getAwsEcrpublicRepository", "ERROR", err)
```

2021-04-27 05:27 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +	if len(data.Repositories) > 0 {
```suggestion
	if data.Repositories != nil && len(data.Repositories) > 0 {
```

2021-04-27 05:30 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +	}
Is this check required?

2021-04-27 05:31 UTC, Subhajit97 commented on aws/table_ aws_ecrpublic_repository.go
> +package aws
Fix the file name. There is an space in after `table_`

2021-04-27 05:32 UTC, Subhajit97 requested changes
@bigdatasourav There are few more changes required. Please see comments, thanks!

2021-04-27 08:35 UTC, Subhajit97 commented on aws/table_aws_ecrpublic_repository.go
> +func getAwsEcrpublicRepository(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getAwsEcrpublicRepository(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-28 09:41 UTC, Subhajit97 approved these changes
LGTM

2021-04-29 07:10 UTC, rajmohanty17 approved these changes
LGTM

2021-04-29 07:15 UTC, khushboo9024 approved these changes

2021-04-29 21:27 UTC, cbruno10 approved these changes

2021-04-29 21:29 UTC, merged