Add table aws_glue_database. closes #201
turbot/steampipe-plugin-aws pull request #337
Opened 2021-04-22 14:33 UTC by pskrbasu

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
pskrbasu@Puskars-MacBook-Pro aws-test (main) $ TF_VAR_aws_profile=redhood TF_VAR_aws_region=ap-south-1 ./tint.js tests/aws_glue_catalog_database
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_glue_catalog_database []

PRETEST: tests/aws_glue_catalog_database

TEST: tests/aws_glue_catalog_database
Running terraform
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
data.aws_region.alternate: Refreshing state...
aws_glue_catalog_database.named_test_resource: Creating...
aws_glue_catalog_database.named_test_resource: Creation complete after 0s [id=039305405804:turbottest99127]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

aws_partition = aws
aws_region = ap-south-1
resource_aka = arn:aws:glue:ap-south-1:039305405804:database/turbottest99127
resource_name = turbottest99127

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "arn:aws:glue:ap-south-1:039305405804:database/turbottest99127"
    ],
    "name": "turbottest99127",
    "title": "turbottest99127"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:glue:ap-south-1:039305405804:database/turbottest99127"
    ],
    "title": "turbottest99127"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "description": "integration testing",
    "name": "turbottest99127",
    "partition": "aws",
    "region": "ap-south-1",
    "title": "turbottest99127"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:glue:ap-south-1:039305405804:database/turbottest99127"
    ],
    "name": "turbottest99127",
    "region": "ap-south-1",
    "title": "turbottest99127"
  }
]
✔ PASSED

POSTTEST: tests/aws_glue_catalog_database

TEARDOWN: tests/aws_glue_catalog_database

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  name,
  catalog_id,
  create_time,
  description,
  location_uri
from
  aws_glue_catalog_database;
+---------+--------------+---------------------+-------------------------------+----------------+
| name    | catalog_id   | create_time         | description                   | location_uri   |
+---------+--------------+---------------------+-------------------------------+----------------+
| test_db | 453319552164 | 2021-04-22 11:09:46 | testing first steampipe table | www.turbot.com |
+---------+--------------+---------------------+-------------------------------+----------------+
> 
> select
  name,
  catalog_id,
  create_time,
  description,
  location_uri
from
  aws_glue_catalog_database
where
  catalog_id = '453319552164';
+---------+--------------+---------------------+-------------------------------+----------------+
| name    | catalog_id   | create_time         | description                   | location_uri   |
+---------+--------------+---------------------+-------------------------------+----------------+
| test_db | 453319552164 | 2021-04-22 11:09:46 | testing first steampipe table | www.turbot.com |
+---------+--------------+---------------------+-------------------------------+----------------+
> 
```
</details>

2021-04-26 09:58 UTC, khushboo9024 commented on aws-test/tests/aws_glue_catalog_database/variables.tf
> +  default = "integration-tests"
```suggestion
  default = "default"
```

2021-04-26 09:59 UTC, khushboo9024 commented on aws/plugin.go
> +			"aws_glue_catalog_database":							tableAwsGlueDatabase(ctx),
indentation is wrong.

2021-04-26 17:16 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +				Name:        "name",
`name` should be the first column.

2021-04-26 17:17 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +			},
```suggestion
			},
			
```

2021-04-26 17:18 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +				Name:        "create_table_default_permissions",
Ordering of column in not correct.

2021-04-26 17:27 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +func databaseName(item interface{}) string {
This function is not required, we have same output for list and get call.

2021-04-26 17:28 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +	// TODO put me in helper function
```suggestion
```

2021-04-26 17:28 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +
```suggestion
//// TABLE DEFINITION
```

2021-04-26 17:31 UTC, khushboo9024 commented on aws-test/tests/aws_glue_catalog_database/test-get-query.sql
> +select name, title, akas
can we query other important columns like `catalog_id` , `create_table_default_permissions`, `location_uri`, `description` in get call?

2021-04-26 17:32 UTC, khushboo9024 commented on aws-test/tests/aws_glue_catalog_database/variables.tf
> +
Remove extra line.

2021-04-26 17:33 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +			ShouldIgnoreError: isNotFoundError([]string{"InvalidInputException", "EntityNotFoundException", "InternalServiceException", "OperationTimeoutException", "EncryptionException"}),
Do we need all these not found errors ?

2021-04-26 17:34 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +	// TODO put me in helper function
```suggestion
```

2021-04-26 17:35 UTC, khushboo9024 requested changes
Please make suggested changes.

2021-04-30 11:44 UTC, Subhajit97 commented on aws/table_aws_glue_catalog_database.go
> +	name = d.KeyColumnQuals["name"].GetStringValue()
```suggestion
	name := d.KeyColumnQuals["name"].GetStringValue()
```

2021-04-30 11:45 UTC, Subhajit97 commented on aws/table_aws_glue_catalog_database.go
> +func getAwsGlueDatabase(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getAwsGlueDatabase(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-30 11:46 UTC, Subhajit97 commented on aws/table_aws_glue_catalog_database.go
> +func tableAwsGlueDatabase(_ context.Context) *plugin.Table {
```suggestion
func tableAwsGlueCatalogDatabase(_ context.Context) *plugin.Table {
```

2021-04-30 11:47 UTC, Subhajit97 commented on aws-test/tests/aws_glue_catalog_database/variables.tf
> +  default = "us-east-2"
We generally use `us-east-1` as primary region.

2021-04-30 11:48 UTC, Subhajit97 commented on aws-test/tests/aws_glue_catalog_database/test-hydrate-expected.json
> +		"title": "{{ resourceName}}"
Fix indentation

2021-05-12 06:55 UTC, khushboo9024 commented on docs/tables/aws_glue_catalog_database.md
> +  count(name)
Please add alias for this column.

2021-05-12 06:57 UTC, khushboo9024 commented on aws/table_aws_glue_catalog_database.go
> +				Description: "The time at which the metadata database was created in the catalog.",
`create_time` should be third column.

2021-05-12 08:01 UTC, khushboo9024 approved these changes
LGTM

2021-05-12 08:24 UTC, rajmohanty17 requested changes
@khushboo9024 can we achieve this in an example ?
Glue Data Catalog Encrypted With KMS Customer Master Keys

2021-05-13 05:34 UTC, pskrbasu commented
> @khushboo9024 can we achieve this in an example ?
> Glue Data Catalog Encrypted With KMS Customer Master Keys

@rajmohanty17 `Glue Data Catalog Encrypted With KMS Customer Master Keys` is related to the Data Catalog and not the database. Catalog ID is just the account ID. Databases reside inside Catalog but we can't create any new catalog, only we can encrypt it.
We can add the `AWS KMS Key ID` column in the database table which will have the data if the Catalog(Account ID) is encrypted, but for multiple databases this column will have the same KMS ID.
Is that okay?

2021-05-13 13:00 UTC, rajmohanty17 approved these changes
LGTM

2021-05-17 17:48 UTC, cbruno10 approved these changes

2021-05-17 17:48 UTC, merged