Add CloudTrail Trail table. Closes #32
turbot/steampipe-plugin-aws pull request #34
Opened 2021-02-03 14:54 UTC by Subhajit97

2021-02-05 05:21 UTC, Subhajit97 commented on docs/tables/aws_cloudtrail_trail.md
> +### List of cloud trails which stores logs in publicly accessible S3 buckets
```suggestion
### List of trails which stores logs in publicly accessible S3 buckets
```

2021-03-10 23:41 UTC, cbruno10 requested changes
@Subhajit97 I think this currently doesn't work if you have any multi-region trails. Also, it seems like multi-region trails show up in every region (we should probably just show where it was created in). In my configuration, I only have us-east-1 and us-east-2 configured:

```
> select * from aws_cloudtrail_trail;
Error: pq: rpc error: code = Unknown desc = TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-east-2:828685001623:trail/turbot-us-east-1-trail for the user: 828685001623
> select title,is_multi_region_trail,region from aws_cloudtrail_trail;
+-------------------------------------+-----------------------+-----------+
| title                               | is_multi_region_trail | region    |
+-------------------------------------+-----------------------+-----------+
| turbot-us-east-1-trail | true                  | us-east-1 |
| turbot-us-east-1-trail | true                  | us-east-2 |
+-------------------------------------+-----------------------+-----------+
```

Can you please test with this table while having at least one multi-region trail as well? And also see if we can limit multi-region trails to where they were created in?

2021-03-11 07:09 UTC, Subhajit97 commented
`List of all the trails in a region (shadow trails are not included)`
![image](https://user-images.githubusercontent.com/38218418/110748740-2bea9100-8266-11eb-8764-16e6244cbef0.png)

`Get the trail by using TrailName`
![image](https://user-images.githubusercontent.com/38218418/110749020-8b48a100-8266-11eb-9aae-b2796c33bb39.png)

`Get the trail by using TrailArn`
![image](https://user-images.githubusercontent.com/38218418/110749068-9bf91700-8266-11eb-8566-2e1e9ccca4a6.png)

** _NOTE_ ** We have configure GET call to work for both `TrailName` and `TrailArn` as `[DescribeTrails](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_DescribeTrails.html#API_DescribeTrails_RequestSyntax)` works for both.

2021-03-16 20:58 UTC, cbruno10 approved these changes

2021-03-16 20:58 UTC, merged