Getting an error as Error: NotFound: Topic does not exist, status code: 404 from aws_sns_topic_subscription table. Closes #335
turbot/steampipe-plugin-aws pull request #349
Opened 2021-04-27 09:44 UTC by visiit

…e: 404 from aws_sns_topic_subscription table. Closes #335

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_sns_topic_subscription
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_sns_topic_subscription []

PRETEST: tests/aws_sns_topic_subscription

TEST: tests/aws_sns_topic_subscription
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_sqs_queue.aws_sns_subscription: Creating...
aws_sns_topic.aws_sns_subscription: Creating...
aws_sns_topic.aws_sns_subscription: Creation complete after 4s [id=arn:aws:sns:us-east-1:986325076436:turbottest53265]
aws_sqs_queue.aws_sns_subscription: Creation complete after 4s [id=https://sqs.us-east-1.amazonaws.com/986325076436/turbottest53265]
aws_sns_topic_subscription.named_test_resource: Creating...
aws_sns_topic_subscription.named_test_resource: Creation complete after 5s [id=arn:aws:sns:us-east-1:986325076436:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
endpoint = arn:aws:sqs:us-east-1:986325076436:turbottest53265
resource_aka = arn:aws:sns:us-east-1:986325076436:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68
resource_name = turbottest53265
topic_arn = arn:aws:sns:us-east-1:986325076436:turbottest53265

Running SQL query: test-get-query.sql
[
  {
    "endpoint": "arn:aws:sqs:us-east-1:986325076436:turbottest53265",
    "protocol": "sqs",
    "topic_arn": "arn:aws:sns:us-east-1:986325076436:turbottest53265"
  }
]
✔ PASSED

Running SQL query: test-get-subscription-attributes-query.sql
[
  {
    "confirmation_was_authenticated": true,
    "delivery_policy": null,
    "effective_delivery_policy": null,
    "filter_policy": null,
    "pending_confirmation": false,
    "raw_message_delivery": false,
    "redrive_policy": null
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "endpoint": "arn:aws:sqs:us-east-1:986325076436:turbottest53265",
    "owner": "986325076436",
    "protocol": "sqs",
    "subscription_arn": "arn:aws:sns:us-east-1:986325076436:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68",
    "topic_arn": "arn:aws:sns:us-east-1:986325076436:turbottest53265"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "986325076436",
    "akas": [
      "arn:aws:sns:us-east-1:986325076436:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68"
    ],
    "partition": "aws",
    "region": "us-east-1",
    "title": "8c3017e6-f431-4c43-ad29-6ac454b68f68"
  }
]
✔ PASSED

POSTTEST: tests/aws_sns_topic_subscription

TEARDOWN: tests/aws_sns_topic_subscription

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-04-28 06:24 UTC, Subhajit97 commented
@visiit Can you please verify the `subscription_arn` column also?
If there are any subscription waiting for confirmation, AWS returns the value as `PendingConfirmation`, when perform list call.
```
> select subscription_arn, akas from aws_pikachu.aws_sns_topic_subscription where topic_arn like '%test-topic'
+---------------------+-------------------------+
| subscription_arn    | akas                    |
+---------------------+-------------------------+
| PendingConfirmation | ["PendingConfirmation"] |
+---------------------+-------------------------
```
Here is the response getting using AWS CLI
```
{
    "SubscriptionArn": "PendingConfirmation",
    "Owner": "1234567898012",
    "Protocol": "https",
    "Endpoint": "https://www.test.com",
    "TopicArn": "arn:aws:sns:us-east-2:1234567898012:test-topic"
}
```
Though the get function returns proper value

2021-04-28 06:26 UTC, Subhajit97 requested changes
@visiit I have left a comment. Can you please verify once? Thanks!

2021-04-28 06:46 UTC, visiit commented
@Subhajit97 When the status is not confirmed, subscription_id is not generated that's why in that time SubscriptionArn is coming as `PendingConfirmation`.![image](https://user-images.githubusercontent.com/55080164/116358584-7080ba80-a81b-11eb-9f23-f1c573d8fb10.png)

2021-04-28 12:37 UTC, cbruno10 commented
@johnsmyth Since subscriptions pending confirmation do not have an ID and no ARN (so we also can't call the get/hydrate functions), should we skip showing these in the table results, or is it valuable to show the pending confirmation ones but put in a placeholder for the ID/ARN?

2021-04-28 20:01 UTC, cbruno10 commented
To better handle subscriptions pending confirmation, I suggest that if `Attributes.PendingConfirmation` is `true`, then:
- Set `akas` as `[]` or `null` (@LalitTurbot - What is our default for rows with no AKAs?)
- Set `SubscriptionArn` to `null` (not sure if our transformation functions can handle that though, may need a separate function)

2021-05-03 06:49 UTC, Subhajit97 commented on aws/table_aws_sns_topic_subscription.go
> +				Transform:   transform.FromField("Attributes.SubscriptionArn").Transform(subscriptionArnNotconformStatus),
```suggestion
				Transform:   transform.FromField("Attributes.SubscriptionArn").Transform(subscriptionArnNotconfirmStatus),
```

2021-05-03 06:50 UTC, Subhajit97 commented on aws/table_aws_sns_topic_subscription.go
> +		return "null", nil
```suggestion
		return nil, nil
```

2021-05-03 09:44 UTC, Subhajit97 commented on aws/table_aws_sns_topic_subscription.go
> +				Transform:   transform.FromField("Attributes.SubscriptionArn").Transform(subscriptionArnNotconformStatus),
@visiit Can we use `NullIfEqual()` transform for this?

2021-05-03 10:32 UTC, Subhajit97 approved these changes
LGTM

2021-05-04 17:45 UTC, cbruno10 approved these changes

2021-05-04 17:45 UTC, merged