Add a column to store "Enable automatic backups" for EFS file system in 'aws_efs_file_system' table. Closes #303
turbot/steampipe-plugin-aws pull request #351
Opened 2021-04-27 11:34 UTC by visiit

…in 'aws_efs_file_system' table. Closes #303

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_efs_file_system
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_efs_file_system []

PRETEST: tests/aws_efs_file_system

TEST: tests/aws_efs_file_system
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_efs_file_system.named_test_resource: Creating...
aws_efs_file_system.named_test_resource: Creation complete after 8s [id=fs-078753b3]
data.template_file.resource_aka: Refreshing state...
aws_efs_file_system_policy.efs_file_system_policy: Creating...
aws_efs_file_system_policy.efs_file_system_policy: Creation complete after 3s [id=fs-078753b3]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = arn:aws:elasticfilesystem:us-east-1:986325076436:file-system/fs-078753b3
resource_id = fs-078753b3
resource_name = turbottest22148

Running SQL query: test-get-query.sql
[
  {
    "encrypted": true,
    "file_system_id": "fs-078753b3",
    "performance_mode": "maxIO",
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest22148"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:elasticfilesystem:us-east-1:986325076436:file-system/fs-078753b3"
    ],
    "file_system_id": "fs-078753b3",
    "policy": {
      "Id": "test_policy",
      "Statement": [
        {
          "Action": [
            "elasticfilesystem:ClientMount",
            "elasticfilesystem:ClientWrite"
          ],
          "Condition": {
            "Bool": {
              "aws:SecureTransport": "true"
            }
          },
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Resource": "arn:aws:elasticfilesystem:us-east-1:986325076436:file-system/fs-078753b3",
          "Sid": "__default_policy_ID"
        }
      ],
      "Version": "2012-10-17"
    },
    "tags": {
      "name": "turbottest22148"
    },
    "title": "fs-078753b3"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:elasticfilesystem:us-east-1:986325076436:file-system/fs-078753b3"
    ],
    "automatic_backup": "disabled",
    "encrypted": true,
    "file_system_id": "fs-078753b3",
    "performance_mode": "maxIO",
    "tags": {
      "name": "turbottest22148"
    },
    "title": "fs-078753b3"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_efs_file_system

TEARDOWN: tests/aws_efs_file_system

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- Basic info

select
  name,
  file_system_id,
  owner_id,
  automatic_backup,
  creation_token,
  creation_time,
  life_cycle_state,
  number_of_mount_targets,
  performance_mode,
  throughput_mode
from
  aws_efs_file_system;

+----------------------------+----------------+--------------+------------------+---------------------------------------------------+---------------------+------------------+-------------------------+------------------+-----------------+
| name                       | file_system_id | owner_id     | automatic_backup | creation_token                                    | creation_time       | life_cycle_state | number_of_mount_targets | performance_mode | throughput_mode |
+----------------------------+----------------+--------------+------------------+---------------------------------------------------+---------------------+------------------+-------------------------+------------------+-----------------+
| test-file-syastem          | fs-3423f680    | 986325076436 | enabled          | quickCreated-8e2630ac-fd8f-4bdf-8ce0-11e5dc26f92e | 2021-04-27 07:30:45 | available        | 6                       | generalPurpose   | bursting        |
| test-steampipe-file-system | fs-c0914574    | 986325076436 | disabled         | quickCreated-e6fc2536-2111-47ef-ad49-e3b085316e85 | 2021-04-27 10:46:06 | available        | 6                       | generalPurpose   | bursting        |
+----------------------------+----------------+--------------+------------------+---------------------------------------------------+---------------------+------------------+-------------------------+------------------+-----------------+
```
</details>

2021-04-28 09:10 UTC, Subhajit97 commented on aws/table_aws_efs_file_system.go
> +func getAutomaticBackupValue(_ context.Context, d *transform.TransformData) (interface{}, error) {
@visiit We generally don't use `get` prefix for `Transform Functions`.

2021-04-28 09:12 UTC, Subhajit97 commented on aws/table_aws_efs_file_system.go
> +	}
Do we need this block, as the functions returns `disabled` at the end?

2021-04-28 09:14 UTC, Subhajit97 commented on docs/tables/aws_efs_file_system.md
> +  automatic_backup,
Will be good if we add a separate example to check the `Enable automatic backups`.

2021-04-28 09:17 UTC, Subhajit97 requested changes
@visiit I have left some suggestions. Please see comments, thanks!

2021-04-30 15:35 UTC, Subhajit97 approved these changes
LGTM

2021-05-04 17:49 UTC, cbruno10 commented on aws/table_aws_efs_file_system.go
> +				Name:        "automatic_backup",
```suggestion
				Name:        "automatic_backups",
```

I think this column name is a bit better, as the feature is usually described as `automatic backups`.

2021-05-04 17:49 UTC, cbruno10 commented on aws/table_aws_efs_file_system.go
> +func automaticBackupValue(_ context.Context, d *transform.TransformData) (interface{}, error) {
```suggestion
func automaticBackupsValue(_ context.Context, d *transform.TransformData) (interface{}, error) {
```

2021-05-04 17:50 UTC, cbruno10 commented on docs/tables/aws_efs_file_system.md
> +### List file systems with automatic backup feature enabled
```suggestion
### List file systems with automatic backups enabled
```

2021-05-04 17:50 UTC, cbruno10 requested changes
Please see comments

2021-05-05 13:33 UTC, cbruno10 approved these changes

2021-05-05 13:34 UTC, merged