Add table aws_appautoscaling_target. closes #329
turbot/steampipe-plugin-aws pull request #353
Opened 2021-04-27 14:37 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/aws_appautoscaling_target []

PRETEST: tests/aws_appautoscaling_target

TEST: tests/aws_appautoscaling_target
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_dynamodb_table.example: Creating...
aws_dynamodb_table.example: Still creating... [10s elapsed]
aws_dynamodb_table.example: Creation complete after 18s [id=turbottest22904]
aws_appautoscaling_target.named_test_resource: Creating...
aws_appautoscaling_target.named_test_resource: Creation complete after 3s [id=table/turbottest22904]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_id = table/turbottest22904
resource_name = turbottest22904

Running SQL query: test-get-query.sql
[
  {
    "partition": "aws",
    "region": "us-east-1",
    "resource_id": "table/turbottest22904"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "partition": "aws",
    "region": "us-east-1",
    "resource_id": "table/turbottest22904"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "986325076436",
    "region": "us-east-1",
    "title": "table/turbottest22904"
  }
]
✔ PASSED

POSTTEST: tests/aws_appautoscaling_target

TEARDOWN: tests/aws_appautoscaling_target

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  service_namespace,
  scalable_dimension,
  resource_id,
  creation_time
from
  aws_appautoscaling_target
where
  service_namespace = 'dynamodb';
```
```
+-------------------+----------------------------------+------------------------------------------+---------------------+
| service_namespace | scalable_dimension               | resource_id                              | creation_time       |
+-------------------+----------------------------------+------------------------------------------+---------------------+
| dynamodb          | dynamodb:table:ReadCapacityUnits | table/turbot-test-20200155-create-update | 2021-04-27 08:11:37 |
+-------------------+----------------------------------+------------------------------------------+---------------------+
```

### Check whether autoscaling is enabled of both read-write capacity

```sql
select
  resource_id,
  scalable_dimension
from
  aws_appautoscaling_target
where
  service_namespace = 'dynamodb'
  and scalable_dimension = 'dynamodb:table:ReadCapacityUnits'
  or 'scalable_dimension' = 'dynamodb:table:WriteCapacityUnits';
```
```
+------------------------------------------+----------------------------------+
| resource_id                              | scalable_dimension               |
+------------------------------------------+----------------------------------+
| table/turbot-test-20200155-create-update | dynamodb:table:ReadCapacityUnits |
+------------------------------------------+----------------------------------+
```

2021-04-30 06:28 UTC, Subhajit97 commented on aws/service.go
> +// ApplicationAutoScalingService returns the service connection for AWS ApplicationAutoScaling service
```suggestion
// ApplicationAutoScalingService returns the service connection for AWS Application Auto Scaling service
```

2021-04-30 06:29 UTC, Subhajit97 commented on aws/table_ aws_appautoscaling_target.go
> +		Description: "AWS ApplicationAutoScaling Target",
```suggestion
		Description: "AWS Application Auto Scaling Target",
```

2021-04-30 06:31 UTC, Subhajit97 commented on aws/table_ aws_appautoscaling_target.go
> +package aws
Fix file name, there is a whitespace after `table_`.

2021-04-30 06:34 UTC, Subhajit97 commented on aws/table_ aws_appautoscaling_target.go
> +	ID := d.KeyColumnQuals["resource_id"].GetStringValue()
don't use uppercase when defining any local variables, use lowerCamelCase instead. 
```suggestion
	id := d.KeyColumnQuals["resource_id"].GetStringValue()
```

2021-04-30 06:35 UTC, Subhajit97 commented on aws/table_ aws_appautoscaling_target.go
> +	if len(op.ScalableTargets) > 0 {
```suggestion
	if op.ScalableTargets != nil && len(op.ScalableTargets) > 0 {
```

2021-04-30 06:36 UTC, Subhajit97 commented on docs/tables/aws_appautoscaling_target.md
> +  or 'scalable_dimension' = 'dynamodb:table:WriteCapacityUnits';
```suggestion
  or scalable_dimension = 'dynamodb:table:WriteCapacityUnits';
```

2021-04-30 06:42 UTC, Subhajit97 requested changes
@Priyanka585464 There are few changes required. Please see comments, thanks!

2021-04-30 07:56 UTC, Subhajit97 approved these changes
LGTM

2021-05-03 08:00 UTC, rajmohanty17 requested changes
@Priyanka585464 can we identify below 

1. Identify and list empty AWS Auto Scaling Groups (ASGs).
2. Ensure that logging is enabled in the ASGs
3. Ensure AWS Auto Scaling Groups utilize multiple Availability Zones to improve environment reliability.

2021-05-04 08:06 UTC, Priyanka585464 commented
@rajmohanty17 
The query examples you have suggested I think those are related to autoscaling group resource maybe .The response what i am getting from get and list call , i am afraid that we can form these queries out of those response:
```
[
 {
 "account_id": "986325076436",
 "creation_time": "2021-04-27 08:11:37",
 "max_capacity": 100,
 "min_capacity": 5,
 "partition": "aws",
 "region": "us-east-1",
 "resource_id": "table/turbot-test-20200155-create-update",
 "role_arn": null,
 "scalable_dimension": "dynamodb:table:ReadCapacityUnits",
 "service_namespace": "dynamodb",
 "suspended_state": {
  "DynamicScalingInSuspended": false,
  "DynamicScalingOutSuspended": false,
  "ScheduledScalingSuspended": false
 },
 "title": "table/turbot-test-20200155-create-update"
 }
]
```
If you have any additional information regarding the suggested queries, please let me know.

2021-05-04 08:29 UTC, rajmohanty17 commented
For the time being let's proceed with it, will revisit later as per requirement.

2021-05-04 08:29 UTC, rajmohanty17 approved these changes
LGTM

2021-05-06 20:11 UTC, cbruno10 approved these changes

2021-05-06 20:11 UTC, merged