Add table aws_dms_replication_instance. closes #298
turbot/steampipe-plugin-aws pull request #357
Opened 2021-04-30 09:52 UTC by sayan133

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-05-04 11:10 UTC, Subhajit97 commented on aws/service.go
> +		return nil, fmt.Errorf("region must be passed DmsService")
```suggestion
		return nil, fmt.Errorf("region must be passed DatabaseMigrationService")
```

2021-05-04 11:12 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +				Description: "A list of tags currently associated with the DMS Replication Instance.",
```suggestion
				Description: "A list of tags currently associated with the replication instance.",
```

2021-05-04 11:12 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +			// Standard columns
```suggestion
			// Steampipe standard columns
```

2021-05-04 11:13 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +
```suggestion
```

2021-05-04 11:13 UTC, Subhajit97 commented on aws/service.go
> +	serviceCacheKey := fmt.Sprintf("dms-%s", region)
```suggestion
	serviceCacheKey := fmt.Sprintf("databasemigrationservice-%s", region)
```

2021-05-04 11:14 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +func getDmsReplicationInstance(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDmsReplicationInstance(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-05-04 11:16 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +	replicationInstanceArn := *h.Item.(*databasemigrationservice.ReplicationInstance).ReplicationInstanceArn
```suggestion
	replicationInstanceArn := h.Item.(*databasemigrationservice.ReplicationInstance).ReplicationInstanceArn
```

2021-05-04 11:16 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +		ResourceArn: &replicationInstanceArn,
```suggestion
		ResourceArn: replicationInstanceArn,
```

2021-05-04 11:18 UTC, Subhajit97 commented on aws/table_aws_dms_replication_instance.go
> +	}
Do we need this block, as the function already returns `nil` at the end?

2021-05-04 11:34 UTC, Subhajit97 requested changes
@sayan133 There are few changes required. Please see comments, thanks!

2021-05-06 14:49 UTC, Subhajit97 approved these changes
LGTM

2021-05-10 20:06 UTC, cbruno10 approved these changes

2021-05-10 20:06 UTC, merged