Add table aws_kinesisanalyticsv2_application. Closes #218
turbot/steampipe-plugin-aws pull request #358
Opened 2021-04-30 10:31 UTC by visiit

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_kinesisanalyticsv2_application
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined
SETUP: tests/aws_kinesisanalyticsv2_application []
PRETEST: tests/aws_kinesisanalyticsv2_application
TEST: tests/aws_kinesisanalyticsv2_application
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.primary: Refreshing state...
aws_iam_role.named_test_resource: Creating...
aws_iam_role.named_test_resource: Still creating... [10s elapsed]
aws_iam_role.named_test_resource: Creation complete after 11s [id=turbottest46291]
aws_kinesisanalyticsv2_application.named_test_resource: Creating...
aws_kinesisanalyticsv2_application.named_test_resource: Creation complete after 8s [id=arn:aws:kinesisanalytics:us-east-1:986325076436:application/turbottest46291]
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Outputs:
account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:kinesisanalytics:us-east-1:986325076436:application/turbottest46291
resource_creation_time = 2021-04-28T14:00:38Z
resource_id = arn:aws:kinesisanalytics:us-east-1:986325076436:application/turbottest46291
resource_name = turbottest46291
version = 1
Running SQL query: test-get-query.sql
[
  {
    "account_id": "986325076436",
    "akas": [
      "arn:aws:kinesisanalytics:us-east-1:986323036436:application/turbottest46291"
    ],
    "application_name": "turbottest46291",
    "application_version_id": 1,
    "partition": "aws",
    "runtime_environment": "SQL-1_0",
    "service_execution_role": "arn:aws:iam::986323036436:role/turbottest46291",
    "title": "turbottest46291"
  }
]
✔ PASSED
Running SQL query: test-hydrate-query.sql
[
  {
    "application_description": null,
    "cloud_watch_logging_option_descriptions": null,
    "service_execution_role": "arn:aws:iam::986323036436:role/turbottest46291",
    "tags_src": [
      {
        "Key": "Name",
        "Value": "turbottest46291"
      }
    ]
  }
]
✔ PASSED
Running SQL query: test-list-query.sql
[
  {
    "application_arn": "arn:aws:kinesisanalytics:us-east-1:986323036436:application/turbottest46291",
    "application_name": "turbottest46291",
    "application_status": "READY",
    "application_version_id": 1
  }
]
✔ PASSED
Running SQL query: test-notfound-query.sql
null
✔ PASSED
Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:kinesisanalytics:us-east-1:986323036436:application/turbottest46291"
    ],
    "tags": {
      "Name": "turbottest46291"
    },
    "title": "turbottest46291"
  }
]
✔ PASSED
POSTTEST: tests/aws_kinesisanalyticsv2_application
TEARDOWN: tests/aws_kinesisanalyticsv2_application
SUMMARY:
1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- Basic info

select
  application_name,
  application_arn,
  application_version_id,
  application_status,
  application_description,
  service_execution_role,
  runtime_environment
from
  aws_kinesisanalyticsv2_application;

+----------------------------+----------------------------------------------------------------------------------------+------------------------+--------------------+-------------------------+------------------------+---------------------+
| application_name           | application_arn                                                                        | application_version_id | application_status | application_description | service_execution_role | runtime_environment |
+----------------------------+----------------------------------------------------------------------------------------+------------------------+--------------------+-------------------------+------------------------+---------------------+
| test-steampipe-application | arn:aws:kinesisanalytics:us-east-1:986325076436:application/test-steampipe-application | 2                      | RUNNING            | testing steampipe query | <null>                 | SQL-1_0             |
+----------------------------+----------------------------------------------------------------------------------------+------------------------+--------------------+-------------------------+------------------------+---------------------+

- List updated application

select
  application_name,
  application_version_id,
  application_arn,
  application_status
from
  aws_kinesisanalyticsv2_application
where
  application_version_id > 1;

+----------------------------+------------------------+----------------------------------------------------------------------------------------+--------------------+
| application_name           | application_version_id | application_arn                                                                        | application_status |
+----------------------------+------------------------+----------------------------------------------------------------------------------------+--------------------+
| test-steampipe-application | 2                      | arn:aws:kinesisanalytics:us-east-1:986325076436:application/test-steampipe-application | RUNNING            |
+----------------------------+------------------------+----------------------------------------------------------------------------------------+--------------------+

- List application runtime environment as SQL

select
  application_name,
  runtime_environment,
  application_arn,
  application_status
from
  aws_kinesisanalyticsv2_application
where
  runtime_environment = 'SQL-1_0';

+----------------------------+---------------------+----------------------------------------------------------------------------------------+--------------------+
| application_name           | runtime_environment | application_arn                                                                        | application_status |
+----------------------------+---------------------+----------------------------------------------------------------------------------------+--------------------+
| test-steampipe-application | SQL-1_0             | arn:aws:kinesisanalytics:us-east-1:986325076436:application/test-steampipe-application | RUNNING            |
+----------------------------+---------------------+----------------------------------------------------------------------------------------+--------------------+

```
</details>

2021-05-07 09:13 UTC, Subhajit97 commented on aws/plugin.go
> +			"aws_kinesisanalyticsv2_application":     tableAwsKinesisAnalyticsV2Application(ctx),
Sort the list

2021-05-07 09:14 UTC, Subhajit97 commented on aws/service.go
> +// KinesisAnalyticsV2Service returns the service connection for AWS Kinesis Analytics V2 service
Is `Kinesis Analytics V2` is a separate word, or it should be `Kinesis Analyticsv2`?

2021-05-07 09:15 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_TIMESTAMP,
```

2021-05-07 09:15 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_TIMESTAMP,
```

2021-05-07 09:18 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +	}
Do we need this block?

2021-05-07 09:18 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +	plugin.Logger(ctx).Trace("route53resolverTagListToTurbotTags")
```suggestion
	plugin.Logger(ctx).Trace("kinesisAnalyticsV2ApplicationTagListToTurbotTags")
```

2021-05-07 09:19 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +	tagList := d.Value.([]*kinesisanalyticsv2.Tag)
```suggestion
	tagList := d.HydrateItem.([]*kinesisanalyticsv2.Tag)
```

2021-05-07 09:20 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +
```suggestion

if tagList == nil {
  return nil, nil
}

```

2021-05-07 09:21 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +func getApplicationArn(item interface{}) *string {
Don't use `get` prefix in function name other than hydrate functions.
```suggestion
func applicationArn(item interface{}) *string {
```

2021-05-07 09:22 UTC, Subhajit97 requested changes
@visiit There are few changes required. Please see comments, thanks!

2021-05-21 05:32 UTC, Subhajit97 commented on aws-test/tests/aws_kinesisanalyticsv2_application/test-get-expected.json
> +    "service_execution_role": "arn:aws:iam::986325076436:role/{{ resourceName }}",
Don't hardcode the account id
```suggestion
    "service_execution_role": "arn:aws:iam::{{ output.account_id.value }}:role/{{ resourceName }}",
```

2021-05-21 05:33 UTC, Subhajit97 commented on aws-test/tests/aws_kinesisanalyticsv2_application/test-hydrate-expected.json
> +    "service_execution_role": "arn:aws:iam::986325076436:role/{{ resourceName }}",
Don't hardcode the account id

2021-05-21 05:35 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +			// Standard columns for all tables
```suggestion
			// Steampipe standard columns
```

2021-05-21 05:39 UTC, Subhajit97 commented on aws/table_aws_kinesisanalyticsv2_application.go
> +	}
Can we update this block to add check for nil first?

2021-05-21 05:40 UTC, Subhajit97 requested changes
@visiit There are few more changes required, otherwise it looks good. Please see comments, thanks!

2021-05-24 14:40 UTC, Subhajit97 approved these changes
LGTM

2021-05-24 14:51 UTC, rajmohanty17 approved these changes
LGTM

2021-05-25 03:14 UTC, cbruno10 approved these changes

2021-05-25 03:15 UTC, merged