Add table_aws_route53_domain. closes #59
turbot/steampipe-plugin-aws pull request #360
Opened 2021-04-30 12:46 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  name,
  auto_renew,
  expiry
from
  aws_route53_domains;
```
```
+------------------+------------+---------------------+
| name             | auto_renew | expiry              |
+------------------+------------+---------------------+
| priyankatest.com | true       | 2022-04-29 09:36:51 |
+------------------+------------+---------------------+
```
### List Route53 domain names are renewed before their expiration.

```sql
select
  name,
  auto_renew,
  expiry
from
  aws_route53_domains
where
  auto_renew = 'true';
```

### List Route53 domain names are renewed before Expiry 7 Days

```sql
select
  name,
  auto_renew,
  expiry
from
  aws_route53_domains
where
  expiry <= (expiry - interval '7' day);
```

### Check your domain names have the Transfer Lock feature enabled in order to keep them secure.

```sql
select
  name,
  expiry
from
  aws_route53_domains
where
  transfer_lock = 'true';
```
```
</details>

2021-05-04 10:49 UTC, Subhajit97 commented on aws/table_aws_route53_domains.go
> +				Description: "A list of tags assigned to the parameter.",
```suggestion
				Description: "A list of tags assigned to the resource.",
```

2021-05-04 10:52 UTC, Subhajit97 commented on aws/service.go
> +	serviceCacheKey := fmt.Sprintf("route53domain-%s", region)
Is the service regional?

2021-05-04 10:58 UTC, Subhajit97 commented on aws/table_aws_route53_domains.go
> +	data, err := svc.ListDomains(params)
Can we use `GetDomainDetail` API for GET?
https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_GetDomainDetail.html

2021-05-04 11:00 UTC, Subhajit97 commented on aws/table_aws_route53_domains.go
> +	params := &route53domains.ListDomainsInput{}
Don't we need any filter for GET call?

2021-05-04 11:05 UTC, Subhajit97 commented on aws/table_aws_route53_domains.go
> +	aka := "arn:" + commonColumnData.Partition + ":route53domains:" + ":" + commonColumnData.AccountId
Can we also include `domainName` in ARN to make it unique?

2021-05-04 11:05 UTC, Subhajit97 commented on aws/table_aws_route53_domains.go
> +//// TRANSFORM FUNCTION
```suggestion
//// TRANSFORM FUNCTIONS
```

2021-05-04 11:07 UTC, Subhajit97 requested changes
@Priyanka585464 I have added some suggestions. Please see comments, thanks!

2021-05-21 09:47 UTC, Subhajit97 approved these changes
LGTM

2021-05-24 15:24 UTC, rajmohanty17 requested changes
Can we have DNSSEC setting from this table ?
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-configure-dnssec.html

2021-05-25 11:12 UTC, Subhajit97 commented
> Can we have DNSSEC setting from this table ?
> https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-configure-dnssec.html


@rajmohanty17 , currently API doesn't return any details about DNSSEC configuration. There is a property that indicated the DNSSEC configuration (https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_GetDomainDetail.html#Route53Domains-domains_GetDomainDetail-response-DnsSec), but it always return `null`.

2021-05-28 11:39 UTC, Subhajit97 commented on aws/plugin.go
> +=======
@Priyanka585464 I think file is not properly rebased. Please verify again.
```suggestion
```

2021-05-28 11:40 UTC, Subhajit97 requested changes
@Priyanka585464 Please rebase the branch.

2021-06-04 15:23 UTC, Subhajit97 approved these changes
LGTM

2021-06-21 12:30 UTC, rajmohanty17 approved these changes
LGTM

2021-06-21 21:18 UTC, cbruno10 approved these changes

2021-06-21 21:19 UTC, merged