Getting an error from aws_sagemaker_notebook_instance table.hydrate call listAwsSageMakerNotebookInstanceTags failed with panic interface conversion. closes #364
turbot/steampipe-plugin-aws pull request #372
Opened 2021-05-05 10:24 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
N/A
```
</details>

2021-05-05 15:02 UTC, Subhajit97 commented on aws/table_aws_sagemaker_notebook_instance.go
> +	}
Can we add a separate function for this?
also, do we need the following check for GET call?
https://github.com/turbot/steampipe-plugin-aws/pull/372/files#diff-2ceeebe3d446a630c976a1a76ab24829e58568b0645e3ae8e4aaa5390a19e234R214-R219

2021-05-07 08:51 UTC, Subhajit97 commented on aws/table_aws_sagemaker_notebook_instance.go
> +func notebookInstanceArn(item interface{}) string {
```suggestion
func notebookInstanceARN(item interface{}) string {
```

2021-05-07 08:54 UTC, Subhajit97 commented on aws/table_aws_sagemaker_notebook_instance.go
>  	if data.Tags == nil {
Do we need this block, as we returning nil at the end?
https://github.com/turbot/steampipe-plugin-aws/blob/f2b280097bc5e11414422ec75eea864f740c9eaa/aws/table_aws_sagemaker_notebook_instance.go#L281-L283

2021-05-07 08:55 UTC, Subhajit97 requested changes
@Priyanka585464 There are few changes required, otherwise it looks good. Please see comments, thanks!

2021-05-07 10:30 UTC, Subhajit97 approved these changes
LGTM

2021-05-10 19:59 UTC, cbruno10 requested changes
Please see comment

2021-05-10 19:59 UTC, cbruno10 commented on aws-test/tests/aws_sagemaker_notebook_instance/test-notfound-query.sql
> +where name = '{{ resourceName }}3p';
@Priyanka585464 Why does this resource name have 3p appended on?

2021-06-14 14:57 UTC, cbruno10 approved these changes

2021-06-14 14:59 UTC, merged