Add table aws_ec2_settings. closes #386
turbot/steampipe-plugin-aws pull request #403
Opened 2021-05-13 07:35 UTC by pskrbasu

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
pskrbasu@Puskars-MacBook-Pro aws-test (main) $ TF_VAR_aws_profile=redhood TF_VAR_aws_region=us-east-2 ./tint.js tests/aws_ec2_settings
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_ec2_settings []

PRETEST: tests/aws_ec2_settings

TEST: tests/aws_ec2_settings
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_ebs_encryption_by_default.named_test_resource: Creating...
aws_kms_key.named_test_resource: Creating...
aws_ebs_encryption_by_default.named_test_resource: Creation complete after 3s [id=terraform-20210513062933461700000001]
aws_kms_key.named_test_resource: Creation complete after 6s [id=6f79c99e-ce8d-4b31-a75d-7113a3a69456]
aws_ebs_default_kms_key.named_test_resource: Creating...
aws_ebs_default_kms_key.named_test_resource: Creation complete after 2s [id=arn:aws:kms:us-east-2:453319552164:key/6f79c99e-ce8d-4b31-a75d-7113a3a69456]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

aws_account = 453319552164
aws_partition = aws
aws_region = us-east-2
resource_aka = arn:aws:kms:us-east-2:453319552164:key/6f79c99e-ce8d-4b31-a75d-7113a3a69456

Running SQL query: test-get-query.sql
[
  {
    "default_ebs_encryption_enabled": true,
    "default_ebs_encryption_key": "arn:aws:kms:us-east-2:453319552164:key/6f79c99e-ce8d-4b31-a75d-7113a3a69456",
    "region": "us-east-2",
    "title": "EC2 Settings"
  }
]
✔ PASSED

POSTTEST: tests/aws_ec2_settings

TEARDOWN: tests/aws_ec2_settings

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  default_ebs_encryption_enabled,
  default_ebs_encryption_key,
  title,
  region
from
  aws_ec2_settings;
+--------------------------------+------------------------------------------------------------------------------+--------------+----------------+
| default_ebs_encryption_enabled | default_ebs_encryption_key                                                   | title        | region         |
+--------------------------------+------------------------------------------------------------------------------+--------------+----------------+
| false                          | alias/aws/ebs                                                                | EC2 Settings | af-south-1     |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-south-1     |
| false                          | alias/aws/ebs                                                                | EC2 Settings | me-south-1     |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-east-1      |
| true                           | arn:aws:kms:ap-south-1:453319552164:key/24213245-62a4-40de-8790-2463a8e9550b | EC2 Settings | ap-south-1     |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-southeast-1 |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-central-1   |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-west-3      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-northeast-3 |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-west-2      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-northeast-2 |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-north-1     |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-northeast-1 |
| false                          | arn:aws:kms:us-east-2:453319552164:key/8dddf7e5-dd9c-4ae4-91c9-2aa928cce178  | EC2 Settings | us-east-2      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ca-central-1   |
| false                          | alias/aws/ebs                                                                | EC2 Settings | us-west-1      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | ap-southeast-2 |
| false                          | alias/aws/ebs                                                                | EC2 Settings | us-west-2      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | eu-west-1      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | us-east-1      |
| false                          | alias/aws/ebs                                                                | EC2 Settings | sa-east-1      |
+--------------------------------+------------------------------------------------------------------------------+--------------+----------------+
> select
  default_ebs_encryption_enabled,
  default_ebs_encryption_key,
  title,
  region
from
  aws_ec2_settings
where
  region='ap-south-1';
+--------------------------------+------------------------------------------------------------------------------+--------------+------------+
| default_ebs_encryption_enabled | default_ebs_encryption_key                                                   | title        | region     |
+--------------------------------+------------------------------------------------------------------------------+--------------+------------+
| true                           | arn:aws:kms:ap-south-1:453319552164:key/24213245-62a4-40de-8790-2463a8e9550b | EC2 Settings | ap-south-1 |
+--------------------------------+------------------------------------------------------------------------------+--------------+------------+
> select
  region,
  default_ebs_encryption_enabled,
  default_ebs_encryption_key
from
  aws_ec2_settings
where
  default_ebs_encryption_enabled='true';
+------------+--------------------------------+------------------------------------------------------------------------------+
| region     | default_ebs_encryption_enabled | default_ebs_encryption_key                                                   |
+------------+--------------------------------+------------------------------------------------------------------------------+
| ap-south-1 | true                           | arn:aws:kms:ap-south-1:453319552164:key/24213245-62a4-40de-8790-2463a8e9550b |
+------------+--------------------------------+------------------------------------------------------------------------------+
```
</details>

2021-05-17 05:40 UTC, Subhajit97 commented on docs/tables/aws_ec2_settings.md
> +  region='ap-south-1';
```suggestion
  region = 'ap-south-1';
```

2021-05-17 05:41 UTC, Subhajit97 commented on docs/tables/aws_ec2_settings.md
> +  default_ebs_encryption_enabled='true';
```suggestion
  default_ebs_encryption_enabled;
```

2021-05-21 12:21 UTC, Subhajit97 approved these changes
LGTM

2021-05-27 07:38 UTC, rajmohanty17 approved these changes
LGTM

2021-06-02 19:05 UTC, cbruno10 requested changes
Please see comments

2021-06-02 19:05 UTC, cbruno10 commented on aws/table_aws_ec2_settings.go
> +				Transform:   transform.FromConstant("EC2 Settings"),
To better differentiate which row is from which region, are we able to change this to `<region> EC2 Settings`?

2021-06-09 07:44 UTC, Subhajit97 commented
+--------------------------------+-----------------------------------------------------------------------------+-------------------------+-----------+------------+--------------+
| default_ebs_encryption_enabled | default_ebs_encryption_key                                                  | title                   | partition | region     | account_id   |
+--------------------------------+-----------------------------------------------------------------------------+-------------------------+-----------+------------+--------------+
| false                          | alias/aws/ebs                                                               | us-east-2 EC2 Settings  | aws       | us-east-2  | 123456789012 |
| false                          | alias/aws/ebs                                                               | af-south-1 EC2 Settings | aws       | af-south-1 | 123456789012 |
| false                          | arn:aws:kms:us-east-1:123456789012:key/47dc93a0-ca41-46b2-96bd-08980fa0ed7c | us-east-1 EC2 Settings  | aws       | us-east-1  | 123456789012 |
+--------------------------------+-----------------------------------------------------------------------------+-------------------------+-----------+------------+--------------+

2021-06-09 12:14 UTC, rajmohanty17 approved these changes
LGTM

2021-06-09 13:22 UTC, cbruno10 requested changes
Some filenames still have the old name (`aws_ec2_settings` instead of `aws_ec2_regional_settings`), can you please update those?

2021-06-09 13:38 UTC, cbruno10 approved these changes

2021-06-09 13:38 UTC, merged