Add 'arn' column to aws_account table. Closes #414
turbot/steampipe-plugin-aws pull request #418
Opened 2021-05-19 08:10 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-05-21 05:59 UTC, Subhajit97 commented on aws/table_aws_account.go
> +func accountArn(ctx context.Context, d *transform.TransformData) (interface{}, error) {
```suggestion
func accountARN(ctx context.Context, d *transform.TransformData) (interface{}, error) {
```

2021-05-21 06:01 UTC, Subhajit97 commented on aws/table_aws_account.go
> +func accountArn(ctx context.Context, d *transform.TransformData) (interface{}, error) {
No need to add new function for `arn`. Modify the `akas` function

2021-05-21 06:03 UTC, Subhajit97 requested changes
@rajeshbal65 There are some changes required. Please see comments, thanks!

2021-05-23 06:10 UTC, Subhajit97 commented on aws/table_aws_account.go
> +				Transform:   transform.FromP(accountDataToAkas, "ARN"),
Is there any reason to use `FromP`?
You can update `accountDataToAkas` to return the `arn`, and use `EnsureStringArray` transform to form the `akas`

2021-05-23 06:12 UTC, Subhajit97 requested changes
@rajeshbal65 Can Can you please rename `accountDataToAkas` to `accountARN`.

2021-05-23 07:15 UTC, Subhajit97 approved these changes
LGTM

2021-05-25 03:11 UTC, cbruno10 approved these changes

2021-05-25 03:11 UTC, merged