Add arn column in aws_api_gateway_stage table. Closes #440
turbot/steampipe-plugin-aws pull request #447
Opened 2021-05-28 11:57 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-05-28 15:02 UTC, khushboo9024 commented on aws/table_aws_api_gateway_stage.go
> +func getAPIGatewayStageArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getAPIGatewayStageArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
```suggestion
func getAPIGatewayStageARN(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-05-28 15:06 UTC, khushboo9024 requested changes
Add `arn` column in example query as well .

2021-06-14 12:43 UTC, khushboo9024 approved these changes

2021-06-14 21:52 UTC, cbruno10 approved these changes

2021-06-14 21:53 UTC, merged