Add table aws_auditmanager_evidence. Closes #401
turbot/steampipe-plugin-aws pull request #450
Opened 2021-05-28 13:23 UTC by visiit

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- Basic info

select
  id,
  arn,
  evidence_folder_id,
  evidence_by_type,
  iam_id,
  control_set_id
from
  aws_auditmanager_evidence;

| id                                   | arn                                                                                       | evidence_folder_id                   | evidence_by_type   | iam_id                                                                                       | control_set_id                                                                                        |
+--------------------------------------+-------------------------------------------------------------------------------------------+--------------------------------------+--------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| 4d35a0ed-ec67-3022-adf4-ad663c0bfa2f | arn:aws:auditmanager:us-east-1:986325076436:evidence/4d35a0ed-ec67-3022-adf4-ad663c0bfa2f | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 490816d9-d1d1-33a4-bd93-84ce9673127b | arn:aws:auditmanager:us-east-1:986325076436:evidence/490816d9-d1d1-33a4-bd93-84ce9673127b | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 4a29b818-ab5b-3093-819a-62d300a11bb0 | arn:aws:auditmanager:us-east-1:986325076436:evidence/4a29b818-ab5b-3093-819a-62d300a11bb0 | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 4df68cdd-9ffc-3089-9241-55d7b59d0368 | arn:aws:auditmanager:us-east-1:986325076436:evidence/4df68cdd-9ffc-3089-9241-55d7b59d0368 | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 4deaf6d3-49ac-31f4-bdb3-1a98bfd6339d | arn:aws:auditmanager:us-east-1:986325076436:evidence/4deaf6d3-49ac-31f4-bdb3-1a98bfd6339d | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 4f572765-62a3-3cd9-a580-ff00c43f21d7 | arn:aws:auditmanager:us-east-1:986325076436:evidence/4f572765-62a3-3cd9-a580-ff00c43f21d7 | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 4e32a4c2-7ea3-3ab6-b9ee-464fb10bffe7 | arn:aws:auditmanager:us-east-1:986325076436:evidence/4e32a4c2-7ea3-3ab6-b9ee-464fb10bffe7 | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 4fd27a39-ccd7-3655-a1d5-efd66cef9d1e | arn:aws:auditmanager:us-east-1:986325076436:evidence/4fd27a39-ccd7-3655-a1d5-efd66cef9d1e | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 4f510820-4073-3ce9-9842-13a16d4d2490 | arn:aws:auditmanager:us-east-1:986325076436:evidence/4f510820-4073-3ce9-9842-13a16d4d2490 | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 4ff33d80-720b-3498-8f84-cc90fc85986f | arn:aws:auditmanager:us-east-1:986325076436:evidence/4ff33d80-720b-3498-8f84-cc90fc85986f | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 508e7152-2d92-3110-8859-99373530f853 | arn:aws:auditmanager:us-east-1:986325076436:evidence/508e7152-2d92-3110-8859-99373530f853 | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 5152ee13-b87a-36e4-a086-a9170318f182 | arn:aws:auditmanager:us-east-1:986325076436:evidence/5152ee13-b87a-36e4-a086-a9170318f182 | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 50af5158-2c22-3db0-b172-45bd83a65911 | arn:aws:auditmanager:us-east-1:986325076436:evidence/50af5158-2c22-3db0-b172-45bd83a65911 | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 540345bd-643c-33b2-b9d2-8d0b3301a53a | arn:aws:auditmanager:us-east-1:986325076436:evidence/540345bd-643c-33b2-b9d2-8d0b3301a53a | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 50f0c31a-7bdc-3194-9411-91ad260dee73 | arn:aws:auditmanager:us-east-1:986325076436:evidence/50f0c31a-7bdc-3194-9411-91ad260dee73 | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 2ccdc509-5de9-3c82-a885-6a0453569cad | arn:aws:auditmanager:us-east-1:986325076436:evidence/2ccdc509-5de9-3c82-a885-6a0453569cad | 1ba55405-958a-3ec7-bd6e-21ed638842fb | Configuration data | -                                                                                            | Requirement 10: Track and monitor all access to network resources and cardholder data                 |
| 54772aae-6c38-3ddd-9f97-e7d52c240eb0 | arn:aws:auditmanager:us-east-1:986325076436:evidence/54772aae-6c38-3ddd-9f97-e7d52c240eb0 | a4b7094b-1448-3177-9a7b-3be98ede43ba | Configuration data | -                                                                                            | Requirement 7: Restrict access to cardholder data by business need to know                            |
| 51bab48d-5594-33f0-ac23-8b5f4028fc0a | arn:aws:auditmanager:us-east-1:986325076436:evidence/51bab48d-5594-33f0-ac23-8b5f4028fc0a | 3c0a9139-4c86-3a1a-b495-811f1561973f | Configuration data | -                             [...]

2021-05-31 15:00 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +				Type:        proto.ColumnType_STRING,
Is it correct?
Seems like the value should be of `JSON` type?

2021-05-31 15:00 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +func listAwsAuditManagerEvidences(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func listAuditManagerEvidences(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-05-31 15:03 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +func getAwsAuditManagerEvidence(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getAuditManagerEvidence(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-05-31 15:09 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +	EvidenceID := d.KeyColumnQuals["id"].GetStringValue()
Use `lowerCamelCase` standard when define any variables

2021-05-31 15:31 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +			ShouldIgnoreError: isNotFoundError([]string{"ResourceNotFoundException"}),
@visiit Can you please check for other errors, i.e `InvalidParameter` ?
```
Error: InvalidParameter: 4 validation error(s) found.
- minimum field size of 36, GetEvidenceInput.AssessmentId.
- minimum field size of 1, GetEvidenceInput.ControlSetId.
- minimum field size of 36, GetEvidenceInput.EvidenceFolderId.
- minimum field size of 36, GetEvidenceInput.EvidenceId.
```

2021-05-31 15:35 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +				Type:        proto.ColumnType_STRING,
![Uploading image.png…]()

2021-05-31 15:36 UTC, Subhajit97 commented on aws/table_aws_auditmanager_evidence.go
> +
@visiit Please put a comment here

2021-05-31 15:37 UTC, Subhajit97 requested changes
@visiit Please see comments, thanks!

2021-06-23 15:53 UTC, Subhajit97 approved these changes
LGTM

2021-07-05 07:41 UTC, rajmohanty17 commented
@Subhajit97 we have already aws_auditmanager_evidence_folder released. Is this different ?

2021-07-08 15:47 UTC, cbruno10 approved these changes

2021-07-08 15:53 UTC, merged