Add a column to store CacheCluster.SnapshotRetentionLimit property in table aws_elasticache_cluster. Closes #448
turbot/steampipe-plugin-aws pull request #458
Opened 2021-05-31 17:51 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  cache_cluster_id,
  cache_node_type,
  at_rest_encryption_enabled,
  snapshot_retention_limit
from
  aws_elasticache_cluster
where
  snapshot_retention_limit > 15;
```
+------------------+-----------------+----------------------------+--------------------------+
| cache_cluster_id | cache_node_type | at_rest_encryption_enabled | snapshot_retention_limit |
+------------------+-----------------+----------------------------+--------------------------+
+------------------+-----------------+----------------------------+--------------------------+
```

2021-06-01 07:22 UTC, Subhajit97 commented on aws/table_aws_elasticache_cluster.go
> +				Hydrate:     getElastiCacheCluster,
@Priyanka585464 do we need hydrate for this?
Don't we get value in `LIST`?

2021-06-01 07:24 UTC, Subhajit97 commented on docs/tables/aws_elasticache_cluster.md
> +### Check Minimum snapshot retention period for Redis cluster is 15 days
@Priyanka585464 Can we update the example to check `List clusters with automatic backup disabled`?

2021-06-01 07:26 UTC, Subhajit97 requested changes
@Priyanka585464 I have added some suggestions. Please see comments, thanks!
Also, please attach test logs.

2021-06-04 12:55 UTC, Subhajit97 approved these changes
LGTM

2021-06-04 19:52 UTC, cbruno10 approved these changes

2021-06-04 19:54 UTC, merged