Add table aws_vpc_vpn_connection #481
turbot/steampipe-plugin-aws pull request #486
Opened 2021-06-09 08:38 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_vpc_vpn_connection []

PRETEST: tests/aws_vpc_vpn_connection

TEST: tests/aws_vpc_vpn_connection
Running terraform
aws_customer_gateway.named_test_resource: Refreshing state... [id=cgw-00d140cced7d1c918]
aws_vpc.named_test_resource: Refreshing state... [id=vpc-0be05820bd5dcbc81]
aws_vpn_gateway.named_test_resource: Refreshing state... [id=vgw-01f4243ea3a62d8ed]
aws_vpn_connection.named_test_resource: Refreshing state... [id=vpn-0e6b18be9be424b17]
aws_vpn_connection.named_test_resource: Modifying... [id=vpn-0e6b18be9be424b17]
aws_vpn_connection.named_test_resource: Modifications complete after 2s [id=vpn-0e6b18be9be424b17]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

account_id = "352685002396"
customer_gateway_id = "cgw-00d140cced7d1c918"
resource_aka = "arn:aws:ec2:us-east-1:352685002396:vpn-connection/vpn-0e6b18be9be424b17"
resource_id = "vpn-0e6b18be9be424b17"
resource_name = "turbottest32845"
type = "ipsec.1"
vpn_gateway_id = "vgw-01f4243ea3a62d8ed"

Running SQL query: test-get-query.sql
[
  {
    "customer_gateway_id": "cgw-00d140cced7d1c918",
    "type": "ipsec.1",
    "vpn_connection_id": "vpn-0e6b18be9be424b17",
    "vpn_gateway_id": "vgw-01f4243ea3a62d8ed"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "customer_gateway_id": "cgw-00d140cced7d1c918",
    "type": "ipsec.1",
    "vpn_connection_id": "vpn-0e6b18be9be424b17",
    "vpn_gateway_id": "vgw-01f4243ea3a62d8ed"
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "352685002396",
    "akas": [
      "arn:aws:ec2:us-east-1:352685002396:vpn-connection/vpn-0e6b18be9be424b17"
    ],
    "tags": {
      "name": "turbottest32845"
    },
    "title": "vpn-0e6b18be9be424b17"
  }
]
✔ PASSED

POSTTEST: tests/aws_vpc_vpn_connection

TEARDOWN: tests/aws_vpc_vpn_connection

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### VPN connection basic info

```sql
select
  vpn_connection_id,
  state,
  type,
  vpn_gateway_id,
  customer_gateway_id,
  region
from
  aws_vpc_vpn_connection;

+-----------------------+-----------+---------+-----------------------+-----------------------+-----------+
| vpn_connection_id     | state     | type    | vpn_gateway_id        | customer_gateway_id   | region    |
+-----------------------+-----------+---------+-----------------------+-----------------------+-----------+
| vpn-099f3d0ee361f108c | available | ipsec.1 | vgw-079b9e9f2d2411521 | cgw-0974df978d6e09c4b | us-east-1 |
| vpn-04db9c4b380497120 | deleted   | ipsec.1 | vgw-068c692e4f15c7fec | cgw-0cf522d67422b7b6a | us-east-1 |
| vpn-0e6b18be9be424b17 | deleted   | ipsec.1 | vgw-01f4243ea3a62d8ed | cgw-00d140cced7d1c918 | us-east-1 |
+-----------------------+-----------+---------+-----------------------+-----------------------+-----------+
```

### List VPN connection options info

```sql
select
  vpn_connection_id,
  options -> 'EnableAcceleration' as enable_acceleration,
  options ->> 'LocalIpv4NetworkCidr' as local_ipv4_network_cidr,
  options ->> 'LocalIpv6NetworkCidr' as local_ipv6_network_cidr,
  options ->> 'RemoteIpv4NetworkCidr' as remote_ipv4_network_cidr,
  options ->> 'RemoteIpv6NetworkCidr' as remote_ipv6_network_cidr,
  options -> 'StaticRoutesOnly' as static_routes_only,
  options ->> 'TunnelInsideIpVersion' as tunnel_inside_ip_iersion,
  options ->> '"TunnelOptions"' as "tunnel_options"
from
  aws_vpc_vpn_connection;

+-----------------------+---------------------+-------------------------+-------------------------+--------------------------+--------------------------+--------------------+--------------------------+----------------+
| vpn_connection_id     | enable_acceleration | local_ipv4_network_cidr | local_ipv6_network_cidr | remote_ipv4_network_cidr | remote_ipv6_network_cidr | static_routes_only | tunnel_inside_ip_iersion | tunnel_options |
+-----------------------+---------------------+-------------------------+-------------------------+--------------------------+--------------------------+--------------------+--------------------------+----------------+
| vpn-0e6b18be9be424b17 | false               | <null>                  | <null>                  | <null>                   | <null>                   | true               | <null>                   | <null>         |
| vpn-099f3d0ee361f108c | false               | 10.0.0.0/16             | <null>                  | 10.0.0.0/16              | <null>                   | false              | ipv4                     | <null>         |
| vpn-04db9c4b380497120 | false               | <null>                  | <null>                  | <null>                   | <null>                   | true               | <null>                   | <null>         |
+-----------------------+---------------------+-------------------------+-------------------------+--------------------------+--------------------------+--------------------+--------------------------+----------------+
```

### List VPN tunnel info of each VPN connection

```sql
select
  vpn_connection_id,
  t -> 'AcceptedRouteCount' as accepted_route_count,
  t ->> 'CertificateArn' as certificate_arn,
  t ->> 'LastStatusChange' as last_status_change,
  t ->> 'OutsideIpAddress' as outside_ip_address,
  t ->> 'Status' as status,
  t ->> 'StatusMessage' as status_message
from
  aws_vpc_vpn_connection,
  jsonb_array_elements(vgw_telemetry) as t;

+-----------------------+----------------------+-----------------+----------------------+--------------------+--------+----------------+
| vpn_connection_id     | accepted_route_count | certificate_arn | last_status_change   | outside_ip_address | status | status_message |
+-----------------------+----------------------+-----------------+----------------------+--------------------+--------+----------------+
| vpn-099f3d0ee361f108c | 0                    | <null>          | 2021-06-08T07:54:18Z | 34.205.109.112     | DOWN   | IPSEC IS DOWN  |
| vpn-099f3d0ee361f108c | 0                    | <null>          | 2021-06-08T07:59:59Z | 50.17.255.86       | DOWN   | IPSEC IS DOWN  |
+-----------------------+----------------------+-----------------+----------------------+--------------------+--------+----------------+
```
```
</details>

2021-06-11 13:56 UTC, Subhajit97 commented on aws/table_aws_vpc_vpn_connection.go
> +			// JSON columns
```suggestion
```

2021-06-11 13:57 UTC, Subhajit97 commented on aws/table_aws_vpc_vpn_connection.go
> +			},
Add `title` column before `tags`

2021-06-11 14:05 UTC, Subhajit97 commented on aws/table_aws_vpc_vpn_connection.go
> +			//standard columns
```suggestion
			// Steampipe standard columns
```

2021-06-11 14:12 UTC, Subhajit97 commented on docs/tables/aws_vpc_vpn_connection.md
> +```
@rajeshbal65 Can we add a query to check the status of both VPN tunnels (both should be in `UP` state)?

2021-06-11 14:13 UTC, Subhajit97 requested changes
@rajeshbal65 There are few changes required. Please see comments, thanks!

2021-06-14 15:18 UTC, Subhajit97 approved these changes
LGTM

2021-06-14 16:05 UTC, rajmohanty17 approved these changes
LGTM

2021-06-14 22:15 UTC, cbruno10 approved these changes

2021-06-14 22:15 UTC, merged