Add table aws_codecommit_repository. Closes #507
turbot/steampipe-plugin-aws pull request #515
Opened 2021-06-28 12:20 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/aws_codecommit_repository []

PRETEST: tests/aws_codecommit_repository

TEST: tests/aws_codecommit_repository
Running terraform
aws_codecommit_repository.named_test_resource: Creating...
aws_codecommit_repository.named_test_resource: Still creating... [10s elapsed]
aws_codecommit_repository.named_test_resource: Creation complete after 15s [id=turbottest12584]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

resource_aka = "arn:aws:codecommit:us-east-1:013122550996:turbottest12584"
resource_id = "9c9bfe13-b5ef-4458-8194-69d55a43fb5a"
resource_name = "turbottest12584"

Running SQL query: test-list-query.sql
[
  {
    "description": "This is the Sample App Repository",
    "id": "9c9bfe13-b5ef-4458-8194-69d55a43fb5a",
    "name": "turbottest12584"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:codecommit:us-east-1:013122550996:turbottest12584"
    ],
    "title": "turbottest12584"
  }
]
✔ PASSED

POSTTEST: tests/aws_codecommit_repository

TEARDOWN: tests/aws_codecommit_repository

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  name,
  id,
  arn,
  creation_date,
  region
from
  aws_codecommit_repository
+------+--------------------------------------+------------------------------------------------+---------------------+-----------+
| name | id                                   | arn                                            | creation_date       | region    |
+------+--------------------------------------+------------------------------------------------+---------------------+-----------+
| test | 14bb2b91-46c0-4ebd-926d-d4a0be9929ce | arn:aws:codecommit:us-east-1:013122550996:test | 2021-06-28 10:01:59 | us-east-1 |
+------+--------------------------------------+------------------------------------------------+---------------------+-----------+
```
</details>

2021-07-12 06:34 UTC, Subhajit97 commented on aws/table_aws_codecommit_repository.go
> +				Description: "A description that makes the build project easy to identify.",
Fix description

2021-07-12 07:02 UTC, Subhajit97 commented on aws/table_aws_codecommit_repository.go
> +			ShouldIgnoreError: isNotFoundError([]string{"InvalidParameter"}),
Why we need `ShouldIgnoreError` for LIST?

2021-07-12 07:08 UTC, Subhajit97 commented on aws/table_aws_codecommit_repository.go
> +				Transform:   transform.FromField("Arn").Transform(arnToAkas),
```suggestion
				Transform:   transform.FromField("Arn").Transform(transform.EnsureStringArray),
```

2021-07-12 07:13 UTC, Subhajit97 commented on aws-test/tests/aws_codecommit_repository/test-not-found-query.sql
> +where name = 'dummy{{ resourceName }}';
Should we add `notFound` check, since we don't have GET?

2021-07-12 07:20 UTC, Subhajit97 commented on aws-test/tests/aws_codecommit_repository/variables.tf
> +  description     = "This is the Sample App Repository"
Can we also add `tags` to validate the hydrate function `getCodeCommitRepositoryTag`?

2021-07-12 07:46 UTC, Subhajit97 commented on docs/tables/aws_codecommit_repository.md
> +AWS CodeCommit is a secure, highly scalable, managed source control service that hosts private Git repositories. It makes it easy for teams to securely collaborate on code with contributions encrypte
```suggestion
AWS CodeCommit repository is the fundamental version control object in CodeCommit. It's where you securely store code and files for your project. It also stores your project history, from the first commit through the latest changes. You can share your repository with other users so you can work together on a project.
```

2021-07-12 07:48 UTC, Subhajit97 commented on aws/table_aws_codecommit_repository.go
> +	}
Can't we do separate `LIST` and `GET`, instead of doing in `LIST`?

2021-07-12 07:49 UTC, Subhajit97 requested changes
@bigdatasourav Please see comments, thanks!

2021-07-12 08:08 UTC, rajlearner17 approved these changes
LGTM

2021-07-15 12:29 UTC, cbruno10 approved these changes

2021-07-15 12:29 UTC, merged