Added table tableAwsEc2NetworkLoadBalancerMetricNetFlowCount and aws_ec2_application_load_balancer_metric_request_count. Closes #521, Closes #520
turbot/steampipe-plugin-aws pull request #527
Opened 2021-07-02 10:46 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-08-03 07:37 UTC, bigdatasourav commented on aws/table_aws_ec2_application_load_balancer_metric_ request_count.go
> +		Description: "AWS EC2 Application LoadBalancer Metrics - Request Count",
```suggestion
		Description: "AWS EC2 Application Load Balancer Metrics - Request Count",
```

2021-08-03 07:41 UTC, bigdatasourav commented on aws/table_aws_ec2_network_load_balancer_metric_net_flow_count.go
> +		Description: "AWS EC2 Network LoadBalancer Metrics - Net Flow Count",
```suggestion
		Description: "AWS EC2 Network Load Balancer Metrics - Net Flow Count",
```

2021-08-09 07:14 UTC, bigdatasourav approved these changes
LGTM

2021-08-09 07:25 UTC, bigdatasourav requested changes
@khushboo9024 please add doc files and example queries for this 2 tables

2021-08-11 10:14 UTC, bigdatasourav approved these changes
LGTM

2021-08-12 08:12 UTC, rajlearner17 approved these changes
LGTM

2021-08-12 08:17 UTC, merged