Get call not working for table aws_codepipeline_pipeline closes #531
turbot/steampipe-plugin-aws pull request #537
Opened 2021-07-08 11:57 UTC by ParthaI

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_codepipeline_pipeline []

PRETEST: tests/aws_codepipeline_pipeline

TEST: tests/aws_codepipeline_pipeline
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_codestarconnections_connection.example: Creating...
aws_kms_key.named_test_resource: Creating...
aws_iam_role.codepipeline_role: Creating...
aws_s3_bucket.codepipeline_bucket: Creating...
aws_codestarconnections_connection.example: Creation complete after 3s [id=arn:aws:codestar-connections:us-east-1:986325076436:connection/5f47ccdb-e5ce-4c91-b397-3942208e2867]
aws_iam_role.codepipeline_role: Creation complete after 4s [id=turbottest62061]
aws_kms_key.named_test_resource: Creation complete after 4s [id=04117e5f-53b0-4711-9c2e-14fb1ae532d6]
aws_kms_alias.s3kmskey: Creating...
aws_kms_alias.s3kmskey: Creation complete after 2s [id=alias/my-key-alias_turbottest62061]
aws_s3_bucket.codepipeline_bucket: Still creating... [10s elapsed]
aws_s3_bucket.codepipeline_bucket: Creation complete after 14s [id=turbottest62061]
aws_iam_role_policy.codepipeline_policy: Creating...
aws_codepipeline.named_test_resource: Creating...
aws_iam_role_policy.codepipeline_policy: Creation complete after 2s [id=turbottest62061:turbottest62061]
aws_codepipeline.named_test_resource: Creation complete after 4s [id=turbottest62061]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
encryption_key = arn:aws:kms:us-east-1:986325076436:alias/my-key-alias_turbottest62061
region_name = us-east-1
resource_aka = arn:aws:codepipeline:us-east-1:986325076436:turbottest62061
resource_name = turbottest62061
role_arn = arn:aws:iam::986325076436:role/turbottest62061

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:codepipeline:us-east-1:986325076436:turbottest62061",
    "encryption_key": {
      "Id": "arn:aws:kms:us-east-1:986325076436:alias/my-key-alias_turbottest62061",
      "Type": "KMS"
    },
    "name": "turbottest62061",
    "role_arn": "arn:aws:iam::986325076436:role/turbottest62061",
    "tags_src": [],
    "title": "turbottest62061"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:codepipeline:us-east-1:986325076436:turbottest62061"
    ],
    "name": "turbottest62061",
    "tags": {},
    "title": "turbottest62061"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:codepipeline:us-east-1:986325076436:turbottest62061",
    "name": "turbottest62061",
    "tags": {},
    "title": "turbottest62061"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "986325076436",
    "akas": [
      "arn:aws:codepipeline:us-east-1:986325076436:turbottest62061"
    ],
    "name": "turbottest62061",
    "region": "us-east-1",
    "title": "turbottest62061"
  }
]
✔ PASSED

POSTTEST: tests/aws_codepipeline_pipeline

TEARDOWN: tests/aws_codepipeline_pipeline

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from aws_codepipeline_pipeline where name='test-pipeline'
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------
| name          | arn                                                       | created_at | role_arn                                                                                                 | update
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------
| test-pipeline | arn:aws:codepipeline:us-east-2:986325076436:test-pipeline | <null>     | arn:aws:iam::986325076436:role/service-role/AWSCodePipelineServiceRole-us-east-1-test-steampipe-pipeline | <null>
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------

```
</details>

2021-07-12 10:10 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Hydrate:     getCodepipelinePipeline,
Is this required, since we are getting `name` from both GET and LIST?

2021-07-12 10:11 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("PipelineArn", "Metadata.PipelineArn"),
Why we need 2 different path, since we have added `Hydrate` in it?
```suggestion
				Transform:   transform.FromField("Metadata.PipelineArn"),
```

2021-07-12 10:11 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("RoleArn", "Pipeline.RoleArn"),
```suggestion
				Transform:   transform.FromField("Pipeline.RoleArn"),
```

2021-07-12 10:11 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("EncryptionKey", "Pipeline.ArtifactStore.EncryptionKey"),
```suggestion
				Transform:   transform.FromField("Pipeline.ArtifactStore.EncryptionKey"),
```

2021-07-12 10:11 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("ArtifactStores", "Pipeline.ArtifactStores"),
```suggestion
				Transform:   transform.FromField("Pipeline.ArtifactStores"),
```

2021-07-12 10:12 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("Stages", "Pipeline.Stages"),
```suggestion
				Transform:   transform.FromField("Pipeline.Stages"),
```

2021-07-12 10:12 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Hydrate:     getCodepipelinePipeline,
```suggestion
```

2021-07-12 10:12 UTC, Subhajit97 commented on aws/table_aws_codepipeline_pipeline.go
> +				Transform:   transform.FromField("PipelineArn", "Metadata.PipelineArn").Transform(transform.EnsureStringArray),
```suggestion
				Transform:   transform.FromField("Metadata.PipelineArn").Transform(transform.EnsureStringArray),
```

2021-07-12 10:13 UTC, Subhajit97 requested changes
@ParthaI Please see comments, thanks!

2021-07-12 10:20 UTC, Subhajit97 approved these changes

2021-07-15 12:27 UTC, cbruno10 approved these changes

2021-07-15 12:28 UTC, merged