Add table aws_directory_service_directory closes #544
turbot/steampipe-plugin-aws pull request #572
Opened 2021-07-28 16:03 UTC by ParthaI

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_directory_service_directory []

PRETEST: tests/aws_directory_service_directory

TEST: tests/aws_directory_service_directory
Running terraform
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_region.alternate: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_vpc.my_vpc: Creating...
aws_iam_role.my_role: Creating...
aws_iam_role.my_role: Creation complete after 4s [id=turbottest46991]
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Creation complete after 11s [id=vpc-05fc06a8667b8dbb9]
aws_subnet.my_subnet2: Creating...
aws_subnet.my_subnet1: Creating...
aws_subnet.my_subnet1: Creation complete after 3s [id=subnet-0818ba5cd9ba9db0c]
aws_subnet.my_subnet2: Creation complete after 3s [id=subnet-0041ed66088749d23]
aws_directory_service_directory.named_test_resource: Creating...
aws_directory_service_directory.named_test_resource: Still creating... [10s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [20s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [30s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [40s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [50s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m0s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m10s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m20s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m30s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m40s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [1m50s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m0s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m10s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m20s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m30s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m40s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [2m50s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m1s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m11s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m21s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m31s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m41s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [3m51s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m1s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m11s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m21s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m31s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m41s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [4m51s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m1s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m11s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m21s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m31s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m41s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [5m51s elapsed]
aws_directory_service_directory.named_test_resource: Still creating... [6m1s elapsed]
aws_directory_service_directory.named_test_resource: Creation complete after 6m6s [id=d-90676dac02]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

account_id = 986325076436
aws_partition = aws
aws_region = us-east-1
resource_aka = arn:aws:ds:us-east-1:986325076436:directory/d-90676dac02
resource_id = d-90676dac02
resource_name = turbottest46991

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:ds:us-east-1:986325076436:directory/d-90676dac02",
    "directory_id": "d-90676dac02",
    "name": "turbottest46991.com"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:ds:us-east-1:986325076436:directory/d-90676dac02"
    ],
    "name": "turbottest46991.com",
    "tags": {
      "Name": "turbottest46991"
    },
    "title": "turbottest46991.com"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "arn:aws:ds:us-east-1:986325076436:directory/d-90676dac02"
    ],
    "name": "turbottest46991.com",
    "title": "turbottest46991.com"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

POSTTEST: tests/aws_directory_service_directory

TEARDOWN: tests/aws_directory_service_directory

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```

```
</details>

2021-08-06 15:24 UTC, khushboo9024 commented on aws/service.go
> +func DirectoryServiceService(ctx context.Context, d *plugin.QueryData) (*directoryservice.DirectoryService, error) {
Function name can be `DirectoryService`, `Service`  word is getting repeated two times.

2021-08-06 15:25 UTC, khushboo9024 commented on aws-test/tests/aws_directory_service_directory/test-get-query.sql
> +where name = '{{ output.resource_name.value }}.com';
This is not get call query.

2021-08-06 15:26 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +				Name:        "connect_settings",
Please fix the ordering of columns, JSON column should come after string columns.

2021-08-06 15:27 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +				Description: "The directory size.",
Change the description.

2021-08-06 15:30 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +func listDirectiryServiceDirectorties(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listDirectoryServiceDirectories(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-08-06 15:31 UTC, khushboo9024 commented on docs/tables/aws_directory_service_directory.md
> +### List Directories of  type MicrosoftAD
```suggestion
### List MicrosoftAD type directories 
```

2021-08-06 15:32 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +			Hydrate: listDirectiryServiceDirectorties,
```suggestion
			Hydrate: listDirectoryServiceDirectories,
```

2021-08-06 15:33 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +				Description: "A RadiusSettings object that contains information about the RADIUS server",
```suggestion
				Description: "A RadiusSettings object that contains information about the RADIUS server.",
```

2021-08-06 15:33 UTC, khushboo9024 commented on aws/table_aws_directory_service_directory.go
> +				Description: "A list of tags currently associated with the Directory Service Directory",
```suggestion
				Description: "A list of tags currently associated with the Directory Service Directory.",
```

2021-08-06 15:37 UTC, khushboo9024 requested changes
Please see comments.

2021-08-10 05:47 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +				Name:        "tag_src",
```suggestion
				Name:        "tags_src",
```

2021-08-10 05:48 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +
Add check for empty input

2021-08-10 05:50 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +	arn := "arn:" + commonColumnData.Partition + ":ds:" + commonColumnData.Region + ":" + commonColumnData.AccountId + ":directory/" + *directory.DirectoryId
Use `matrixKeyRegion` to fetch the region, instead of using `commonColumnData`

2021-08-10 05:50 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +//// TRANSFORMATION FUNCTION
```suggestion
//// TRANSFORM FUNCTIONS
```

2021-08-10 06:53 UTC, khushboo9024 approved these changes
LGTM

2021-08-11 09:55 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +func getDirectoryArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDirectoryARN(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-08-11 09:55 UTC, Subhajit97 commented on aws/table_aws_directory_service_directory.go
> +//// TRANSFORM FUNCTION
```suggestion
//// TRANSFORM FUNCTIONS
```

2021-08-11 10:30 UTC, Subhajit97 approved these changes

2021-08-12 08:15 UTC, rajlearner17 approved these changes
LGTM

2021-08-12 08:17 UTC, merged