Add table ec2_capacity_reservation. Closes #542
turbot/steampipe-plugin-aws pull request #619
Opened 2021-08-20 16:47 UTC by c0d3r-arnab

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_ec2_capacity_reservation
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_ec2_capacity_reservation []

PRETEST: tests/aws_ec2_capacity_reservation

TEST: tests/aws_ec2_capacity_reservation
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ec2_capacity_reservation.named_test_resource will be created
  + resource "aws_ec2_capacity_reservation" "named_test_resource" {
      + arn                     = (known after apply)
      + availability_zone       = "us-east-1a"
      + ebs_optimized           = false
      + end_date_type           = "unlimited"
      + ephemeral_storage       = false
      + id                      = (known after apply)
      + instance_count          = 1
      + instance_match_criteria = "open"
      + instance_platform       = "Linux/UNIX"
      + instance_type           = "t2.micro"
      + owner_id                = (known after apply)
      + tags_all                = (known after apply)
      + tenancy                 = "default"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + account_id        = "632902152528"
  + availability_zone = "us-east-1a"
  + aws_partition     = "aws"
  + instance_count    = 1
  + instance_platform = "Linux/UNIX"
  + instance_type     = "t2.micro"
  + region_name       = "us-east-1"
  + resource_aka      = (known after apply)
  + resource_id       = (known after apply)
aws_ec2_capacity_reservation.named_test_resource: Creating...
aws_ec2_capacity_reservation.named_test_resource: Creation complete after 3s [id=cr-0296e11be3b264d6b]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = "632902152528"
availability_zone = "us-east-1a"
aws_partition = "aws"
instance_count = 1
instance_platform = "Linux/UNIX"
instance_type = "t2.micro"
region_name = "us-east-1"
resource_aka = "arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0296e11be3b264d6b"
resource_id = "cr-0296e11be3b264d6b"

Running SQL query: test-get-query.sql
[
  {
    "account_id": "632902152528",
    "availability_zone": "us-east-1a",
    "capacity_reservation_id": "cr-0296e11be3b264d6b",
    "instance_platform": "Linux/UNIX",
    "instance_type": "t2.micro",
    "partition": "aws",
    "region": "us-east-1",
    "state": "active"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "account_id": "632902152528",
    "availability_zone": "us-east-1a",
    "capacity_reservation_id": "cr-0296e11be3b264d6b",
    "instance_platform": "Linux/UNIX",
    "instance_type": "t2.micro",
    "partition": "aws",
    "region": "us-east-1",
    "state": "active"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0296e11be3b264d6b"
    ],
    "title": "cr-0296e11be3b264d6b"
  }
]
✔ PASSED

POSTTEST: tests/aws_ec2_capacity_reservation

TEARDOWN: tests/aws_ec2_capacity_reservation

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  capacity_reservation_arn,
  capacity_reservation_id,
  instance_type,
  state
from
  aws_ec2_capacity_reservation;
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
| capacity_reservation_arn                                                     | capacity_reservation_id | instance_type | state     |
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0358ac3305d546c1d | cr-0358ac3305d546c1d    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0c07a3407b16c9f71 | cr-0c07a3407b16c9f71    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0401ebd31315c8cc6 | cr-0401ebd31315c8cc6    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0e866f1c8e19c2572 | cr-0e866f1c8e19c2572    | t2.micro      | active    |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-06dce73c0cd39b78f | cr-06dce73c0cd39b78f    | t2.micro      | cancelled |
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
> select
  capacity_reservation_arn,
  capacity_reservation_id,
  instance_type,
  state
from
  aws_ec2_capacity_reservation
where
  state = 'cancelled';
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
| capacity_reservation_arn                                                     | capacity_reservation_id | instance_type | state     |
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0358ac3305d546c1d | cr-0358ac3305d546c1d    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0c07a3407b16c9f71 | cr-0c07a3407b16c9f71    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-0401ebd31315c8cc6 | cr-0401ebd31315c8cc6    | t2.micro      | cancelled |
| arn:aws:ec2:us-east-1:632902152528:capacity-reservation/cr-06dce73c0cd39b78f | cr-06dce73c0cd39b78f    | t2.micro      | cancelled |
+------------------------------------------------------------------------------+-------------------------+---------------+-----------+
>
```
</details>

2021-08-24 05:23 UTC, bigdatasourav commented on aws-test/tests/aws_ec2_capacity_reservation/variables.tf
> +
```suggestion
```

2021-08-24 05:24 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +		Description: "AWS EC2 capacity reservation",
```suggestion
		Description: "AWS EC2 Capacity Reservation",
```

2021-08-24 10:18 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +				Description: "The Amazon Resource Name (ARN) of the capacity reservation.",
Please add arn column after ID

2021-08-24 10:21 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +func getAwsEc2CapacityReservationAkas(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
we dont need this as we are getting arn in api response

2021-08-24 10:23 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +				Hydrate:     getAwsEc2CapacityReservationAkas,
```suggestion
```

2021-08-24 10:24 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +				Transform:   transform.FromValue().Transform(transform.EnsureStringArray),
use capacity_reservation_arn

2021-08-24 10:26 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +			},
Add tag_src column

2021-08-24 10:28 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +				Name:        "tags",
Format tags as map[string]string{}, For reference check aws_tagging_resource table.

2021-08-24 10:30 UTC, bigdatasourav requested changes
@c0d3r-arnab Please check the requested changes also add one get call example in example query

2021-08-25 06:12 UTC, bigdatasourav commented on aws/table_aws_ec2_capacity_reservation.go
> +				Description: "The total number of instances for which the capacity reservation reserves capacity",
```suggestion
				Description: "The total number of instances for which the capacity reservation reserves capacity.",
```

2021-08-25 06:23 UTC, bigdatasourav approved these changes
LGTM

2021-08-25 06:52 UTC, rajlearner17 approved these changes
LGTM

2021-08-25 06:53 UTC, merged