Add table aws_glue_catalog_table Closes #955
turbot/steampipe-plugin-aws pull request #963
Opened 2022-04-28 11:41 UTC by karanpopat

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Outputs:

aws_account = "533793682495"
aws_region = "us-east-1"
database_name = "turbottest1778"
resource_aka = "arn:aws:glue:us-east-1:533793682495:table/turbottest1778/turbottest1778"
resource_name = "turbottest1778"

Running SQL query: test-get-query.sql
[
  {
    "catalog_id": "533793682495",
    "description": "integration testing",
    "name": "turbottest1778"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "catalog_id": "533793682495",
    "description": "integration testing",
    "name": "turbottest1778"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "description": "integration testing",
    "name": "turbottest1778",
    "region": "us-east-1"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:glue:us-east-1:533793682495:table/turbottest1778/turbottest1778"
    ],
    "name": "turbottest1778",
    "region": "us-east-1",
    "title": "turbottest1778"
  }
]
✔ PASSED

POSTTEST: tests/aws_glue_catalog_table

TEARDOWN: tests/aws_glue_catalog_table

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  name,
  catalog_id,
  create_time,
  description,
  database_name
from
  aws_glue_catalog_table;
+----------+--------------+---------------------------+-------------+---------------+
| name     | catalog_id   | create_time               | description | database_name |
+----------+--------------+---------------------------+-------------+---------------+
| elb_logs | 533793682495 | 2019-08-09T02:06:46+05:30 | <null>      | sampledb      |
+----------+--------------+---------------------------+-------------+---------------+

> select
  catalog_id,
  count(name) as table_count
from
  aws_glue_catalog_table
group by
  catalog_id;
+--------------+-------------+
| catalog_id   | table_count |
+--------------+-------------+
| 533793682495 | 1           |
+--------------+-------------+```
</details>

2022-05-05 05:54 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "The time when the table definition was created in the Data Catalog.",
```suggestion
				Description: "The time when the table definition was created in the data catalog.",
```

2022-05-05 05:55 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "The table name. For Hive compatibility, this must be entirely lowercase.",
```suggestion
				Description: "The table name.",
```

2022-05-05 05:56 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "The name of the database where the table metadata resides. For Hive compatibility, this must be all lowercase.",
```suggestion
				Description: "The name of the database where the table metadata resides.",
```

2022-05-05 05:56 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "Indicates whether the table has been registered with Lake Formation.",
```suggestion
				Description: "Indicates whether the table has been registered with lake formation.",
```

2022-05-05 05:58 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "If the table is a view, the expanded text of the view; otherwise null.",
```suggestion
				Description: "If the table is a view, the expanded text of the view otherwise null.",
```

2022-05-05 05:58 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +				Description: "If the table is a view, the original text of the view; otherwise null.",
```suggestion
				Description: "If the table is a view, the original text of the view otherwise null.",
```

2022-05-05 06:06 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +			Hydrate:       listGlueCatalogTables,
Can we add optional quals for limiting the results?
In doc, I can see the `catalog_id`, `databse_name` etc can be use as optional quals.

2022-05-05 06:08 UTC, ParthaI commented on docs/tables/aws_glue_catalog_table.md
> +### List tables with retention less than 30 days
```suggestion
### List tables with retention period less than 30 days
```

2022-05-05 06:09 UTC, ParthaI commented on aws/table_aws_glue_catalog_table.go
> +		plugin.Logger(ctx).Debug("getGlueCatalogTable", "ERROR", err)
```suggestion
		plugin.Logger(ctx).Error("getGlueCatalogTable", "ERROR", err)
```

2022-05-05 08:17 UTC, rajlearner17 commented
@karanpopat pls check this 
```
> select
  name,
  catalog_id,
  create_time,
  description,
  database_name
from
  aws_glue_catalog_table;
Error: rpc error: code = Internal desc = 'List' call for table 'aws_glue_catalog_table' is missing 2 required quals: 
    column:'catalog_id' operator: =
    column:'database_name' operator: =
 (SQLSTATE HV000)```

2022-05-05 09:37 UTC, ParthaI approved these changes
LGTM

2022-05-05 11:41 UTC, rajlearner17 commented
Queries working fine

2022-05-05 15:57 UTC, cbruno10 requested changes
@karanpopat Please see comments, thanks!

2022-05-05 15:57 UTC, cbruno10 commented on aws/table_aws_glue_catalog_table.go
> +				Type:        proto.ColumnType_STRING,
@karanpopat Why is this a string? The API shows this field as a number instead. If it's a number, the example would also not need casting.

2022-05-06 13:18 UTC, cbruno10 approved these changes

2022-05-09 05:21 UTC, merged